### ISSUE TITLE
Error on running flex dashboard

### ISSUE THREAD

**Issue by webbedfeet** [rstudio/flexdashboard#10]
When I try to run one of the examples from the website, I'm getting the following error:

```
Error in append(extra_dependencies, list(html_dependency_jquery(), html_dependency_stickytableheaders())) : 
  could not find function "html_dependency_jquery"
```

Am I missing something?

**Comment by jjallaire** [comment]
You need to update to the latest version of the rmarkdown package from CRAN.

On Fri, Mar 11, 2016 at 11:10 AM, Abhijit Dasgupta <notifications@github.com
