### ISSUE TITLE
Flexdasboard

### ISSUE THREAD

**Issue by mimeides** [rstudio/flexdashboard#104]
Hi, Flexdashboard ..; really magic !!!
My question is :  Can we put 2 graphs (vert or Hori) in same tabset 
Example :
.....
Column {.tabset .tabset-fade}
### A
  Graph1  || Graph2
### B
Graph1  
Graph2

Thks a lotssss !!!

Mimeides !

**Comment by jjallaire** [comment]
No unfortunately there isn't a way to do this right now.

**Comment by mimeides** [comment]
thks a lots !!!!
but   grreatttt   packagee !!!!!

Bye

Mimeides

**Comment by cpsievert** [comment]
Duplicate of https://github.com/rstudio/flexdashboard/issues/265
