### ISSUE TITLE
Error: could not find function "xpath_class" when deploying to shinyapps.io

### ISSUE THREAD

**Issue by pssguy** [rstudio/flexdashboard#107]
Flexdashboard app with shiny runtime
[here](https://mytinyshinys.shinyapps.io/wikiGuardianFlexDB/)
Tried ??xpath_class and got no results

The code where error occurs is old but  does work locally
The input data is from a reactive

```{r }


output$wikiCard <- renderUI({
  req(data)
  
  theName <- str_replace_all(data()$vals[1]," ","_")
  url <- paste0("http://en.wikipedia.org/wiki/",theName)
  test <- http_status(GET(url))
  
  if (test$category == "client error")
    return()

  vcard <- read_html(url) %>%
    html_nodes(".vcard")
  
  if (length(vcard) == 0)
    return()
  
  vcardInfo <- vcard[[1]]
  
  HTML(as(vcardInfo,"character"))
})

 uiOutput("wikiCard")

```

**Comment by jjallaire** [comment]
It looks like that method is in the `selectr` package: https://github.com/sjp/selectr/blob/master/R/xpath.R

So you probably need to do a `require(selectr)` somewhere to ensure that it gets detected and deployed along with your app.

**Comment by jjallaire** [comment]
This is a shinyapps issue rather than a flexdashboard issue, so if the above

**Comment by pssguy** [comment]
Thanks. Tried adding library(selectr) with no joy so will raise with shinyapps google group

**Comment by pssguy** [comment]
It seems that upgrading to R v 3.3.2 made the difference
