### ISSUE TITLE
Dynamic user inputs not rendering in local browser nor on reload of browser on shiny-server

### ISSUE THREAD

**Issue by jfredtx** [rstudio/flexdashboard#108]
[test_mtcars.txt](https://github.com/rstudio/flexdashboard/files/769572/test_mtcars.txt)

I don't know if this question is better posed the shiny-server or r-markdown repos, but I am having a problem with the user interface dynamically updating inputs on reload of a flexdashboard. I have used `runtime: shiny` and  `runtime: shiny_prerendered` but still get the same result.

Scenario - user selects from a list of static inputs, and that static input determines the elements of another input list.  I have tried with `uiOutput("x")`/`output$x<-renderUI()` , simply `renderUI()`, and `updateSelectInput()` (with `observe`) methods - all with the same result.  A reactive selection of input choices based on the initial selection feeds those methods. The methods all work fine in a traditionally styled Shiny App.

With rmarkdown and flexdashboard, the document renders fine with Rstudio, but when deployed on shiny-server after a render, it does not load the dynamic user inputs.

I've traced the websocket messages in the console for a successful load and for a non-successful load - it appears that the dynamic outputs are just not getting called/invalidated upon reload of the .Rmd document.

If I make a change to the .Rmd file in RStudio server, save it, and then reload from shiny-server in the browser it works the first time. But, if I re-load the file, it does not update the dynamic inputs (and hence  the application hangs).

This makes me think it is an issue with r-markdown and some form of caching, as it renders ok initially or when the render is forced (as in RStudio).

I will post a code example to illustrate this behavior, but I can't find a lot of information on dynamic inputs with flexdashboard and Rmarkdown on shiny-server. Using latest CRAN versions of Rmarkdown, Rstudio, shiny, flexdashboard and shiny-server. Will test with RStudio Connect once I get that up and running.

I attached a text file with a simple rmarkdown/flexdashboard non-working example (when opened from Rstudio browser with "Open in Browser") if local, or on shiny-server (test_mtcars.txt).

Regards,
Jason

**Comment by faigl** [comment]
Hi @jfredtx !

see the solution:
https://github.com/rstudio/shiny-server/issues/295

**Comment by jfredtx** [comment]
Hi @faigl ,

Thanks for the cross reference. If I understand correctly, it is because in my sample code, I have one level of indentation n the runtime statement - and since I have sub items under output, it thinks `runtime: shiny` is part of that output context. So, what you are saying is that removing the spaces/indentation in front of `runtime: shiny` should solve the issue. Such a simple solution. Thanks!  That `yaml` statement is very sensitive to indentation, as I have learned. If that is correct, I will try it and close this issue.

Regards,
Jason

**Comment by jfredtx** [comment]
Indeed, the solution is simple and it works.  Just ensure that `runtime: shiny` is on its own line (not indented in the `yaml` header. 

Thus, in the example I posted above, just change the yaml header to:
```
---
title: "Dynamic UI Test"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---
```

**Comment by Vimath** [comment]
I have developed a webapp using flex dashboard and shiny. I am running rstudio server on aww instance with Ubuntu on it. I had the same issue but after I replaced the “runtime:shiny” on the top it is now rendering the charts in the browser also. Thanks for this one. My next thing is how do I create an url and send it to co workers to access this web app ?
