### ISSUE TITLE
pandoc document conversion failed with error 1

### ISSUE THREAD

**Issue by GreenEric** [rstudio/flexdashboard#110]
Dear JJ & Allaire,
Thanks for the great work. I just installed the moment I saw it, and I do believe it shall improve my work in great deal. Yet, I faced some difficulties which I have no clue.

I just follow the instructions, File>New File>R markdown>From template>Flex Dashboard.
Then it generates the file.  it pops this,
**pandoc document conversion failed with error 1**

> pandoc.exe: dashboard.html: hClose: resource exhausted (No space left on device)
Error: pandoc document conversion failed with error 1
In addition: Warning message:
running command '"C:/Users/Eric/AppData/Local/Pandoc/pandoc" +RTS -K512m -RTS dashboard.utf8.md --to html --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output dashboard.html --smart --email-obfuscation none --self-contained --standalone --section-divs --template "C:\Users\Eric\Documents\R\win-library\3.3\flexdashboard\rmarkdown\templates\flex_dashboard\resources\default.html" --variable "theme:cosmo" --include-in-header "C:\Users\Eric\AppData\Local\Temp\Rtmp0sEaEQ\rmarkdown-str3e2827a7467.html" --mathjax --variable "mathjax-url:https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML" --include-in-header "C:\Users\Eric\AppData\Local\Temp\Rtmp0sEaEQ\file3e286c2b1398html" --highlight-style pygments --include-before-body "C:\Users\Eric\AppData\Local\Temp\Rtmp0sEaEQ\file3e2840ef44de.html" --include-after-body "C:\Users\Eric\AppData\Local\Temp\Rtmp0sEaEQ\file3e2884971ef.html"' had status 1 
Execution halted

I also noticed the file is beginning with,

> title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill

so, I modified it as,

> title: "Untitled"
output: 
  flexdashboard::flex_dashboard: flex_dashboard 
    orientation: columns
    vertical_layout: fill

then it comes to another error message.

> Error in yaml::yaml.load(string, ...) : 
  Scanner error: mapping values are not allowed in this context at line 4, column 16
Calls: <Anonymous> ... parse_yaml_front_matter -> yaml_load_utf8 -> <Anonymous> -> .Call
Execution halted

How should I do to work with your great work?
Can't thank enough,

Eric

**Comment by gadenbuie** [comment]
This particular message seems relevant

```
pandoc.exe: dashboard.html: hClose: resource exhausted (No space left on device)
```

but I'd expect other space-related problems to be more evident. Regardless, I'm hoping you've found a solution to your problem. If not, feel free to comment or open a new issue!
