### ISSUE TITLE
Value Box Display Blank Page

### ISSUE THREAD

**Issue by dwy904** [rstudio/flexdashboard#111]
I tried using the following example code, but the output is a white page with a small number on the upper left of the page:

valueBox(42, caption = "Errors", icon="fa-thumbs-down")

I am wondering if there is any step I missed.

**Comment by gadenbuie** [comment]
Hi! Thanks for the question with apologies for the delay – I hope you've been able to figure this out. For posterity, the section on [Value Boxes](https://pkgs.rstudio.com/flexdashboard/articles/using.html#value-boxes) in the [Using flexdashboard article](https://pkgs.rstudio.com/flexdashboard/articles/using.html) covers how `valueBox()` is used. In particular, you need to place the `valueBox()` under a level-3 heading (`###`).

````markdown
Row
-----------------------------------------------------------------------

### Articles per Day

```{r}
valueBox(42, icon = "fa-pencil")
```
````
