### ISSUE TITLE
IE 11 JavaScript Error

### ISSUE THREAD

**Issue by jdiedesch** [rstudio/flexdashboard#119]
I'm encountering a problem viewing flexdashboard documents in IE 11 (file stored locally). Any guidance/suggestions are much appreciated.

A trivial example:

```
---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---
{r setup, include=FALSE}
library(flexdashboard)

Column {data-width=650}
-----------------------------------------------------------------------

### The simplest flexdashboard
```
**The error message:**

![image](https://cloud.githubusercontent.com/assets/26704255/25544538/c8aa719c-2c0f-11e7-82c1-8180fdb1f0b8.png)

**Comment by jdiedesch** [comment]
In explaining the problem to a colleague, I found my way to the solution. The problem was with a default compatibility view for intranet sites. After disabling that setting, there are no errors.

**Comment by jjallaire** [comment]
Excellent!
