### ISSUE TITLE
ggplotly-like resize

### ISSUE THREAD

**Issue by Monduiz** [rstudio/flexdashboard#120]
I am only using ggplotly for one thing: it resizes flawlessly a plot to the available space.

I would love to not have to use ggplotly, is it possible to build that feature in flexdashboard?

**Comment by jjallaire** [comment]
flexdashboard actually already has some facilities for automatic resizing
of static images. See discussion here:
http://rmarkdown.rstudio.com/flexdashboard/using.html#r_graphics

In short, you can either provide fig.height and fig.width values to the
chunk which match your intended aspect ratio or you can use Shiny (the
latter provides better resizing at the cost of requiring an R back end).

**Comment by Monduiz** [comment]
From the documention: "We’ve specified an explicit fig.height and fig.width for each chart so that their rendered size fits their flex container as closely as possible. Note that the ideal values for these dimensions typically need to be determined by experimentation."

I have used those and they are not automatic. You do have to experiment to find what works.
I only need to wrap a ggplot2 chart with ggplotly and it will fit perfectly every time. I was thinking of the same functionality. I would rather not have to use plotly.

**Comment by jjallaire** [comment]
Yes, if you want full automatic resizing then you can get this from Shiny
(at the cost of requiring R for deployment/display). See
http://rmarkdown.rstudio.com/flexdashboard/shiny.html#simple_example for a
simple example

**Comment by Monduiz** [comment]
True, shiny will provide that but I guess this is what I am referring to: requiring the backend of shiny is a problem. Maybe there is no way to implement ggplotly's convenience of automatic resizing. The fig settings are very finicky and never quite get you to an optimal resizing of chart and labels.

**Comment by jjallaire** [comment]
The only way to implement ggplotly's convenience of automatic resizing is
literally to re-implement ggplotly! (i.e. a library that renders ggplot in
JavaScript). This is on the order of hundreds thousands of hours of work so
I'd suggest either (a) fiddling with aspect ratio until you are happy; (b)
accept whatever negative externalities ggplotly imposes; or (c) use shiny.
