### ISSUE TITLE
storyboard data-commentary-width ignored with a back-tick in the title

### ISSUE THREAD

**Issue by vnijs** [rstudio/flexdashboard#123]
It seems data-commentary-width is ignored if the last non-space character in the title is a back-tick. See example below where back-ticks are used around "Frame 2". If a non-space character is included between the last back-tick and the with argument it works fine.

    ---
    title: "Storyboard Commentary"
    output: 
      flexdashboard::flex_dashboard:
        storyboard: true
    ---
    
    ### Frame 1 {data-commentary-width=500}
    
    ```{r}
    ```
    
    *** 
    
    Some commentary about Frame 1.
    
    ### `Frame 2` {data-commentary-width=500}
    
    ```{r}
    ```
    
    *** 
    
    Some commentary about Frame 2.
    
    ### `Frame 3` works fine because the back-tick is not the last character {data-commentary-width=500}
    
    ```{r}
    ```
    
    *** 
    
    Some commentary about Frame 3.

**Comment by jjallaire** [comment]
I think that an issue with pandoc's markdown parsing, I would report the
issue over on the pandoc repo

**Comment by vnijs** [comment]
Could be. However, does pandoc have anything like `{data-commentary-width=500}`? Just to be clear, the issue is that the `{data-commentary-width=500}` statement is not used by flexdashboard. 

If it is a pandoc issue I'm not sure how to turn this into a reproducible example that doesn't use flexdashboard.

**Comment by jjallaire** [comment]
I tried to create a trivial reproducible example for pandoc but couldn't,
so you are correct that this is something idiosyncratic to flexdashboard.
I'll take a closer look.

**Comment by jjallaire** [comment]
It turns out this is an issue in pandoc which is actually *fixed* in the most recent version of pandoc (1.19.2 is the one I tried against) which is why I couldn't repro it there.  You should be able to get this working by just installing a more recent version of pandoc on your system (rmarkdown automatically uses the most recent version it finds).

**Comment by vnijs** [comment]
Thanks @jjallaire
