### ISSUE TITLE
Inconsistent theme?

### ISSUE THREAD

**Issue by nicholaelaw** [rstudio/flexdashboard#126]
Hi there, I'm building a website with `rmarkdown`, with a few pages built using `flexdashboard`. In my tinkering, I find it odd that while vanilla `rmarkdown::html_document` uses `navbar-default` class for the navbar, `flexdashboard` uses `navbar-inverse` instead.

Is there a practical reason for this, or is it just a design choice? If it is a design choice, is there a way to force `flexdashboard` to use `navbar-default`, or `html_document` to use `navbar-inverse`? I want a unified look for my website, and I really don't want to write more whacky CSS overrides.

**Comment by jjallaire** [comment]
Yes, it's a design choice based on the notion that navbar-inverse looks better for dashboards. For rmarkdown you can change to inverse this way:

```yaml
name: "my-website"
navbar:
  title: "My Website"
  type: inverse
```

For flexdashboard you'd need a JS chunk that does this:

    ```js
    $('.navbar-inverse').removeClass('navbar-inverse').addClass('navbar-default');
    ```

**Comment by nicholaelaw** [comment]
Hmm, thanks. I noticed that none of the themes offered is dark. Perhaps one of the reasons to use inverse themes is to prevent usually bright graphs on dark background?

**Comment by jjallaire** [comment]
Yeah we haven't supported dark themes b/c they tend to have too much
contrast with plots/widgets that have white backgrounds.
