### ISSUE TITLE
flexdashboard.js not properly included in HTML (causes page to break) when rendered from a shiny app in shiny server

### ISSUE THREAD

**Issue by daattali** [rstudio/flexdashboard#127]
Sorry for the long obscure title - the bug seems similarly obscure :)

I'm able to reproduce this on any ubuntu machine I spin up with a shiny server. When rendering a flexdashboard and providing it as an HTML to download from within a shiny app, it works fine when running through RStudio IDE (both desktop and server), but when it's served through shiny server I get a javascript console error "unexpected identifier". If I look at the problem, it brings me to this javascript:

![image](https://cloud.githubusercontent.com/assets/952340/26273593/e26ac904-3d00-11e7-8989-362d7606d709.png)

You can see (if you click on it and see an enlarged image) what happened - some of the comments in flexdashboard.js got stripped away and interpreted as code, which breaks everything. I don't understand why this happens.

Consider this app:

app.R

```
ui <- fluidPage(
  downloadButton("report", "Generate report")
)
server <- function(input, output) {
  output$report <- downloadHandler(
    filename = "report.html",
    content = function(file) {
      tempReport <- file.path(tempdir(), "report.Rmd")
      file.copy("report.Rmd", tempReport, overwrite = TRUE)
      rmarkdown::render(tempReport, output_file = file,
        envir = new.env(parent = globalenv())
      )
    }
  )
}

shinyApp(ui, server)
```

report.Rmd

```
---
output: flexdashboard::flex_dashboard
---

### Section 1

Foo

### Section 2

Bar

```

This plain flexdashboard results in that problem.

To see it in action: http://104.131.143.157:3838/flex/ serves that exact flexdashboard , and you see it works. http://104.131.143.157:3838/test/ renders that same flexdashboard from a shiny app on a shiny server - try downloading it and opening it. If I run the app from RStudio, it's fine.

I can give you credentials to this server if you ask me privately, it's a test server for just this bug.

**Comment by daattali** [comment]
Things I've tried:

- installing latest pandoc (1.19)
- linking pandoc to `/usr/lib/rstudio-server/bin/pandoc/pandoc`
- bashing my head on the desk for about 5 hours

**Comment by jjallaire** [comment]
@jcheng5 Could you take a look at this one?

**Comment by daattali** [comment]
Update: now the problem disappeared. Is it possible that this was indeed a pandoc problem and that somehow the pandoc version was cached earlier?

**Comment by jjallaire** [comment]
I'm not sure at all what the problem might have been as it involves so many
different parts. If we can get a repro with the older pandoc then that's
definitely the culprit (seems a decent possibility).

**Comment by daattali** [comment]
Yeah I can repro again, it just takes 5 min to set up another server, I'll
post here when I do it

---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com <http://attalitech.com>

**Comment by daattali** [comment]
OK new server with the issue reproducing:

http://192.241.238.88:3838/test/

**Comment by jjallaire** [comment]
Do you believe that the issue is just pandoc 1.17 vs. pandoc 1.19?

**Comment by daattali** [comment]
Maybe? But that doesn't explain (at least not trivially to me) why 1. it
works when being served outside shiny server and 2. why it still didn't
work for half an hour after making the changes, but it worked 10 hours later

---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com <http://attalitech.com>

**Comment by jcheng5** [comment]
(I'll take a look tomorrow)

**Comment by daattali** [comment]
Thanks Joe

**Comment by jcheng5** [comment]
@daattali Can you email me (or gist) the app to repro?

**Comment by daattali** [comment]
The app at http://192.241.238.88:3838/test/ is exactly what I wrote in the first comment, same code.

**Comment by jcheng5** [comment]
Sorry, don't know how I missed that

**Comment by jcheng5** [comment]
Not getting a repro here. Do you mind emailing me the creds for your repro server?

**Comment by daattali** [comment]
emailing you

**Comment by jcheng5** [comment]
This is indeed due to the pandoc version. It looks like Shiny Server ships with pandoc 1.12.3, which has this problem. I wasn't reproing this because my test server had the distro's pandoc installed, which is much newer (1.16.0.2). Once I removed the system pandoc, then R Markdown will use whatever pandoc is newest, according to this: https://github.com/rstudio/rmarkdown/issues/289#issuecomment-59607882

I'll be sure to update the pandoc version in Shiny Server for the next release. Thanks Dean!

**Comment by daattali** [comment]
Does this explain why rendering it from R console or from a shiny app running from rstudio = ok, but rendering from shiny server = error? As far as I know there was only one pandoc version installed on the machine. I'm fairly certain that yes pandoc is the reason for this, but I don't understand this inconsistency

**Comment by jjallaire** [comment]
Shiny Server and RStudio each have their own embedded copy of pandoc (which
they use by default unless there is a system pandoc on the PATH of a later
version).

**Comment by daattali** [comment]
Ah that makes sense! For curiousity, where is pandoc that comes with shiny server (ubuntu)? I found `/usr/lib/rstudio-server/bin/pandoc/pandoc` but didn't see shiny server's
