### ISSUE TITLE
[Feature Request]Add support for unicode characters in page title?

### ISSUE THREAD

**Issue by nicholaelaw** [rstudio/flexdashboard#128]
Currently, if a page title consists of unicode characters, page link will not work as advertised:

```
示例
=====================================
```

The actual link to page `示例` would be determined by the number of components that came before it, it seems. Eg. `#dashboard-13`. Page linking is still possible but tedious: you have build the page, get the element id in the HTML, then go back to code and set href to it.

To allow page linking in this situation, either one of the following would work:

1. Support unicode element id, so that `href = '#示例'` would just work; or
2. Allow setting custom link reference to a page. Eg.

```
示例 {data-id='examples'}
=====================================
```

would be linked to `/#example`.

**Comment by jjallaire** [comment]
You should already be able to do this with pandoc id attributes, e.g.

```
示例 {#examples}
=====================================
```

See http://pandoc.org/MANUAL.html#header-identifiers

**Comment by nicholaelaw** [comment]
Ha! Forgot about that! I'm happy.
