### ISSUE TITLE
How to compile a flexdashboard html file from R console?

### ISSUE THREAD

**Issue by ThoDuyNguyen** [rstudio/flexdashboard#13]
Is it possible to do it?

I tried: 

```
knit("index.Rmd", output = "index.html")
```

But the output file is not what I expected.

Thank you in advance

Edit: 
I figured out that this line is what I needed: 

```.
library(rmarkdown)
render("index.Rmd")
```

**Comment by jjallaire** [comment]
Yes, just call rmarkdown::render like this:

rmarkdown::render("mydashboard.Rmd")
