### ISSUE TITLE
flexdashboard and recharts

### ISSUE THREAD

**Issue by willingpo** [rstudio/flexdashboard#135]
Can flexdashboard  use recharts ?When I Knit a flexdashboard's html which include recharts,the html always  refresh.

**Comment by timelyportfolio** [comment]
Can you provide an example?

**Comment by willingpo** [comment]
My Code is like this:
---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(recharts)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
echartr(iris, Sepal.Length, Sepal.Width, series = Species)
```

**Comment by gadenbuie** [comment]
I haven't tried it with flexdashboard, but I'd encourage anyone with a similar question to try using [echarts4r](http://echarts4r.john-coene.com/).
