### ISSUE TITLE
flexdashboards on shinyapps.io

### ISSUE THREAD

**Issue by jkr216** [rstudio/flexdashboard#136]
flexdashboard isn't displaying correctly on shinyapps.io. It's being smushed into a very small frame.

**Comment by jjallaire** [comment]
Does the dashboard have `runtime: shiny` or `runtime: shiny_prerendered` (those are the only types of flexdashboards that can be deployed to shinyapps.io). 

I don't have any problem deploying various dashboards to shinyapps.io so you may need to be more specific here (i.e. provide the source code for a dashboard which exhibits this behavior). You may also want to submit a support ticket to shinyapps.io

**Comment by jkr216** [comment]
Cc Andy here as I think he has seen this issue as well. It only occurs with custom domains. I will send the code shortly.

**Comment by jjallaire** [comment]
Okay, I don't think there is anything to do in flexdashboard if it's related to custom domains. Please feel free to re-open if you establish that a change is required in the package in order to deploy correctly with shinyapps.io custom domains.

**Comment by kippandrew** [comment]
I suggested opening a ticket here, as something about the CSS layout of the flexdashboard means that when running on shinyapps.io with a custom domain, the iframe is unable to reliability detect the frame height, resulting in a tiny frame:

http://worldmap.reproduciblefinance.com/

We do see this occasionally on other apps with custom CSS, but other then that I'm not 100% where sure the problem lies.

**Comment by jkr216** [comment]
Hi JJ, do you mean the flexdashboard builder would hard code the height? Or the shinyapps team?

**Comment by jjallaire** [comment]
@kippandrew Could you suggest a change here? It seems like whatever is going on is idiosyncratic to shinyapps.io custom domains (as it apparently works fine on standard domains, at least in all the of the example dashboard I've tried. I'm happy to make whatever change is required but I'm not in a good position to debug this scenario.
