### ISSUE TITLE
Is it possible to create a 2x2 dashboard with tabs on each pane

### ISSUE THREAD

**Issue by statquant** [rstudio/flexdashboard#137]
Hello I am looking for a way to create a 2x2 dashboard with each pane having 2 tabs. For some reason I cannot manage, from the docs it is not explicitely discouraged but the examples are only showing tabs on a whole column/row pane.

Is it possible ?

Also I apologize as this might not be the place to get basic questions answered. Stackoverflow does not appear to have good answer rate either. What is the best place to ask questions and discuss flexdashboards ?

**Comment by jjallaire** [comment]
You are correct that this isn't possible (it's by far the most annoying limitation of flexdashboard). This is indeed the best place to ask about flexdashboard.

**Comment by statquant** [comment]
Thank you for your prompt reply JJ.
Can I ask you one last question, I am a newby in shiny or flexdashboard
(though not too much  in R itself).
I like flex dashboard as it looked simple (yaml+rmd and I am good to go)
but is the requested feature available in shiny?
I plan in doing simple dashboards, loading data and displaying through
plotly, with a last page with editor + console so user can modify the data
in place.
Should I go the shiny route?

**Comment by jjallaire** [comment]
If you want maximum flexibility with layout you should go with straight
shiny. There will be a steeper learning curve and the layouts you can do
with flexdashboard will require more code, but you won't ultimately run
into any UI limitations you can't surmount. Check out the shinydashboard
package if you haven't already.

**Comment by SemiQuant** [comment]
Here's a possible solution. [Link to code.](https://gist.github.com/SemiQuant/9f010b330122f79861bbb63ad2ea3d30)

<img width="1179" alt="Screenshot 2019-05-10 at 10 40 33" src="https://user-images.githubusercontent.com/8179171/57514312-7b7d7000-7310-11e9-8dff-60a67e61da9f.png">
