### ISSUE TITLE
Linkable valueBox "remembers" previous links

### ISSUE THREAD

**Issue by jarodmeng** [rstudio/flexdashboard#139]
I use `valueBox` to dynamically create links based on user input. When the dashboard first launches, everything works as expected. Clicking on the value box opens the link. However, when I change the input and click on the value box again, it opens two tabs, one for the old link and one for the new link. If I change the input again, clicking the value box would open three tabs. It appears that somehow the value box "remembers" all previous links and open all of them when clicked.

Here is a minimum example. I comment out the code so that GitHub doesn't try to render the markdown.

```
# ---
# title: "Test Linkable valueBox"
# output: 
#   flexdashboard::flex_dashboard:
#     orientation: rows
# runtime: shiny
# ---
# 
# ```{r setup, include=FALSE}
# library(flexdashboard)
# ```
# 
# Sidebar {.sidebar}
# =======================================================================
# 
# ```{r}
# textInput("website", "Website", "http://google.com")
# ```
# 
# Dashboard
# =======================================================================
# 
# Row
# -----------------------------------------------------------------------
# 
# ### valueBox {.value-box}
# 
# ```{r}
# renderValueBox({
#   valueBox(value = input$website, href = input$website)
# })
# ```
```

**Comment by jjallaire** [comment]
Thanks for the report, should now be fixed on master
