### ISSUE TITLE
Controlling visibility of navbar menu items 

### ISSUE THREAD

**Issue by maarten-vermeyen** [rstudio/flexdashboard#142]
I'm using Shinyproxy to provide authenthication to some Shiny applications that use flexdashboards. While it is easy to implement basic authorisation in R code blocks to limit access to certain functionality and also hide most of the corresponding UI, I'm having some difficulties with hiding page links in the navbar. 

Just to be clear, I'm not trying to hide the menu item as a way to secure the application, the functionalities to create or retrieve data and generate output are secured server side.  

Using the {.hidden} mechanism makes the link invisible to all users. Since it isn't possible (I could be wrong here) to render the navbar from a reactive context with flexdashboard, the easiest way to hide this would be through manipulating the class attribute through a javascript event listener. This listener can be added based on the users permissions. 

However It is cumbersome to target specific items from the menu item with javascript as they don't have id's. In order to hide a list item, you would have to use a selector that takes into account that it is a grandchild of the navbar element which has a child with a specific href attribute.  It would be easier if the list item elements had an assigned ID, maybe something like `<li id="navbar-item-section-title>`. 

It could be I've missed something obvious here, in which case you have my sincere apologies and my gratitude for pointing me in the right direction.

**Comment by cpsievert** [comment]
See here for a way to solve this issue https://github.com/rstudio/flexdashboard/issues/229#issuecomment-780102766
