### ISSUE TITLE
rmardown::render() produces blank page when run from Linux terminal

### ISSUE THREAD

**Issue by sillasgonzaga** [rstudio/flexdashboard#145]
I'm trying to render a flexdashboard document from the Linux terminal, but it produces a somewhat blank page:

![flex_errado](https://user-images.githubusercontent.com/11240259/31085330-30fa37a4-a76d-11e7-8d2b-4eec31644b68.png)

However, if I run the render() script from Rstudio Server, it works as it should:

![flex_certo](https://user-images.githubusercontent.com/11240259/31085398-61944526-a76d-11e7-8ded-4788b988e417.png)

I'm using the same code from one the examples provided on the flexdashboard website:

https://beta.rstudioconnect.com/jjallaire/htmlwidgets-d3heatmap/htmlwidgets-d3heatmap.html

The code from terminal outputs this:
```
/usr/bin/pandoc +RTS -K512m -RTS flex_ex.utf8.md --to html --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output /srv/shiny-server/relatorios/flex_ex.html --smart --email-obfuscation none --self-contained --standalone --section-divs --template /home/casaevideo/R/x86_64-redhat-linux-gnu-library/3.3/flexdashboard/rmarkdown/templates/flex_dashboard/resources/default.html --include-in-header /tmp/RtmpFjnBNv/rmarkdown-strc71525d636f6.html --variable 'theme:cosmo' --include-in-header /tmp/RtmpFjnBNv/rmarkdown-strc7156801811c.html --mathjax --variable 'mathjax-url:https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' --include-in-header /tmp/RtmpFjnBNv/filec7157a278f8ahtml --include-after-body /tmp/RtmpFjnBNv/filec715251ac36f.html --highlight-style pygments --include-before-body /tmp/RtmpFjnBNv/filec7154b7738f2.html --include-after-body /tmp/RtmpFjnBNv/filec7157089ceb1.html

Output created: /srv/shiny-server/relatorios/flex_ex.html
```
And the code from Rstudio this output:
`
/usr/lib/rstudio-server/bin/pandoc/pandoc +RTS -K512m -RTS flex_ex.utf8.md --to html --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output /srv/shiny-server/relatorios/flex_ex.html --smart --email-obfuscation none --self-contained --standalone --section-divs --template /usr/lib64/R/library/flexdashboard/rmarkdown/templates/flex_dashboard/resources/default.html --include-in-header /tmp/Rtmpi6MsMy/rmarkdown-str825668d5448c.html --variable 'theme:cosmo' --include-in-header /tmp/Rtmpi6MsMy/rmarkdown-str825660713cd8.html --mathjax --variable 'mathjax-url:https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' --include-in-header /tmp/Rtmpi6MsMy/file8256742d1ed1html --include-after-body /tmp/Rtmpi6MsMy/file82562d2ff616.html --highlight-style pygments --include-before-body /tmp/Rtmpi6MsMy/file825674846ccb.html --include-after-body /tmp/Rtmpi6MsMy/file82564a252d0e.html `

Also, I've posted the html source code of both files in this gist:

https://gist.github.com/sillasgonzaga/e4283c88ccb3d7146b9ac0afa0595488

```

sessionInfo()
R version 3.3.3 (2017-03-06)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] d3heatmap_0.6.1.1 knitr_1.15.1      shiny_1.0.4       flexdashboard_0.5 rmarkdown_1.5    

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.12       magrittr_1.5       munsell_0.4.3      colorspace_1.3-2  
 [5] xtable_1.8-2       R6_2.2.2           highr_0.6          plyr_1.8.4        
 [9] stringr_1.2.0      tools_3.3.3        png_0.1-7          htmltools_0.3.6   
[13] yaml_2.1.14        rprojroot_1.2      digest_0.6.12      RColorBrewer_1.1-2
[17] base64enc_0.1-3    htmlwidgets_0.9    evaluate_0.10      mime_0.5          
[21] stringi_1.1.5      scales_0.4.1.9002  backports_1.1.0    jsonlite_1.5      
[25] httpuv_1.3.5       Cairo_1.5-9    
```

**Comment by benfasoli** [comment]
I was just having the same issue and found a resolution as I was adding comments here. 

## Problem

The system version of pandoc (in your case, `/usr/bin/pandoc`) is out of date (or possibly too new) compared the version that ships with RStudio (in your case, `/usr/lib/rstudio-server/bin/pandoc/pandoc`). You can confirm for your configuration with

```
/usr/bin/pandoc --version  # for me, 1.12.3.1
/usr/lib/rstudio-server/bin/pandoc/pandoc --version  # for me, 1.17.2
```

## Fix

For the command line R to use the same version of pandoc, you can specify the `RSTUDIO_PANDOC` environment variable before calling `render()`. This specifies the path to the specific pandoc binary to use.

```r
# Define before render()
Sys.setenv('RSTUDIO_PANDOC' = '/usr/lib/rstudio-server/bin/pandoc')
# Then render via R code normally
render(file, output_format = flex_dashboard())
```

## Solution

Not sure if pandoc 2 is backwards compatible for use with `flexdashboard` but `flex_dashboard()` could easily check the version of pandoc that it's calling to ensure it's a recent enough version.
