### ISSUE TITLE
Deploy issue on shinyapp.io, multiple charts and tabs

### ISSUE THREAD

**Issue by jbozz16** [rstudio/flexdashboard#147]
Hi guys

I have some problems when I have to deploy my .rmd file on shinyapp.io. 

The first problem, I do not have the "shinyapp.io" option in the destination account Menu (picture below)
![r_issue_1](https://user-images.githubusercontent.com/20000403/31705203-b76f6060-b3e4-11e7-9dff-47a7043a1ba1.PNG)

but I solved the issue using the function 
“rsconnect:::deployDoc("//path/of/myfile/my_app.Rmd")”

The second problem, when I used the library "Flexdashboard" in a .rmd  and I coded just a tab and a chart the deploy on shinyapp.io perfectly works (picture below)

![output_index2](https://user-images.githubusercontent.com/20000403/31705733-d7cd3a38-b3e6-11e7-8a4c-02f419f7c113.PNG)

In another .rmd file I always used the "Flexdashboard" library and I coded more charts and tabs. When I tried to deploy my app in shinyapp.io the server got disconeccted (picture below).

![output_index3](https://user-images.githubusercontent.com/20000403/31706687-107a9fda-b3ea-11e7-9d7c-80651a5c58dc.PNG)

I both tried the following lines of code

title: "Myapp"
output: 
  flexdashboard::flex_dashboard:
    storyboard: true
    orientation: columns
    runtime: shiny_prerendered

and 

title: "Myapp"
output: 
  flexdashboard::flex_dashboard:
    storyboard: true
    orientation: columns
    runtime: shiny

but the result it did not change, in both cases the server got disconnected .

Do you have any solution for the problem?

Regards

Jacopo

**Comment by jbozz16** [comment]
Here the source code

---
title: "Test"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    runtime: shiny
---

```{r delete enviroment, echo=FALSE}
rm(list=ls(all=TRUE))
```

```{r setup, include=FALSE}
library(flexdashboard)
library(MASS)
library(shiny)
library(plotly)
library(markdown)
library(RJDBC)
library(rsconnect)
```


```{r}
drv <- JDBC("###################################",identifier.quote="`")

conn <- dbConnect(drv,"#########################################;
                  database=#################;
                  user=#####################;
                  password=#################;
                  encrypt=true;
                  trustServerCertificate=false;
                  hostNameInCertificate=*.database.windows.net;
                  loginTimeout=30;")

res <- dbGetQuery(conn, ' select * from InputR_Linea14_b')

```


Tab 1
=======================================================================

### Chart A

```{r}


    print(res)



```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

 print(res)

```

Tab 2
=======================================================================

### Chart A

```{r}

    print(res)




```

**Comment by haroldgil** [comment]
I've been having the same issue! ("shinyapps.io" option in the destination account Menu wouldn't show) 

I figured it out in my case. The problem seems to be with the YAML header, specifically with the single colon at the end of "flexdashboard::flex_dashboard:". I took out the single colon **_and_ also removed the spaces preceding the options that followed it**. Finally,  I had to place **"flexdashboard::flex_dashboard" on the same line as "output:"**.

Now the "shinyapps.io" option is back and I am able to publish to shinyapps.io!

**Original non-working version:**

![worksnot](https://user-images.githubusercontent.com/6191338/33032833-68d16130-cdf0-11e7-889f-575d8db624ff.PNG)

**Version that works:**

![works](https://user-images.githubusercontent.com/6191338/33032782-4861fbbc-cdf0-11e7-9245-886abc4c80d9.PNG)

**Comment by bborgesr** [comment]
@haroldgil, the correct format is:

```yaml
---
title: "Basic Shiny Flexdashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
    source_code: embed
runtime: shiny
---
```

**Comment by haroldgil** [comment]
Thanks @bborgesr 

You're right,  the only problem with my **Original non-working version** was that "runtime: shiny" needed to be left aligned with no spaces preceding it. The below works for me.

![good](https://user-images.githubusercontent.com/6191338/33133131-cb86a22a-cf69-11e7-970c-24a0a22a5410.PNG)
