### ISSUE TITLE
renderValueBox doesn't show values

### ISSUE THREAD

**Issue by ADraginda** [rstudio/flexdashboard#148]
If you wrap `valueBox` within `renderValueBox` then the valueBox won't show values correctly.

Run this snippet once....and you'll see the value box show up correctly. Then "Run Document" (within RStudio) a 2nd time and you won't see the values anymore (looks like it only shows the values right after the Rmd compiles)

NOTE: Make sure to replace the `'''` I put in with three backticks (since i'm trying to show md code within a md)

```
---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    runtime: shiny
---

'''{r setup, include=FALSE}
library(flexdashboard)
'''

'''{r}
renderValueBox(valueBox(value = 10,
                        icon = "fa-dollar",
                        color = "primary"))

'''
```

The fix is: Don't put your valueBoxes within `renderValueBox`....but I wanted to report this anyway in case it's truly a bug.

**Comment by AzrakDakin** [comment]
Hello,
I have encountered this problem and have still not found a solution.
I have several ValueBoxes, which works on the first Run, but not on the second or third.
If a change is made, and it is restarted, it works, then the problem returns again.
Do you have a lead?
thank you

**Comment by kianweelee** [comment]
Hi @AzrakDakin , did you manage to resolve this issue? I am currently encountering the same issue and looking for an alternative for this.

**Comment by AzrakDakin** [comment]
Hi @kianweelee , yes, I have found the solution of the problem

`flexdashboard::valueBox(value = paste(var,"%"), 
      caption="Level",
      if (var< 25)
      {icon="glyphicon-thumbs-down"
      }
      else if (var> 85)
      {icon="glyphicon-thumbs-up"
      }
      else {icon="glyphicon-hand-right"
      },
      if (var< 25)
      {color = 'red'
      }
      else if (var> 85)
      {color = 'green'
      }
      else {color = 'orange'
      })
`

if i can help you tell me

**Comment by kianweelee** [comment]
Well, I am trying to make my values in the valuebox change based on the input on the csv file. For testing purpose, my csv file has a header call "Number" and a row containing a number 10. My program contains a progressbar and the valuebox. Code is as below:
```

```{r}
fileData <- reactiveFileReader(1000, NULL, 'flexdeshboard_reactivity_test.csv', read.csv)


########################################################################################################################### UI

progressBar(
      id = "pb2",
      value = 0,
      total = 100,
      title = "",
      display_pct = TRUE
    )


####################################################################################################################### Server
# Anything that calls autoInvalidate will automatically invalidate
# every 2 seconds.
autoInvalidate <- reactiveTimer(2000)

observe({
  # Invalidate and re-execute this reactive expression every time the
  # timer fires.
  autoInvalidate()
  
  # update progress bar function, value return to the csv file
  updateProgressBar(
    session = session,
    id = "pb2",
    value = fileData()$Number, total = 100
  )
})
```

###

```{r}
library(shinydashboard)

ui <- dashboardPage(
  dashboardHeader(disable = TRUE),
  dashboardSidebar(disable = TRUE),
  dashboardBody(
    fluidRow(
      # Dynamic valueBoxes
      valueBoxOutput("progressBox")
    )
  )
 )

server <- function(input, output) {
  
   output$progressBox <- renderValueBox({
    valueBox(
      fileData()$Number, "Progress", icon = icon("list"),
      color = "purple"
    )
  })
}

shinyApp(ui, server)
```
```

Like the issue similar to yours, I can run and render it smoothly for the first time. However, if I were to run it the second time, I can't render it and encounter a "No file" message.

**Comment by AzrakDakin** [comment]
ok, however, i work on flexdashboard and not shinydashboard, which i find less practical

**Comment by kianweelee** [comment]
Hi, thats great to hear! I am actually using flexdashboard! The reason why I imported the shinydashboard is because I can't seem to make renderValueBox() work without it.

**Comment by AzrakDakin** [comment]
ok, to generate my Flexdashboard, I take new file> Rmarkdown> From template> Flexdashboard.

Then here is the list my useful packages (adapted to my needs)

library(dplyr)
library(ggplot2)
library(tidyr)
library(readxl)
library(knitr)
library(rmarkdown)
library(tidyverse)
library(shiny)
library(htmlwidgets)
library(digest)
library(bit)
library(plotly)
library(flexdashboard)

**Comment by AzrakDakin** [comment]
and if you want in the future, offer the flex to another person, you can add:

list_packages <-
  c('xlsx','dplyr','haven')

for (package in list_packages) {
  if (!require(package, character.only = T, quietly = T)) {
    install.packages(package)
    library(package, character.only = T)
  }
}

**Comment by kianweelee** [comment]
Thanks for the advice! Have you tried uploading your flexdashboard on a server? The reason why I chose flexdashboard is because I am not limited to the 12-wide grid system offer by shiny. However, I will also need to upload the completed dashboard on a server so they can use it during daily meetings.

**Comment by AzrakDakin** [comment]
my dashboards are deployed in an internal network, with an Rstudio image hosted under Gitlab "private" to the network. Thus, access is only possible if one is part of this internal network.

**Comment by kianweelee** [comment]
This is my testing code. I have uploaded the excel file since I can't upload csv here.

```
---
title: "Test"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
    runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(tidyverse)
library(dplyr)
library(shinyWidgets)
```

QC Rejection 
===============================================================================

Column
-----------------------------------------------------------------------

```{r}
fileData <- reactiveFileReader(1000, NULL, 'flexdeshboard_reactivity_test.csv', read.csv)


########################################################################################################################### UI
fluidPage()

progressBar(
      id = "pb2",
      value = 0,
      total = 100,
      title = "",
      display_pct = TRUE
    )


####################################################################################################################### Server
# Anything that calls autoInvalidate will automatically invalidate
# every 2 seconds.
autoInvalidate <- reactiveTimer(2000)

observe({
  # Invalidate and re-execute this reactive expression every time the
  # timer fires.
  autoInvalidate()
  
  # update progress bar function, value return to the csv file
  updateProgressBar(
    session = session,
    id = "pb2",
    value = fileData()$Number, total = 100
  )
})
```

###

```{r}
library(shinydashboard)

ui <- dashboardPage(
  dashboardHeader(disable = TRUE),
  dashboardSidebar(disable = TRUE),
  dashboardBody(
    fluidRow(
      # Dynamic valueBoxes
      valueBoxOutput("progressBox")
    )
  )
 )

server <- function(input, output) {
  
   output$progressBox <- renderValueBox({
    valueBox(
      fileData()$Number, "Progress", icon = icon("list"),
      color = "purple"
    )
  })
}

shinyApp(ui, server)
```
```
[flexdeshboard_reactivity_test.xlsx](https://github.com/rstudio/flexdashboard/files/5140741/flexdeshboard_reactivity_test.xlsx)

**Comment by AzrakDakin** [comment]
I would need the file also

**Comment by kianweelee** [comment]
Which file will you need?

**Comment by AzrakDakin** [comment]
no, its ok, i test

**Comment by kianweelee** [comment]
I have added them here: https://github.com/kianweelee/flexdashboard_test

**Comment by AzrakDakin** [comment]
have you a  fonction "fileData"?

**Comment by kianweelee** [comment]
Filedata is actually a reactive function as stated in ``fileData <- reactiveFileReader(1000, NULL, 'flexdeshboard_reactivity_test.csv', read.csv)``.

**Comment by AzrakDakin** [comment]
its ok

**Comment by AzrakDakin** [comment]
everything works, but we refresh, it's at 0, is it?

**Comment by kianweelee** [comment]
Yes everything works but when i close the dashboard and run it again, the valuebox becomes missing. You can try to access the csv file and change the value to see if the value changes

**Comment by AzrakDakin** [comment]
I'm sincerely sorry, but after trying I can't find it. I had also tried shinydashboard, but lacking success, the full flex had met my needs.

In the flex the only difference was before:

valueBox(value = ...  and after flexdashboard::valueBox(value =...

this was enough to make the valueBox reactive constantly

so sorry Kian

**Comment by kianweelee** [comment]
No worries! I will continue to work on it and update you if I have a solution! Thanks for the help!

**Comment by AzrakDakin** [comment]
great thx,

**Comment by cpsievert** [comment]
The yaml matter in the original comment is wrong -- the `runtime: shiny` needs to be a top-level setting (i.e., it's not an argument to `flex_dashboard`)

````
---
title: "Untitled"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
---

### A value

```{r setup, include=FALSE}
library(flexdashboard)
```

```{r}
renderValueBox(valueBox(value = 10,
                        icon = "fa-dollar",
                        color = "primary"))

```
````

This works how I'd expect it to -- please file a new issue if there's something else here that I'm missing
