### ISSUE TITLE
Error input not found 

### ISSUE THREAD

**Issue by joscani** [rstudio/flexdashboard#151]
Suddenly my flexdashboard does not work. I think something happens because this examples does not work. Any idea?
http://rmarkdown.rstudio.com/flexdashboard/shiny.html#simple_example

**Comment by jjallaire** [comment]
This is likely due to the pandoc v2.0 / R markdown v1.7 issue. @bborgesr Could you confirm?

We should prepare a flexdashboard release to CRAN I think.

**Comment by jcheng5** [comment]
I think it might be this: https://github.com/rstudio/rmarkdown/issues/1201

@joscani can you try `install_github("rstudio/rmarkdown")` and see if that fixes it?

**Comment by joscani** [comment]
Thank you @jcheng5 , now its work perfectly. I needed because thursday I present my viz in the IX useRs conference of Spain R users in Granada. http://r-es.org/9jornadasR/

**Comment by jcheng5** [comment]
Ok, great. Good luck with your presentation!
