### ISSUE TITLE
Flexdashboard and Plotly interaction causes issues with scrollbar on legend of Plotly graphs

### ISSUE THREAD

**Issue by maulcait** [rstudio/flexdashboard#154]
Someone else asked this question on stackoverflow, but I am having the same problem. https://stackoverflow.com/questions/46495164/flexdashboard-plotly-interaction-results-in-odd-scroll-bar-behavior

Basically when I have multiple plotly plots within a flexdashboard, the first plot doesn't have a scroll bar, but any subsequent plots are getting a scrollbar that I cannot remove. 

According to the response to the stackoverflow question "flexdashboard is the culprit in this case because of how it is dynamically fitting the available space and informing plotly.js on how to render. It is worth noting this appears as SVG in the source html."

**Comment by cpsievert** [comment]
Seems like you probably want to pass the size of container to the `ggplotly()` call, similar to this https://github.com/ropensci/plotly/blob/master/inst/examples/shiny/ggplotly_sizing/app.R
