### ISSUE TITLE
All apps with htmlwidgets failing to render on Mac after #150

### ISSUE THREAD

**Issue by bborgesr** [rstudio/flexdashboard#155]
I think that #150 unfortunately introduced one bug, that I can't quite figure out why. I've found that this fix works fine for apps with no htmlwidgets, but it fails to render in all other circumstances (DT, ggplotly, d3heatmap, ...). (Going back just one commit to 73a7fe1dd6644b6f63e311fbcf41bc361266a1fe fixes the issue; of course, then you get the terrible #149 Pandoc bug).

Here's a repro (the first example in the [website](http://rmarkdown.rstudio.com/flexdashboard/examples.html)):

````r
---
title: "NBA Scoring (2008)"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
    source_code: embed
---

```{r setup, include=FALSE}
library(knitr)
library(d3heatmap)
library(flexdashboard)

url <- "http://datasets.flowingdata.com/ppg2008.csv"
nba_players <- read.csv(url, row.names = 1)
```

### Stats by Player {data-width=650}

```{r}
d3heatmap(nba_players, scale = "column")
```

### Top Scorers {data-width=350}

```{r}
knitr::kable(nba_players[1:20,c("G", "MIN", "PTS")])
```
````

Here's what it should look like:
![screen shot 2017-11-16 at 11 30 42 pm](https://user-images.githubusercontent.com/6527540/32921649-4872d1ac-cb26-11e7-9187-3a5321dd743a.png)

Here's what it looks like at commit 73a7fe1dd6644b6f63e311fbcf41bc361266a1fe (ugly, because of #149 ):
![screen shot 2017-11-16 at 11 31 00 pm](https://user-images.githubusercontent.com/6527540/32921773-c241229a-cb26-11e7-9c44-b97b3305b69b.png)

If we go one commit forward to Yihui's fix (to c90540f7acd686ea67fc7ba3f5f36cfb870da8c5), the rendering fails with get the following output:
```
processing file: NBA-scoring-with-d3heatmap.Rmd
  |.........                                                        |  14%
  ordinary text without R code

  |...................                                              |  29%
label: setup (with options) 
List of 1
 $ include: logi FALSE

  |............................                                     |  43%
  ordinary text without R code

  |.....................................                            |  57%
label: unnamed-chunk-1

Quitting from lines 22-23 (NBA-scoring-with-d3heatmap.Rmd) 
Error in switch(options$dev, pdf = ".pdf", jpeg = ".jpeg", ".png") : 
  EXPR must be a length 1 vector
Calls: <Anonymous> ... fun -> withVisible -> knit_print -> html_screenshot
Execution halted
```
I've tried other apps, and the only common denominator in the problematic chunks is that it is creating an htmlwidget.

<details>
  <summary><code>devtools::session_info().R</code><span> (I got a bunch of packages from Github rather than CRAN as a hail mary, but I coulnd't find any combination that worked once we get to c90540f7acd686ea67fc7ba3f5f36cfb870da8c5) </span></summary>

```r
> devtools::session_info()
Session info ---------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.2 (2017-09-28)
 system   x86_64, darwin15.6.0        
 ui       RStudio (1.1.383)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       Europe/Lisbon               
 date     2017-11-16                  

Packages -------------------------------------------------------------------------------------------------------
 package       * version date       source                               
 backports       1.1.0   2017-05-22 CRAN (R 3.4.0)                       
 base          * 3.4.2   2017-10-04 local                                
 compiler        3.4.2   2017-10-04 local                                
 datasets      * 3.4.2   2017-10-04 local                                
 devtools        1.13.2  2017-06-02 CRAN (R 3.4.0)                       
 digest          0.6.12  2017-01-27 CRAN (R 3.4.0)                       
 DT              0.2     2016-08-09 CRAN (R 3.4.0)                       
 evaluate        0.10.1  2017-06-24 CRAN (R 3.4.1)                       
 flexdashboard * 0.5     2017-11-16 local                                
 graphics      * 3.4.2   2017-10-04 local                                
 grDevices     * 3.4.2   2017-10-04 local                                
 htmltools       0.3.6   2017-11-16 Github (rstudio/htmltools@02678ee)   
 htmlwidgets     0.9     2017-11-16 Github (ramnathv/htmlwidgets@c042cca)
 jsonlite        1.5     2017-06-01 CRAN (R 3.4.0)                       
 knitr           1.17.10 2017-11-16 Github (yihui/knitr@abd8319)         
 magrittr        1.5     2014-11-22 CRAN (R 3.4.0)                       
 memoise         1.1.0   2017-04-21 CRAN (R 3.4.0)                       
 methods       * 3.4.2   2017-10-04 local                                
 Rcpp            0.12.13 2017-09-28 cran (@0.12.13)                      
 rmarkdown       1.7.3   2017-11-16 Github (yihui/rmarkdown@63a37ae)     
 rprojroot       1.2     2017-01-16 CRAN (R 3.4.0)                       
 rsconnect       0.8.5   2017-08-23 CRAN (R 3.4.1)                       
 stats         * 3.4.2   2017-10-04 local                                
 stringi         1.1.5   2017-04-07 cran (@1.1.5)                        
 stringr         1.2.0   2017-02-18 CRAN (R 3.4.0)                       
 tools           3.4.2   2017-10-04 local                                
 utils         * 3.4.2   2017-10-04 local                                
 withr           2.1.0   2017-11-01 CRAN (R 3.4.2)                       
 yaml            2.1.14  2016-11-12 CRAN (R 3.4.0)    
```
</details>
<br>

@yihui, do you have any idea what may be causing this?

cc @jcheng5

**Comment by bborgesr** [comment]
Interestingly, the same app works fine in http://colorado.rstudio.com/'s RSP. I'll do some more investigation.

**Comment by bborgesr** [comment]
I take back what I said, I get the same problem on my Mac even when I revert to Pandoc 1.9

**Comment by yihui** [comment]
This is a knitr issue, and I just fixed it: https://github.com/yihui/knitr/commit/f37911941a9fe57bce44ae5d1bb0c661eaa05fc8

I'll release a new version of knitr to CRAN over the weekend.

**Comment by bborgesr** [comment]
Thanks @yihui, it works great!

**Comment by Kattuvan** [comment]
I get the same error as one above My session information is below. This Error  started appearing when I switched to R 3.4.3. Then I switched back to 3.4.2. But I get more errors as the packages were developed using R3.4.3.  Please help me. Thanks.
> devtools::session_info()
Session info -------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.3 (2017-11-30)
 system   x86_64, mingw32             
 ui       RStudio (1.1.383)           
 language (EN)                        
 collate  English_Canada.1252         
 tz       America/New_York            
 date     2017-12-09                  

Packages -----------------------------------------------------------------------------
 package       * version    date       source                          
 backports       1.0.5      2017-01-18 CRAN (R 3.3.2)                  
 base          * 3.4.3      2017-12-06 local                           
 compiler        3.4.3      2017-12-06 local                           
 datasets      * 3.4.3      2017-12-06 local                           
 devtools        1.13.4     2017-11-09 CRAN (R 3.4.3)                  
 digest          0.6.12     2017-01-27 CRAN (R 3.3.3)                  
 evaluate        0.10.1     2017-06-24 CRAN (R 3.4.3)                  
 flexdashboard   0.5.1      2017-11-30 CRAN (R 3.4.3)                  
 graphics      * 3.4.3      2017-12-06 local                           
 grDevices     * 3.4.3      2017-12-06 local                           
 htmltools       0.3.6      2017-04-28 CRAN (R 3.4.0)                  
 jsonlite        1.5        2017-06-01 CRAN (R 3.4.3)                  
 knitr           1.17       2017-08-10 CRAN (R 3.4.3)                  
 magrittr        1.5        2014-11-22 CRAN (R 3.3.1)                  
 memoise         1.0.0      2016-01-29 CRAN (R 3.3.1)                  
 methods       * 3.4.3      2017-12-06 local                           
 Rcpp            0.12.14    2017-11-23 CRAN (R 3.4.3)                  
 rmarkdown       1.6        2017-06-15 CRAN (R 3.4.1)                  
 rprojroot       1.2        2017-01-16 CRAN (R 3.3.2)                  
 stats         * 3.4.3      2017-12-06 local                           
 stringi         1.1.6      2017-11-17 CRAN (R 3.4.2)                  
 stringr         1.2.0      2017-02-18 CRAN (R 3.3.3)                  
 tools           3.4.3      2017-12-06 local                           
 utils         * 3.4.3      2017-12-06 local                           
 withr           2.1.0.9000 2017-12-10 Github (jimhester/withr@fe81c00)
 yaml            2.1.15     2017-12-01 CRAN (R 3.4.3)  

Error in switch(options$dev, pdf = ".pdf", jpeg = ".jpeg", ".png") : 
  EXPR must be a length 1 vector
Calls: <Anonymous> ... fun -> withVisible -> knit_print -> html_screenshot
Execution halted

**Comment by yihui** [comment]
@Kattuvan Unfortunately, the new version of **knitr** was stuck in the CRAN submission process for unknown reasons (I submitted it a couple of weeks ago but haven't heard back yet). You can install the development version of **knitr** via

```r
devtools::install_github('yihui/knitr')
```
