### ISSUE TITLE
flexdashboard shiny tag$iframe auto-forwards link to iframe website 

### ISSUE THREAD

**Issue by benjaminrobinson** [rstudio/flexdashboard#157]
Hi, all!  Not sure this is a post for shiny but since I'm using a flexdashboard with shiny in the runtime I'm posting it here.  I'm embedding an iframe into a flexdashboard and getting a strange result.  When I click the "Open in Browser" link after clicking "Run Document" inside of RStudio, my flexdashboard opens up on a local port in my web browser of choice (Chrome) and then after momentarily showing my flexdashboard, autoforwards me to the website that I'm trying to embed using the iframe.  Any takers on why this is happening?  Here's my code and a link to a GitHub gist of what I'm trying to do:

https://gist.githubusercontent.com/benjaminrobinson/dbaf4baebd2540744eaf90e6501c85a2/raw/b3476be85d8652f144c2883057b058f8f0e3a371/gistfile1.txt

---
title: ""
output:
  flexdashboard::flex_dashboard:
    orientation: rows
runtime: shiny
---

Open Data Platform
=======================================================================
```{r}
tags$iframe(style="height:600px; width:100%; scrolling=yes", src="https://data.cityofchicago.org/browse?category=Administration+%26+Finance")
```

**Comment by gadenbuie** [comment]
I've seen similar behavior at times in RStudio and I'm fairly confident that it isn't something unusual with flexdashboard. In general, in these cases I'd recommend using an external browser to preview your dashboard, rather than the RStudio viewer pane.
