### ISSUE TITLE
Cards Components

### ISSUE THREAD

**Issue by Kvit** [rstudio/flexdashboard#160]
It would be very nice to have Cards components for navigation/links in flexshboard (fixed sizes, right-down scalable flow,  structured content, links styled as buttons.)

**Comment by bborgesr** [comment]
Can you elaborate or point to an example?

**Comment by Kvit** [comment]
Card navigation design is very common nowadays, here is one of many examples: https://github.com/SiDevesh/React-Native-Material-Cards. 

Flexdashboard provides a great way to build dashboard components but I could not find a way to control component size and layout options that would allow making navigation Cards.  Features that would be useful:  fixed component size, flow layout (not just column or row) , links styled as buttons.

**Comment by bborgesr** [comment]
From what you describe, maybe [shinydashboard](https://rstudio.github.io/shinydashboard/index.html) would be a better fit for you? It is based in AdminLTE ([demo website](https://adminlte.io/themes/AdminLTE/index2.html)), which differs from the fllexdashboard approach in that items in different columns often have different height, so it looks more card-like (e.g. see [this](https://rstudio.github.io/shinydashboard/structure.html#column-based-layout) or just run the app below). You can also use `valueBox`es to link to other pages (or items). See the example below in shinydashboard.

While I understand that this isn't everything that you were asking for, that is what comes out of the box. In the future, we may make some improvements to either/both flexdashboard and shinydashboard that would make card components in that type of design easier. But there's nothing in the works right now.

Demo card-like shinydashboard app:

```r
library(shiny)
library(shinydashboard)

body <- dashboardBody(
  fluidRow(
    column(width = 4,
      box("Box1 content", title = "Box1", width = NULL, status = "primary"),
      box("Box2 content", title = "Box2", width = NULL, solidHeader = TRUE, status = "primary"),
      box("Box3: a box with a solid black background", 
        tags$img(src = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Kiyomizu-dera%2C_Kyoto%2C_November_2016_-07.jpg/500px-Kiyomizu-dera%2C_Kyoto%2C_November_2016_-07.jpg",
          width = "100%"),
        width = NULL, background = "black")
    ),
    column(width = 4,
      box("Box4 content", status = "warning", width = NULL),
      box("Box5 content", numericInput("num", "Choose num", 10), title = "Box5", width = NULL, solidHeader = TRUE, status = "warning"),
      box("Box6: a box with a solid light-blue background", title = "Box6",
        width = NULL, background = "light-blue")
    ),
    column(width = 4,
      box("Box7 content", title = "Box7", width = NULL, solidHeader = TRUE),
      box("Box8: a box with a solid maroon background", title = "Box8", width = NULL, background = "maroon"),
      valueBox("About", subtitle = "Go to external link", width = NULL,
        icon = icon("external-link"), href = "https://example.com/about")
    )
  )
)

ui <- dashboardPage(
  dashboardHeader(title = "Card-like dashboard"),
  dashboardSidebar(disable = TRUE),
  body
)
server <- function(input, output, session) {}
shinyApp(ui, server)
```

**Comment by Kvit** [comment]
Thank you for comments. I tried both dashboards and found rmarkdown approach more convenient for building dashboard layouts (and I still can inject shiny components to markdown but not the other way around).  Also, Importantly for me,  shiny_prerendered runtime makes apps load much faster.  Too bad we cannot combine features from both dashboards :).  Maybe someone will come up with card HTML widget..
