### ISSUE TITLE
Wish: support for rgl widget

### ISSUE THREAD

**Issue by ugroempi** [rstudio/flexdashboard#163]
Thanks for providing a framework for dashboards! I played with the html widgets example [here](https://beta.rstudioconnect.com/jjallaire/htmlwidgets-showcase-storyboard/) and tried to replace the MetricsGraphics one with an rgl one:

`library(rgl)`
`plot3d(mtcars$mpg, mtcars$disp, mtcars$hp,` 
   `xlab="miles per gallon", ylab="displacement", zlab="horse power", type="s", col=mtcars$cyl)`
`rglwidget()`

This code works in Rmarkdown or bookdown, but does not work within the flexdashboard. I get the error message given below (German machine). It would be nice if rgl could be used in a flexdashboard.

Best, Ulrike

Here is the error message: 
"Error in validateCssUnit(sizeInfo$width) : CSS units must be a single-element numeric or character vector"
"Ruft auf: <Anonymous> ... <Anonymous> -> need_screenshot -> toHTML -> validateCssUnit"

**Comment by dmurdoch** [comment]
I've just seen the same error.  I'd be happy to modify rglwidget to work with flexdashboard, but I've no idea what modification would be needed.  Any suggestions?

**Comment by jcheng5** [comment]
@dmurdoch It looks like your widget objects' `x$width` and `x$height` are numeric vectors of length 2 (returned from `figWidth()` and `figHeight()`), instead of the expected length 1.

**Comment by dmurdoch** [comment]
Yes, that's what's causing the problem.  It's easy to work around, but I wonder if there's a deeper problem?  In the example I was looking at, `figHeight()` was just rescaling the result of `knitr::opts_current$get("fig.height")`.  That option is allowed to be a vector if you have multiple devices, but in this case the "dev" option is  `c( "png", "png")`, so something looks like a bug.

**Comment by dmurdoch** [comment]
I've now put rgl 0.99.5 on R-forge with a fix for this.

**Comment by jcheng5** [comment]
Ah, the `c("png", "png")` appears to be intentional: https://github.com/rstudio/flexdashboard/blob/dd4440a0424dc86c265af6af5a27b5bc912311be/R/flex_dashboard.R#L247-L262

Looks like it creates one PNG for desktop, and another PNG that's intended for mobile devices in portrait mode. This feature is specific to flexdashboard so it makes sense that this issue doesn't repro elsewhere.
