### ISSUE TITLE
[Feature Request] New Loading GIF

### ISSUE THREAD

**Issue by PaulC91** [rstudio/flexdashboard#174]
Pedantic request here but would it be possible to update the 'Loading...' gif that appears prior to rendering? 

It feels a bit outdated and pixelated compared to the 'Please wait...' version that appears on regular shiny apps.

Thanks

**Comment by jjallaire** [comment]
@PaulC91 I believe that indicator is provided by the rmarkdown package so you should post this issue there: https://github.com/rstudio/rmarkdown/issues
