### ISSUE TITLE
ggplot output in flexdashboard different than in Rstudio-rmd

### ISSUE THREAD

**Issue by phahn57** [rstudio/flexdashboard#176]
I made a report using flexdashboard.
The output of ggplot
`ggplot(stat,aes(as.factor(abt),faelle))+geom_col(data=stat[stat$jahr==2018,],alpha=0.3)+geom_point(data=stat[stat$jahr==2017,],color="blue")+theme_bw()+guides(colour=FALSE,alpha=FALSE,size=FALSE)+labs(x="Abteilung",y="Fälle")`

is different in html from flexdashboard and within Rstudio:
**within Rstudio:**
<img width="413" alt="bildschirmfoto 2018-03-14 um 10 19 51" src="https://user-images.githubusercontent.com/8415158/37393413-509e9c1a-2771-11e8-8134-f1be601c71c6.png">

**in flexdashboard:**
<img width="351" alt="bildschirmfoto 2018-03-14 um 10 20 52" src="https://user-images.githubusercontent.com/8415158/37393453-6d1fb32e-2771-11e8-9797-b5ec96eb388c.png">

There is no empty factor in abt.
Same issue with all plots for other factors as "verweil", "drg" etc. 

Already tried using ungroup(), now change.

Preview of the data frame reveals no empty factor in abt, and the plot within Rstudio is correct. 
The structure of the data frame (stat) ( build by several dplyr filter and grouping operations)
stat:
`structure(list(jahr = c(2017, 2017, 2017, 2017, 2017, 2017, 2017, 
2017, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018), form = c("voll", 
"voll", "voll", "voll", "voll", "voll", "voll", "voll", "voll", 
"voll", "voll", "voll", "voll", "voll", "voll", "voll"), abt = c("EXT", 
"F-CHI", "H-CHI", "K-CHI", "Kinder", "ORTH", "S-CHI", "WS", "EXT", 
"F-CHI", "H-CHI", "K-CHI", "Kinder", "ORTH", "S-CHI", "WS"), 
    drg = c(63.416, 109.117, 123.23, 41.606, 5.422, 764.558, 
    155.243, 111.312, 44.572, 150.274, 169.645, 22.136, 2.809, 
    747.866, 166.264, 105.883), faelle = c(80L, 93L, 118L, 50L, 
    4L, 364L, 121L, 160L, 58L, 128L, 149L, 25L, 6L, 381L, 118L, 
    143L), sn = c(3855L, 4767L, 3123L, 2995L, 458L, 19388L, 6645L, 
    92L, 2796L, 6665L, 3392L, 1884L, 387L, 20361L, 6517L, 0L), 
    verweil = c(139L, 316L, 362L, 117L, 10L, 2558L, 467L, 1113L, 
    104L, 535L, 523L, 61L, 8L, 2457L, 479L, 1248L)), class = c("grouped_df", 
"tbl_df", "tbl", "data.frame"), row.names = c(NA, -16L), vars = c("jahr", 
"form"), drop = TRUE, .Names = c("jahr", "form", "abt", "drg", 
"faelle", "sn", "verweil"), indices = list(0:7, 8:15), group_sizes = c(8L, 
8L), biggest_group_size = 8L, labels = structure(list(jahr = c(2017, 
2018), form = c("voll", "voll")), class = "data.frame", row.names = c(NA, 
-2L), vars = c("jahr", "form"), drop = TRUE, .Names = c("jahr", 
"form")))`

**Comment by cpsievert** [comment]
The difference here is almost certainly a difference in your data. If not that, then it might be explained by a different plotly or dplyr version (if so, please file an issue in those repos), but closing here since this isn't a flexdashboard issue
