### ISSUE TITLE
Trouble deploying a Flexdashboard to shinyapps.io

### ISSUE THREAD

**Issue by jtleekpf** [rstudio/flexdashboard#180]
I get the following error when I try to deploy a flexdashboard to shinyapps.io. It's a single Rmd file, but it does read data from a .csv. 

```
Error: Unhandled Exception: Child Task 523803995 failed: Error parsing manifest: Unknown repository for package source: rspm
In addition: Warning message:
```

**Comment by slopp** [comment]
Where are you publishing from?

**Comment by jtleekpf** [comment]
Sorted it. Turns out there was something in the dependency tree of the
janitor package that was causing the error. I removed that dependency and
it worked great thanks!
