### ISSUE TITLE
`source_code` GitHub links needs to use `target="_blank"` when used in an `iframe`, such as in Connect

### ISSUE THREAD

**Issue by jimhester** [rstudio/flexdashboard#182]
GitHub uses a [frame-ancestors Content Security Policy directive](https://githubengineering.com/githubs-csp-journey/#frame-ancestors) so it cannot be embedded inside an iframe. As a result when clicking on these links inside the connect iframe you e.g. the following error in the JS console.

> Refused to display 'https://github.com/jimhester/tidyversedashboard' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".

The workaround for this is to use the [`target="_blank"` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-target) in the anchor element to force them to be opened in a new window.

An example connect app that exhibits this behavior is https://connect.rstudioservices.com/connect/#/apps/91/access/35

**Comment by jjallaire** [comment]
I thought that Connect had a generic handler for this (as this will affect any navigation to an external site on an Rmd within Connect, and I'd think there would be tons of these). @trestletech Is there something different about this case?

**Comment by trestletech** [comment]
The only global handler that I recall for links was around removing the worker ID subpath which we share with SSP. I can't recall us altering the target of a link, though it doesn't seem unreasonable that we could either default to new tabs or do some frame-busting. Let me open a Connect issue and see if we can find a more general solution that we're happy with.

**Comment by jjallaire** [comment]
Also, isn't content displayed by default at the top level on RSC? (i.e. when is it in an iframe other than when managing it inside the publisher chrome?)

**Comment by trestletech** [comment]
(Sorry, missed the GH notification)

The default experience steers people towards viewing it in the contextualized dashboard (which involves an iframe). When you navigate to content via the content listing you see it with the chrome by default.

We discussed ways that we could look at fixing this today using a JS handler but we're struggling to figure out the right move. It came up that there are a variety of instances in which a Shiny app or RMD might be shown in an iframe, such as embedding in a blog. For every use case we could think of, it seemed like the desirable experience would be to have the R content bust out of the frame by default.

It seems pretty aggressive to have htmltools default to `target="_top"`, but we're equally unexcited about sniffing for external `<a>` links in user content to try to open them in the parent frame and/or a new tab.
