### ISSUE TITLE
Commentary Functionality After Compiling/Rendering

### ISSUE THREAD

**Issue by ShaohongBai** [rstudio/flexdashboard#187]
Hey there, 

We have been using the packages for years and absolutely it! Thank you!

We have recently looking for a way that enables recipients or readers to comment on the dashboards generated by flexdardboard. For example, sales team might need make some text comments for visualisation in the dashboard before sending to clients. Is this something you guys aware how to implement?

My team would be definitely happy to contribute regarding this. However, we are just wonder any shortcuts or existed ways you guys know?

Regards 

Shaohong

**Comment by gadenbuie** [comment]
Thanks for the comments and my apologies for the long delay in the response. We don't have anything planned or available that would give you commenting features, but you might be able to use a third-party library like [hypothesis](https://web.hypothes.is/). Please let us know if you find a solution!
