### ISSUE TITLE
SEO optimisation 

### ISSUE THREAD

**Issue by sje-c** [rstudio/flexdashboard#194]
Does anybody have any insight into google web crawlers and websites created with flexdashboard. I am finding that all that is captured is the initial loading screen. Both in HTML and screen capture. Non of the meta tags from the true page are found / indexed. It is as if the web crawler is impatient to wait a second or two for server response. Can't find much on this topic.

So how do you edit the initial loading HTML of the markdown to customise it and input your own meta tags. Hard code the initial shiny deployment.

[Cross posting here on github for highlighting of issue to developers] 
https://community.rstudio.com/t/seo-of-flexdashboard-shiny-apps/11195/4

**Comment by skofieldO5** [comment]
I have the exact same problem with including og tags for my flexdashboard www.baseball-dashboard.com

Did you find a solution for this?

**Comment by skofieldO5** [comment]
This is a bit frustrating for me. I built the whole dashboard mainly for marketing reasons. But without the ability to include og tags it doesn't make a lot of sense to put links to it on social media sites. Would really appreciate any help with this. Thanks.

**Comment by skofieldO5** [comment]
Great. Thanks. I will look into it.

**Comment by skofieldO5** [comment]
I can't really get it to work. Maybe it's  because of the rmakrdown version? It says I need 1.2 but the latest release on github is 1.11. Maybe that's it? I'm happy to share my code if someone would want to help me out.

**Comment by sje-c** [comment]
I think you should build a "normal" website as a gateway, put a blurb about
the dashboard, what it is. License a few images (cheaply through istock) to
put on it.  Especially considering you said this was for marketing reasons.
And that will *advertise* the dashboard so to speak and be easier for SEO.
Keep it simple with a bootstrap template.  And hopefully people will click
through.

**Comment by skofieldO5** [comment]
Thank you. I unfortunately have not a lot of knowledge in web dev. Would it be so easy to just put it in an iframe or something like that? Any resource you could point me to would be great.

**Comment by sje-c** [comment]
You've done well getting the dashboard online then. Worth being mindful of getting off topic in a thread.    That being said as this is kind of mitigating the issue in contrived way,...

Maybe find a tutorial and use a time saving host with GUI design like Wix / squarespace ?!  I am sure they have suitable templates.  I reckon it's easier to manage the development through a graphical interface design web service if you don't want to DIY everything.  

I design using Visual Studio 2017 (community) utilizing bootstrap templates (like Cover),   https://getbootstrap.com/docs/4.2/examples/.  Link it to version control like github.  And then use RStudio on my server to pull it from github into the web server root director /var/www/html. 

I had a quick look at your dashboard, nicely done.  Good luck with it!

**Comment by skofieldO5** [comment]
Thanks a lot for your help. I have a lot on my plate right now and I think it would be a lot of work to put up a whole new website just to get og tags working. I'm not sure if I could use this knowledge in future projects so I will think about it. But thanks again and I'm glad you like the dashboard.

**Comment by gadenbuie** [comment]
Thank you everyone for the suggestions in this issue. There may some inherent limitations here when search crawlers approach Shiny apps that likely depend on how they're deployed. In any case, I'd recommend using a package like [metathis](https://pkg.garrickadenbuie.com/metathis/) to help you include full metadata in your dashboard. I think this package should work for both static and dynamic flexdashboards, but if you run into any issues I'd be happy to help out.
