### ISSUE TITLE
Sourcing Multiple Rmd Files

### ISSUE THREAD

**Issue by S-UP** [rstudio/flexdashboard#195]
Hi,

I would like to clean up my flexdashboard file so that each page I have created can be sourced from a distinct file. I have not yet found an example on this. 

What would be the recommended way doing this?

Many thanks!

**Comment by jjallaire** [comment]
You can use the `child` chunk option to include another Rmd: https://yihui.name/knitr/demo/child/

**Comment by albamrt** [comment]
This way, is it possible to use the 'source_code: embed' option so that the code from each page or tab (sourced code) is shown? Thanks!!
