### ISSUE TITLE
Source Code for Flexdashboard Website

### ISSUE THREAD

**Issue by S-UP** [rstudio/flexdashboard#196]
Hi,

The [Flexdashboard ](https://rmarkdown.rstudio.com/flexdashboard/) product page is very well done. I would like to study the code to better understand how the setup looks like.

Specifically, I would like to understand how I can have the navigation on the left (known from standard Rmd files) and the navigation element at the top (default of Flexdashboard).

Would be great to add this info somewhere in the readme file.

Many thanks!

**Comment by jjallaire** [comment]
Here are docs on R Markdown websites: https://rmarkdown.rstudio.com/rmarkdown_websites.htm

Here is the source code for the flexdashboard site: https://github.com/rstudio/rmarkdown/tree/gh-pages/flexdashboard
