### ISSUE TITLE
plot_click using flexdashboard

### ISSUE THREAD

**Issue by zippedlightning** [rstudio/flexdashboard#197]
Hello, this is my first time posting on github.

Is there a way to have plots with mouse interactions using flexdashboard?

In shiny this is not difficult.  I want to save mouse clicks, and in shiny I would type:

In the ui, you would have:
    mainPanel(
      plotOutput("scatterplot", click = "plot_click"))

And in the server you would have:
df <- reactiveValues(Clicksdf = data.frame(clickx = numeric(), clicky = numeric()))

Can I do this in flexdashboard?

**Comment by jjallaire** [comment]
There are 2 ways to do this:

1) You can use crosstalk with widgets that support it: https://rstudio.github.io/crosstalk/ (this is a client-only solution, no server required)

2) You can use Shiny with flexdashboard: https://rmarkdown.rstudio.com/flexdashboard/shiny.html

**Comment by cpsievert** [comment]
And here's more links about how to do this sort of thing with shiny (and/or plotly)

https://shiny.rstudio.com/articles/#graphics
https://plotly-r.com/client-side-linking.html
https://plotly-r.com/linking-views-with-shiny.html
