### ISSUE TITLE
Automate Flexdashboard

### ISSUE THREAD

**Issue by iabubakar** [rstudio/flexdashboard#201]

**Comment by jjallaire** [comment]
RStudio Connect is one way to do this: https://www.rstudio.com/products/connect/

**Comment by iabubakar** [comment]
Many thanks. 
One has to install R Studio Connect and then automate the process of publishing?

**Comment by jjallaire** [comment]
Yes, RStudio Connect has features for scheduled publishing, secure access, and email notifications.

**Comment by iabubakar** [comment]
Dear.

Good day.

I had created and publish flexDashboard on Rpubs. it worked.

But I am now having a blank screen.
any help

counting on your cooperation.

many regards

Ismaela

**Comment by gadenbuie** [comment]
I you've been able to resolve your problem with Rpubs! Please feel free to comment here or to open a new issue if not.
