### ISSUE TITLE
Font Awesome brand icons

### ISSUE THREAD

**Issue by bhogan-mitre** [rstudio/flexdashboard#203]
I'm having trouble including a custom icon in the navbar.  I believe the issue is that it's a brand icon (ironically, [`fa-r-project`](https://fontawesome.com/icons/r-project?style=brands)) and the class needs to be `fab` instead of `fa`.

```
---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    navbar:
      - { title: "Test Icon", icon: "fa-r-project", href: "http://dummy.url", target: "_blank"}
---
```

This gets rendered with `class="fa fa-r-project"` and shows up as a blank square:
<img width="913" alt="broken_icon" src="https://user-images.githubusercontent.com/32336739/48687390-234e8800-eb8f-11e8-959f-72fbf5fd26c0.png">

If I manually adjust it with in the inspector/devtools to `class="fab fa-r-project"`, it shows up fine:
<img width="919" alt="fixed_icon" src="https://user-images.githubusercontent.com/32336739/48687576-0070a380-eb90-11e8-9fce-694c51725ad2.png">

**Comment by jjallaire** [comment]
This should be fixed with: https://github.com/rstudio/flexdashboard/commit/ccb5f1ad057f42da24818d6ff3acb0f4e6b944cb

So the following will now work for FA icon sets:

```
icon: "fab fa-r-project"
```

**Comment by bhogan-mitre** [comment]
Awesome, thank you!
