### ISSUE TITLE
Error in pngfun when rendering plots embeded in shiny in different pages

### ISSUE THREAD

**Issue by pernaletec** [rstudio/flexdashboard#204]
First of all my many thanks to the developers for this amazing tool. 

Let me explain the issue I am experiencing. With the following example code: 

---
title: "Test"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
runtime: shiny
---
```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(rmarkdown)
library(knitr)
```
Test 
=======================================================================
Column
-----------------------------------------------------------------------
```{r}
shinyApp(
  ui = fillPage(
    fillCol(flex = c(NA, 1), 
      inputPanel(
        selectInput("region", "Region:", choices = colnames(WorldPhones))
      ),
      plotOutput("phonePlot", height = "100%")
    )
  ),
  server = function(input, output) {
    output$phonePlot <- renderPlot({
      barplot(WorldPhones[,input$region]*1000, 
              ylab = "Number of Telephones", xlab = "Year")
    })
  }
)
```
Test 
=======================================================================

Column
-----------------------------------------------------------------------
```{r}
shinyApp(
  ui <- fluidPage(
    plotOutput("network")
  ),
  # Define server logic ----
  server <- function(input, output) {  
      output$network = renderPlot({
      #g = graph_from_data_frame(d = edges, directed=FALSE, vertices = nodes)
        plot(x=seq(1:10),y=seq(1:10))
      })
  }
)
```
Test 
=======================================================================
Column
-----------------------------------------------------------------------
```{r}
shinyApp(
  ui = fillPage(
    fillCol(flex = c(NA, 1), 
      inputPanel(
        selectInput("region", "Region:", choices = colnames(WorldPhones))
      ),
      plotOutput("phonePlot", height = "100%")
    )
  ),
  server = function(input, output) {
    output$phonePlot <- renderPlot({
      barplot(WorldPhones[,input$region]*1000, 
              ylab = "Number of Telephones", xlab = "Year")
    })
  }
)
```

I get the following output: 

_Warning: Error in pngfun: invalid 'width' or 'height'
  125: pngfun
  124: startPNG
  123: drawPlot
  109: <reactive:plotObj>
   93: drawReactive
   80: origRenderFunc
   79: output$network
    3: <Anonymous>
    1: rmarkdown::run
Warning in pngfun(filename = filename, width = width, height = height, res = res,  :
  unable to allocate bitmap
Warning in pngfun(filename = filename, width = width, height = height, res = res,  :
  opening device failed
Warning: Error in pngfun: unable to start png() device
  125: pngfun
  124: startPNG
  123: drawPlot
  109: <reactive:plotObj>
   93: drawReactive
   80: origRenderFunc
   79: output$phonePlot
    3: <Anonymous>
    1: rmarkdown::run_

A warning is shown for seconds in the second and third page the first time they are clicked. Then the warning dissapear and the plot is shown as expected. I really don't know what could be happening. 

Could you guys please let me know if you can reproduce this issue and its possible solution?

My sessionInfo() output:

_sessionInfo()
R version 3.4.4 (2018-03-15)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 7 (build 7601) Service Pack 1_

_Matrix products: default_

_locale:
[1] LC_COLLATE=Spanish_Bolivarian Republic of Venezuela.1252  LC_CTYPE=Spanish_Bolivarian Republic of Venezuela.1252   
[3] LC_MONETARY=Spanish_Bolivarian Republic of Venezuela.1252 LC_NUMERIC=C                                             
[5] LC_TIME=Spanish_Bolivarian Republic of Venezuela.1252_    

_attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base_

_loaded via a namespace (and not attached):
 [1] compiler_3.4.4        backports_1.1.2       magrittr_1.5          rsconnect_0.8.8       rprojroot_1.3-2      
 [6] htmltools_0.3.6       tools_3.4.4           flexdashboard_0.5.1.1 yaml_2.1.18           Rcpp_0.12.16         
[11] stringi_1.1.7         rmarkdown_1.10        knitr_1.20            jsonlite_1.5          stringr_1.3.0        
[16] digest_0.6.15         evaluate_0.10.1_   

Thanks in advance!

**Comment by jcheng5** [comment]
Without having run the example yet, my guess is that the pixel size of the embedded app is very small before its respected page is shown.

Is there a reason you're embedding shinyApp, instead of putting the renderPlot directly in the document?

**Comment by pernaletec** [comment]
@jcheng5 thank you very much for your super fast feedback!

I just tried your suggestion and in fact works well writing down the code straight in the document. This way: 

Test 
=======================================================================

Column
-----------------------------------------------------------------------

```{r}

  inputPanel(
    selectInput("region", "Region:", choices = colnames(WorldPhones))
  )
  renderPlot({
    barplot(WorldPhones[,input$region]*1000, 
            ylab = "Number of Telephones", xlab = "Year")
  })
  
```

Test 
=======================================================================

Column 
-----------------------------------------------------------------------

```{r}
    inputPanel(
      selectInput("region", "Region:", choices = colnames(WorldPhones))
    )
  renderPlot({
    barplot(WorldPhones[,input$region]*1000, 
            ylab = "Number of Telephones", xlab = "Year")
  })


```

Test 
=======================================================================

Column 
-----------------------------------------------------------------------

```{r}

    inputPanel(
      selectInput("region", "Region:", choices = colnames(WorldPhones))
    )

  renderPlot({
    barplot(WorldPhones[,input$region]*1000, 
            ylab = "Number of Telephones", xlab = "Year")
  })
  
```

In my real case the plot for each page is a product of a quite long code and, for readability, I prefer to have it embeded as an external application. 

Could you give me a hint about how can I deal with 

> the pixel size of the embedded app is very small before its respected page is shown

Best regards.

**Comment by jcheng5** [comment]
I would strongly urge you not to use an external application for reasons if code readability; instead, use a Shiny module, which is designed for that purpose. Using an external application necessarily siloes your application into an iframe, which will make it much harder to get a seamless appearance with the rest of the page (assuming that is the goal).

**Comment by pernaletec** [comment]
Ok @jcheng5, taking into account your reccomendation, I am trying to repeat the task using the WorldPhone.R example module and the following .Rmd code: 

Test 
=======================================================================

Column
-----------------------------------------------------------------------

```{r}
# include the module
source("worldPhones.R")

# call the module
worldPhonesUI("phones")
callModule(worldPhones, "phones")
```

Test 
=======================================================================

Column 
-----------------------------------------------------------------------

```{r}
# include the module
source("worldPhones.R")

# call the module
worldPhonesUI("phones")
callModule(worldPhones, "phones")
```
_However the following error appears:_

_Warning in min(w.l) : no non-missing arguments to min; returning Inf
Warning in max(w.r) : no non-missing arguments to max; returning -Inf
Warning in min(x) : no non-missing arguments to min; returning Inf
Warning in max(x) : no non-missing arguments to max; returning -Inf
Warning: Error in plot.window: need finite 'xlim' values
  168: plot.window
  167: barplot.default
  165: renderPlot
  163: func
  123: drawPlot
  109: <reactive:plotObj>
   93: drawReactive
   80: origRenderFunc
   79: output$phones-phonePlot
    3: <Anonymous>
    1: rmarkdown::run_

Any hint?

**Comment by pernaletec** [comment]
It worked ok with my real code!
The problem with calling twice the same module seems to be a conflict with the namespace.
