### ISSUE TITLE
bookmarking with flexdashboard

### ISSUE THREAD

**Issue by vdamico** [rstudio/flexdashboard#206]
Hi,

I cannot get this to work and replies on the topic seem very scarce: Does bookmarking currently work with R markdown and flexdashboard? 
> packageVersion("shiny")
[1] ‘1.1.0’
> packageVersion("flexdashboard")
[1] ‘0.5.1.1’

Appreciate all help!

**Comment by jjallaire** [comment]
IIRC this won't work out of the box. @jcheng5 I do recall us discussing that if you render your Shiny UI elements dynamically with uiOutput then it might work but I forget the details now. Any hope here?

**Comment by vdamico** [comment]
Thanks J.J. @jcheng5 could you help out on a potential solution with uiOutput? I'd like to report back to the team how we should deal with our problem.

**Comment by gadenbuie** [comment]
I believe this is the same problem as reported in #153,mm,m,
