### ISSUE TITLE
Some themes affect rendering of gauges - flexdashboard

### ISSUE THREAD

**Issue by charlie-bee** [rstudio/flexdashboard#209]
All themes but default, cosmo, flatly, lumen make gauges looked faded. This is with `theme: yeti`
![image](https://user-images.githubusercontent.com/9541789/51480900-3bde4880-1d60-11e9-9bb6-5adc876bdaa1.png)

**Comment by cpsievert** [comment]
You can now do this with the development version (you may also want to wait for #308 to be merged)

````
---
output: 
  flexdashboard::flex_dashboard:
    theme: 
      bootswatch: yeti
      primary: lime
---
````
