### ISSUE TITLE
Font Awesome displays square in valueBox

### ISSUE THREAD

**Issue by davejshirley** [rstudio/flexdashboard#216]
Related to issue #203, but in `valueBox`.  

Some icons display correctly in valueBox, setting the icon with the `icon` argument, but others are not found and display as a backup icon (square box).

If the `icon` argument is set to a value that starts with 'fa-', the first word in the class is also 'fa', but sometimes it needs to be set to other values such as 'fas' to display properly.

Example of failure:
`valueBox('hello', icon = "fa-tachometer-alt")`
Output as displayed after js processing:
`<i class="fa fa-tachometer-alt"></i>` (shows as square)

Example of workaround:
`valueBox('hello', icon = "- fas fa-tachometer-alt")`
Output as displayed after js processing:
`<i class="- fas fa-tachometer-alt"></i>` (shows as correct icon)

The workaround relies on flexdashboard.js splitting the iconLib on `-` (around line 1680) and  interpretation of the resulting tag being sufficiently tolerant, but there probably should be a mechanism just to specify that full class.

**Comment by al-obrien** [comment]
I believe there are also some icons recently released (>5.1) such as [fas fa-baby](https://fontawesome.com/icons/baby?style=solid) which perhaps are not available through rmarkdown/flexdashboard at this time. I am also curious if some of the comments circulating around are related to the need to update the icons available?

**Comment by cpsievert** [comment]
Can confirm that `valueBox('hello', icon = "fa-tachometer-alt")` works. Please reopen if you can provide another example of an icon that requires that unfortunate workaround.

**Comment by cpsievert** [comment]
Also, FontAwesome icons are bundled with rmarkdown, not flexdashboard, so if you're waiting on new icons, please follow https://github.com/rstudio/rmarkdown/issues/1661
