### ISSUE TITLE
How to anchor-link to a #### Heading inside a Flexdashboard

### ISSUE THREAD

**Issue by pablobernabeu** [rstudio/flexdashboard#219]
I would like to ask how to link to a `#### Heading` inside a Flexdashboard page. Linking to a page proper is easy with `[](#heading)`, yet I'm having trouble finding out about this more specific kind of anchor link. I've tried creating it as [suggested here](https://stackoverflow.com/a/39293457/7050882), but it didn't work. 

Thank you very much indeed

**Comment by cderv** [comment]
For reference, this also has been posted on the community
https://community.rstudio.com/t/how-to-anchor-link-to-a-heading-inside-a-flexdashboard-page/30595/2

**Comment by pablobernabeu** [comment]
> For reference, this also has been posted on the community
> https://community.rstudio.com/t/how-to-anchor-link-to-a-heading-inside-a-flexdashboard-page/30595/2

Thank you!

**Comment by pablobernabeu** [comment]
No apparent solution, based on current answers

https://community.rstudio.com/t/how-to-anchor-link-to-a-heading-inside-a-flexdashboard-page/30595

**Comment by gadenbuie** [comment]
This was also requested in #190 (I'm pretty sure they're functionally the same: deep linking beyond the page). I definitely see the value in this feature, so I'm going to close this issue in favor of the older one. Please subscribe to that issue to be notified of any work in this area. Thank you!
