### ISSUE TITLE
Tabset headers get cut off when too many storyboard tiles present in header

### ISSUE THREAD

**Issue by ZackLarsen** [rstudio/flexdashboard#220]
When adding more than a few storyboard tiles to flexdashboard, I notice that my main page has part of it cut off because the names of the additional storyboard tiles or social media links in the navbar begin to wrap around and create a new row in the header. 

In my example (see attached screenshots below), I have three tabs in the tabset on my landing page, and they all disappear when I add the "Newtab" storyboard to my markdown notebook. The social media links in the navbar and the source code embedding are moved below where they were prior to adding the "Newtab" storyboard. You can see from the screenshots that the "Data", "Crimes involving use of a firearm", and "Arrests Made" tabs are no longer visible when the "Newtab" storyboard is added.

Is there a way to fix this issue while still being able to have multiple storyboards in one flexdashboard? Something that comes to mind is having an arrow that lets you scroll through the storyboard names at the top of the page instead of dropping them down to a different level.

Thanks for your help and thanks for making flexdashboard an amazing tool for presenting work!
-Zack

<img width="1437" alt="Screen Shot 2019-05-26 at 10 20 45 AM" src="https://user-images.githubusercontent.com/29289933/58383761-1d06f180-7fa0-11e9-8d0a-15effde29008.png">

<img width="1434" alt="Screen Shot 2019-05-26 at 10 21 26 AM" src="https://user-images.githubusercontent.com/29289933/58383762-1d06f180-7fa0-11e9-918b-6b7376c7221a.png">

**Comment by ZackLarsen** [comment]
Fixed issue by using the "data-navmenu=" option next to each storyboard name to group several together and avoid the issue of overcrowding the header with many storyboard or page names.
Example:

Statistical {.storyboard data-navmenu="Menu A"} 
Categorical {.storyboard data-navmenu="Menu A"} 

Geospatial {.storyboard data-navmenu="Menu B"} 
Ward Features {.storyboard data-navmenu="Menu B"}

**Comment by jecabcas** [comment]
Thank you @ZackLarsen ,  I am having the same problem and I will apply as suggested.
Also, here are my two cents, I believe the size of the screen is contributing to this issue. I found that this issue is more prevalent in laptops than on bigger screens.
