### ISSUE TITLE
change gauge min/max labels and add threshold indicator

### ISSUE THREAD

**Issue by hyedd77** [rstudio/flexdashboard#225]
I am new to flexdashboard and am using gauges in correlation with a risk calculator. Because the risk probabilities are usually very small and a 0 to 100 scale isn't practical for showing these small changes, I am using various min and max parameters and would like to change the min and max text labels to simply be "Low" and "High". 

Also, I would like to add an indicator such as a black line on the gauge that indicates a certain threshold for average population risk. 

I haven't found a way to do either of these things within the standard gauge parameters, and am wondering if there's a way to customize/access the widget itself to make these changes if not possible the standard way. 

Here's the code that I'm using to build the gauges. The value is passed as a percent, so the min and max of 0 and 1 imply that the gauge ranges from 0 to 1 percent. 

build_gauge <- function(value, average_risk) {
  return(gauge(round(value, 2), symbol = "%", min = 0, max = 1, sectors = gaugeSectors(success = c(0, average_risk), warning = c(average_risk, average_risk*2), danger = c(average_risk*2, 100)), abbreviate = TRUE, abbreviateDecimals = 0))

Thanks ahead for any help!

**Comment by gadenbuie** [comment]
Thanks for the question and apologies on the very long delay in responding! Unfortunately, the JavaScript library used by flexdashboard for the gauges ([justgage](https://toorshia.github.io/justgage/)) doesn't allow for customizing the min/max text labels or adding a line marking a single value. I can certainly see the value in a dashboard setting; maybe you can build something custom with [ggplot2](https://ggplot2.tidyverse.org/) or [plotly](https://plotly.com/r/)?
