### ISSUE TITLE
 `{.hidden}` attribute not responsive to reactive values

### ISSUE THREAD

**Issue by rjake** [rstudio/flexdashboard#229]
We love flexdashboard at work. Lately we have found the need to hide pages/tabs from the navbar based on a user's log-in or because the selection criteria returned no results, making a detail tab unnecessary. It seems that the `{.hidden}` attribute cannot be controlled using reactive values. I have a post here but so far no takers:
https://stackoverflow.com/questions/57280199/flexdashboard-hidden-navbar-tab-using-reactive-values

Similar points have been brought up in #142 and #46

**Comment by cpsievert** [comment]
Closing since it appears someone has posted a fairly good workaround. Here it is:

````
---
title: "-"
output: flexdashboard::flex_dashboard
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)

show_hide <- "show" # "hidden"

r_show_hide <- reactive(ifelse(session$clientData$url_hostname == "127.0.0.1", "hidden", "show"))
```

Does work {.`r show_hide`}
=============================

### Should be `r show_hide`


Doesn't work {.`r isolate(r_show_hide())`}
===============================

### Should be `r renderText(r_show_hide())`

````
