### ISSUE TITLE
多页面标题是否可以支持中文？

### ISSUE THREAD

**Issue by yanan9256** [rstudio/flexdashboard#23]
flexdashboard 0.1.0版本
多页面，页标题是中文的话，无法切换页面

**Comment by taiyun** [comment]
Try：

```
第一页 {#page1}
============
```

**Comment by yanan9256** [comment]
I want to:
`第一页子标题一 {data-navmenu="第一页"}`
And This is what I got:
`<a href="#undefined" data-toggle="tab">第一页子标题一</a>`

**Comment by jjallaire** [comment]
Fixed via https://github.com/rstudio/flexdashboard/commit/bba4e61e0f7aa22d9d551cb2a247f013e6d2a3fb
