### ISSUE TITLE
DataTables warning

### ISSUE THREAD

**Issue by ddjustina** [rstudio/flexdashboard#230]
Flexdashboard is awesome, thank you so much.

But, I keep getting this warning. Don't know what is the reason.

Already tried:
- devtools::install_github('rstudio/DT')

![flex_warning](https://user-images.githubusercontent.com/7991816/62261187-d512a980-b3ea-11e9-917c-062036680a41.PNG)

**Comment by jcheng5** [comment]
Thanks for the report. Could you send a reproducible example?

**Comment by ddjustina** [comment]
> 
> Thanks for the report. Could you send a reproducible example?

@jcheng5 so sorry for the delay. Here is the code and the data. Thanks for the support.
[issue_demo.zip](https://github.com/rstudio/flexdashboard/files/3464929/issue_demo.zip)

**Comment by gadenbuie** [comment]
I can reproduce the problem with the example provided, thank you! I can also resolve the issue by commenting out the following lines from the `DT()` call

```r
      columnDefs = list(
        list(
          visible = FALSE,
          targets = c(2, 3, 5:15)
        )
      ),
```

which indicates to me that there's an issue with those lines. My guess is that that `targets` refers to columns that don't exist; from what I can tell there are only 10 columns in the source data. If you change

```
targets = c(2, 3, 5:15)
```

to

```
targets = c(2, 3, 5:9)
```

the document renders without the warning. (Also note that `columnDefs` uses JavaScript's syntax of indexes starting from 0.)
