### ISSUE TITLE
flexdashboard with two tabs and a leaflet on each make leafletProxy() not work

### ISSUE THREAD

**Issue by dan-reznik** [rstudio/flexdashboard#236]
Imagine a simple flexdashboard with two "tabs" and a UI and a leaflet on each, as in the code skeleton below. The leaflet on the 2nd tab is not getting initialized (accessed via leafletProxy()), since  it does not "exist" during loadtime. The main question is: how do I adapt the solutio n in https://github.com/rstudio/leaflet/issues/590 to flexdashboard? They give tabs and id which informs the code if a given tab is exposed. Any help appreciated!

---
title: "The Title"
output: 
  flexdashboard::flex_dashboard:
    css: styles.css
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(tidyverse)
# other libs
```

# Tab1
## SideBar1 {.sidebar}

```{r}
selectInput("inp1", "Inp1" ,
            c(ch1="ch1",ch2="ch2"),
            selected="ch1")
```

### Leaflet1

```{r}
output$map1 <- renderLeaflet({
  leaflet() %>%
    addTiles() %>%
     fitBounds(map=.,lng1=-43,lat1=-22,lng2=-42,lat2=-21)

leafletOutput('map1') 
```

```{r, include=F}
update_leaflet <-  function(map_name,input)
# this works because its exposed
  leafletProxy(map_name, data = df_leaflet) %>%
    clearControls() %>%
    clearShapes() %>% 
    addCircles(...) %>%  addLegend(...) # omitting args for brevity
 })
}

observeEvent(input$inp1 , update_leaflet("map1",input))
```

# Tab2
## SideBar2 {.sidebar}

```{r}
selectInput("inp2", "Inp2" ,
            c(ch1="ch1",ch2="ch2"),
            selected="ch1")
```

### Leaflet 2

```{r}
output$map2 <- renderLeaflet({
  leaflet() %>%
    addTiles() %>%
     fitBounds(map=.,lng1=-43,lat1=-22,lng2=-42,lat2=-21)

leafletOutput('map2') 
```

```{r, include=F}
update_leaflet <-  function(map_name,input)
# this doesn't work because the 2nd leaflet is not exposed at load time
  leafletProxy(map_name, data = df_leaflet) %>%
    clearControls() %>%
    clearShapes() %>% 
    addCircles(...) %>%  addLegend(...) # omitting args for brevity
 })
}

observeEvent(input$inp2 , update_leaflet("map2",input))
```

**Comment by LaurS12** [comment]
Did you ever solve this issue? I recognize this post is from a while ago but I am now having this issue where the second tab of my flexdashboard won't load the leaflet maps when I publish to Shiny

**Comment by LaurS12** [comment]
Did you ever resolve this issue? I am now having a similar problem with mine

**Comment by gadenbuie** [comment]
Thanks for reporting @dan-reznik and for linking to the Shiny-based solution! I agree that the underlying issue is that flexdashboard should report the active tab to the Shiny process, which would allow the linked Shiny-based solution to work. #237 is a better description of the required work, so I'm going to close this issue in favor of that issue.
