### ISSUE TITLE
cant add multiple wordclouds from wordcloud2

### ISSUE THREAD

**Issue by phillynerd** [rstudio/flexdashboard#238]
I'm struggling to get the both wordclouds to appear. I tried adding self_contained: FALSE to the yaml header, along with a few other widget wrappers, but I haven't been able to figure out what the issue is.  It's not a sizing issue, since if you remove the wordcloud from chunk1, the wordcloud renders fine in chunk2. 

-------------------------------------
\---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
\---

\```{r setup, include=FALSE}
library(flexdashboard)
library(wordcloud2)
\```

Column 
\-----------------------------------------------------------------------

\### Chart A

\```{r chunk1}
wordcloud2(demoFreq, color = "random-light")
\```

Column
\-----------------------------------------------------------------------

\### Chart B

\```{r chunk2}
wordcloud2(demoFreq, color = "random-dark")
\```

**Comment by jl5000** [comment]
This isn't an issue with flexdashboard, it's a namespace issue with wordcloud2. Someone's forked it and implemented a fix, but it's not on CRAN.

https://github.com/Lchiffon/wordcloud2/issues/60
