### ISSUE TITLE
Update a table from a fileinput

### ISSUE THREAD

**Issue by michael-lambe** [rstudio/flexdashboard#239]
I am trying to create a shiny/flexdashboard in which the table can be refreshed by uploading a new file.

I was wondering what is the recommended way to proceed with such use-case.

The code below is a simple dashboard with a table (using formattable) that is first loaded with a dataset. The user can use the file upload widget to upload a new dataset - I would like to understand how to refresh the table once the upload is complete. Should this be done in the new_df_tbl event?

The example is self-contained and can be used directly in Rstudio.

    ---
    title: "Basic"
    output: 
      flexdashboard::flex_dashboard:
        orientation: rows
        vertical_layout: fill
    runtime: shiny
    ---
    
    ```{r setup, include=FALSE}
    library(flexdashboard)
    library(shinyWidgets)
    library(shiny)
    library(formattable)
    library(tidyverse)
    ```
    
    ```{r}
    df <- data.frame(
      x = rnorm(100),
      y = rnorm(100)
    )
    ```
    
    ```{r}
    df_tbl <- reactive({
        df %>% select(x, y) # do some stuff here but for simplicity we do nothing
    })
    ```
    
    
    
    Sidebar {.sidebar}
    =======================================================================
    
    ```{r}
    fileInput("file1", "Choose CSV File",
                    multiple = FALSE,
                    accept = c("text/csv",
                             "text/comma-separated-values,text/plain",
                             ".csv"))
    
    br()
    
    actionButton(inputId = "apply", label = "Apply", icon = icon("play"))
    ```
    
    ```{r}
    rv <- reactiveValues(data = NULL)
    rv <- df
    
    observeEvent(eventExpr = input$apply, 
      handlerExpr = {
          req(input$file1)
          file <- read_csv(input$file1$datapath)
          rv$data <- file
      }, ignoreNULL = FALSE)
    ```
    
    
    Main
    =======================================================================
    
    Column
    -----------------------------------------------------------------------
    
    ### Table
    
    ```{r}
    renderFormattable({
      formattable(df_tbl())
    })
    ```

As I am not sure how to proceed with such logic, I also created a [ticket on SoF](https://stackoverflow.com/questions/58098139/update-shiny-table-from-a-file-input)

**Comment by cpsievert** [comment]
The answer on SO offers pretty sound advice
