### ISSUE TITLE
Link to source code for Pokemon Dashboard not working

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [rstudio/flexdashboard#242]
The link to the source code for the Pokemon Dashboard (http://jkunst.com/flexdashboard-highcharter-examples/pokemon/) example is not working. This is linked at https://rmarkdown.rstudio.com/flexdashboard/examples.html.

@jbkunst do you have an updated link that can be pointed to?

**Comment by sbridel** [comment]
https://github.com/jaywhitmire/pokemon/blob/master/Pokemon%20Dashboard.Rmd

**Comment by cderv** [comment]
@sbridel I don't think this is really the same one. 🤔  

The source code for the pokemon dashboard linked from flexdashboard examples page is here on @jbkunst repo:
https://github.com/jbkunst/flexdashboard-highcharter-examples/tree/gh-pages/pokemon

**Comment by mine-cetinkaya-rundel** [comment]
Thanks @cderv. I made a PR to @jbkunst's repo to reflect the correct link.
