### ISSUE TITLE
renderText not working in headers

### ISSUE THREAD

**Issue by jy-r** [rstudio/flexdashboard#245]
**Expected behavior** 

- changing input will change the result in header

**Actual behavior**

- following code worked in previous versions of `R` and `flexdashboard`, but in current stopped working 
- not working in 
  - `R version 3.6.1 (2019-07-05) -- "Action of the Toes"`
  - `Flexdashboard 0.5.1.1`
  - `shiny 1.4.0`

**Example**

````
--
title: "test"
output: flexdashboard::flex_dashboard
runtime: shiny
---

```{r}
library(flexdashboard)
library(shiny)
```

Inputs {.sidebar}
-------------------------------------

```{r}
selectInput(
  "month", 
  label = "Pick a Month",
  choices = month.abb, 
  selected = month.abb[2]
)

getmonth <- reactive({
  sprintf('Box 2 (%s)', input$month)
})

renderText({getmonth()})
```  

Column  
-------------------------------------

### `r renderText(getmonth())`
````

**Comment by cderv** [comment]
FWIW, I can reproduce with last version of rmarkdown, flexdashboard and shiny 1.4.0. It works with shiny 1.3.2. The issue seems to come from there.

**Comment by wch** [comment]
@schloerke and I bisected it to the commit in Shiny which upgrade to jQuery 3. This is probably a timing issue, related to:

* rstudio/shiny#2630
* rstudio/shiny/issues/2635

**Comment by gorodnichy** [comment]
Unfortunately , I had the same problem.

I wanted to do this (input taken from shiny menu)

# Country: `r renderText(input$country)` 

It does not work - prints empty space

My sessionInfo below


> R version 3.6.1 (2019-07-05)
> Platform: x86_64-redhat-linux-gnu (64-bit)
> Running under: Fedora 29 (Twenty Nine)
> 
> Matrix products: default
> BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so
> 
> locale:
>  [1] LC_CTYPE=en_CA.UTF-8       LC_NUMERIC=C               LC_TIME=en_CA.UTF-8        LC_COLLATE=en_CA.UTF-8     LC_MONETARY=en_CA.UTF-8    LC_MESSAGES=en_CA.UTF-8   
>  [7] LC_PAPER=en_CA.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_CA.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
>  [1] dplyr_0.8.5           leaflet_2.0.3         DT_0.13               flexdashboard_0.5.1.1 stringr_1.4.0         lubridate_1.7.4       magrittr_1.5         
>  [8] dtplyr_1.0.1          data.table_1.12.8     shiny_1.4.0.2         plotly_4.9.2          ggplot2_3.3.0        
>
