### ISSUE TITLE
Multiple issues with notes

### ISSUE THREAD

**Issue by MySchizoBuddy** [rstudio/flexdashboard#25]
Adding notes or text before and after {r} code has confusing effects. Starting with this flex doc. Im having a hard time adding rmarkdown code here. it tries to render it and mess it up. Here is the image of the code.
![image 3](https://cloud.githubusercontent.com/assets/51676/15451217/5ad0edbe-1fd0-11e6-869e-d35dcc5a421b.png)

Which results in the following
![image 1](https://cloud.githubusercontent.com/assets/51676/15451218/623a15ee-1fd0-11e6-9b8e-34db94785140.png)

When you add any text after the title tag it clips the x axis. Adding any text after the r code makes it a script tag. Only the last note using > is shown as a note the others are shown as blockquote. See the generated html 

Using Flexdashboard 0.2 and knitr 1.13 on MRO 3.2.5

**Comment by jjallaire** [comment]
This behavior is all expected. If you want to add text annotations you
should put them in a blockquote *after* the chart (and those annotations
will appear in a footer element so shouldn't be that long). Alternatively
you can put them in their own section.

**Comment by MySchizoBuddy** [comment]
what about the xaxis being clipped when add text before the graph

**Comment by jjallaire** [comment]
You can't include free form text and a graphic in the same chunk

**Comment by jgoldmann** [comment]
I agree with @MySchizoBuddy, supporting graphs with text could be handled more smoothly than it is now. Now, the user is restricted to add explanations as small comment after the plot.
