### ISSUE TITLE
Is there a way to include flexdashboard into a shiny app?

### ISSUE THREAD

**Issue by keithmichaelf** [rstudio/flexdashboard#251]
Shiny app only seems to be able to include markdown files. I know shiny apps can be called from flex but can the opposite be done?
Is there way to include the flexdashboard RMD file inside a shiny app? Kindly help.

**Comment by cpsievert** [comment]
You can turn a flexdashboard document into a shiny app by adding `runtime: shiny` to the yaml matter


You can't, however, (natively) embed flexdashboard inside a larger shiny app (you could embed it via an HTML iframe, though).
