### ISSUE TITLE
Include table of contents in flexdashboard

### ISSUE THREAD

**Issue by ChenTaHung** [rstudio/flexdashboard#252]
I would like to insert a table of contents in my flexdashboard, just like the example :

https://rmarkdown.rstudio.com/flexdashboard/using.html

but `toc: true` and `toc: yes` both don't work

Is there any way to add a toc in a flexdashboard?

Thanks!

**Comment by cderv** [comment]
I think the flexdashboard website, so the page `using.html` you link to, is not made with flexdashboard itself but using Rmarkdown website. https://bookdown.org/yihui/rmarkdown/rmarkdown-site.html 

With Rmarkdown website generator, you can organize your Rmd as a website with a navbar. You can add a TOC in each Rmd with format `html_document`

`toc` is not an argument of `flexdashboard::flex_dashboard`, as you can check in the doc`?flexdashboard::flex_dashboard`

Hope I understand well your question and that it helps.

**Comment by ChenTaHung** [comment]
@cderv  Ok~ So `using.html` is a website written with `Rmarkdown website` that attached a `html_document` Rmd file and the table of contents had already been included in the document. Did I get it?

**Comment by cderv** [comment]
Yes. 
In the documentation I linked above, you'll have the link to the source code of the website. You'll find the source Rmd file [`using.rmd`](https://github.com/rstudio/rmarkdown/blob/gh-pages/flexdashboard/using.Rmd). The whole repository will be a good example if you don't know it yet.

**Comment by gadenbuie** [comment]
Thank you for the question @ChenTaHung! And thanks @cderv for the answer. By the way, the page in question is now located here: https://pkgs.rstudio.com/flexdashboard/articles/using.html
