### ISSUE TITLE
Sidebar won't render

### ISSUE THREAD

**Issue by jzelner** [rstudio/flexdashboard#257]
Hi - I haven't seen an open issue for this but am perplexed about why I can't get a sidebar to render in a flexdashboard. Here is a MNWE:

```
---
title: "Transmission model."
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
---

Sidebar {.sidebar}
===========================


Dashboard
==========================

### Age-specific

### Infectiousness

Second Page
=========================

### More Results
```
When I render, either in rstudio or on the command line, I get this:

![image](https://user-images.githubusercontent.com/136323/77445347-5b895a80-6dc3-11ea-86e9-29cf7540d4bf.png)

I have tried this with and without shiny, updating my shiny, flexdashboard, and rmarkdown installations, and still get the same result. Here is my `sessionInfo`:

![image](https://user-images.githubusercontent.com/136323/77445502-8f648000-6dc3-11ea-9197-0b25bfde39a6.png)

Any assistance would be greatly appreciated!

**Comment by cderv** [comment]
If I copy paste your MRE, I get the correct result
![image](https://user-images.githubusercontent.com/6791940/77474988-61f5f180-6e18-11ea-94da-e018f3ea245d.png)

I think I used the same 📦 as you. note sure how to test further. 
Can you try what I did and copy paste from github in a new Rmd ? 
Also, what is your version of pandoc ? (`rmarkdown::pandoc_version()`)

<details><summary> Session Info </summary>

``` r
xfun::session_info("flexdashboard")
#> R version 3.6.3 (2020-02-29)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 18363)
#> 
#> Locale:
#>   LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252   
#>   LC_MONETARY=French_France.1252 LC_NUMERIC=C                  
#>   LC_TIME=French_France.1252    
#> 
#> Package version:
#>   base64enc_0.1.3          BH_1.72.0.3              crayon_1.3.4            
#>   digest_0.6.25            evaluate_0.14            fastmap_1.0.1           
#>   flexdashboard_0.5.1.9000 glue_1.3.2               graphics_3.6.3          
#>   grDevices_3.6.3          highr_0.8                htmltools_0.4.0         
#>   htmlwidgets_1.5.1        httpuv_1.5.2             jsonlite_1.6.1          
#>   knitr_1.28               later_1.0.0              magrittr_1.5            
#>   markdown_1.1             methods_3.6.3            mime_0.9                
#>   promises_1.1.0           R6_2.4.1                 Rcpp_1.0.4              
#>   rlang_0.4.5              rmarkdown_2.1.1          shiny_1.4.0.2           
#>   sourcetools_0.1.7        stats_3.6.3              stringi_1.4.6           
#>   stringr_1.4.0            tinytex_0.20             tools_3.6.3             
#>   utils_3.6.3              xfun_0.12                xtable_1.8.4            
#>   yaml_2.2.1
```

<sup>Created on 2020-03-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

</details>

**Comment by jzelner** [comment]
Thanks for giving it a shot! I'm currently running Pandoc 2.8; wonder if updating to 2.9 will make a difference?

**Comment by jzelner** [comment]
Yep, that fixed it. Thanks!
