### ISSUE TITLE
Cant run `source()` code in `flexdashboard::flex_dashboard`

### ISSUE THREAD

**Issue by yuliaUU** [rstudio/flexdashboard#258]
I am not sure why I cant run the `source() ` command. it works in other documants

> ---
> title: "Row Orientation"
> output: 
>   flexdashboard::flex_dashboard:
>     orientation: rows
> ---
> ```{r setup, include=FALSE}
> library(ggplot2)
> library(plotly)
> library(flexdashboard)
> source('scripts/script.R')
> ````
> 

I received an error ` Error in file(filename, "r", encoding = encoding) : cannot open the connection`

**Comment by shrektan** [comment]
When Rmarkdown is rendering, the working directory is changed to the `dirname()` of the file, temporarily. It means the file path in `source()` should be changed to a path that's relative to the current working directory.

BTW, I believe you are supposed to call `source()` with the argument `local=TRUE`, as you may only want to run the codes of `scripts/script.R` as if they were copied & pasted to the Rmd file.

**Comment by yuliaUU** [comment]
Thank you!
