### ISSUE TITLE
Custom port and host

### ISSUE THREAD

**Issue by xianglinZ** [rstudio/flexdashboard#259]
Hi, I really like this package, especially it can be viewed directly on the web page, but now I have a small problem, that is, shiny can customize the listening port and host, I want to know whether flexdahboard can also, What should I do if I can? I used this template:
---
title: "Multiple Pages"
output: flexdashboard :: flex_dashboard
runtime: shiny
---
Ask the teacher for advice, thank you very much!

**Comment by cderv** [comment]
I think you need to customize the shiny options in the call of [`rmarkdon:run`](https://rmarkdown.rstudio.com/docs/reference/run.html)

See example in the doc:
```r
# Run the Shiny document "shiny_doc.Rmd" on port 8241
rmarkdown::run("shiny_doc.Rmd", shiny_args = list(port = 8241))
}
```
You can pass shiny options using `shiny_args`. These are option passed to `runApp`, so you can also pass `host`. 

Let's not that [`runApp` argument has some default value from R option](https://shiny.rstudio.com/reference/shiny/1.4.0/runApp.html). So setting the shiny option should work for flexdahsboard with shiny runtime. 
* `getOption("shiny.port")`
* `getOption("shiny.host", "127.0.0.1")`
See the help page of `runApp`

Hope it helps

**Comment by xianglinZ** [comment]
Oh, thank you very much, it made me realize, this is a good way, you are right, I run successfully, now I have to consider the issue of encryption, do you know any good way to encrypt the shiny program of flexdashboard.

**Comment by cderv** [comment]
Please let's stick to what Github Issue are made for: Reporting issue or suggesting feature request. 
For general question and sharing experience, you should ask on https://community.rstudio.com
There is a broader community there ready help, and with some people more advanced than me about shiny stuff. 

If your initial issue has been answered here, please close this issue. For your new question, open it on the community for a follow up discussion. 

Is this ok with you? 

Thank you.

**Comment by xianglinZ** [comment]
Hello, is there any good way to stop the service for RMarkdown :: run ()

**Comment by cderv** [comment]
It depends how you launch this code. 
Can you ask this kind of question in the QA website https://community.rstudio.com ?
it is better this keeping on discussing in GH issue. Thank you !
