### ISSUE TITLE
Unable to render a gvis object

### ISSUE THREAD

**Issue by snakonechny** [rstudio/flexdashboard#26]
Hello,

Thank you much for putting together this great package! I'm having some issues with rendering gvis objects in flexdashbaord. Here's a minimal example:

---
title: "Sample"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(googleVis)
library(dplyr)

df <- iris %>% group_by(Species) %>% mutate(meanSLength = mean(Sepal.Length))
```

Column {data-width=650}
-----------------------------------------------------------------------

### Sample column chart in googleVis

```{r, results='asis', message=FALSE, echo=FALSE}
renderGvis(
  
  gvisBarChart(df, "Species", "meanSLength")
  
)
```

Above `renderGvis` I do specify `results='asis', message=FALSE, echo=FALSE`. Still, I get the following back:

<img width="1005" alt="screen shot 2016-05-21 at 10 46 16 pm" src="https://cloud.githubusercontent.com/assets/8390111/15451853/ebd98a9e-1fa5-11e6-925c-2c98decc398a.png">

This happens in both the RStudio preview window and the browser.

Any help would be much appreciated!

Thanks!

**Comment by jjallaire** [comment]
Yes, googleVIs objects aren't htmlwidgets (http://www.htmlwidgets.org)
which is the standard protocol for JavaScript visualizations within R, and
what we built flexdashboard to interoperate with so I don't think this will
work.

J.J.

On Sat, May 21, 2016 at 10:48 PM, Svyat Nakonechny <notifications@github.com

**Comment by snakonechny** [comment]
@jjallaire ,
Thanks for a quick response! I tried testing rCharts in flexdashbaord and received a similar error message. I take it these interactive visualizations also aren't supported?

**Comment by jjallaire** [comment]
No, we just support htmlwidgets

On Sun, May 22, 2016 at 10:54 AM, Svyat Nakonechny <notifications@github.com

**Comment by paulditterline** [comment]
@snakonechny, using the ggplotly() wrapper from the plotly package on ggplot objects does allow for interactivity in flexdashboard. See: https://paulditterline.shinyapps.io/Louisville_Salaries/

**Comment by snakonechny** [comment]
@paulditterline , thanks for the pointer!
