### ISSUE TITLE
Define featured image for social network share?

### ISSUE THREAD

**Issue by ozturkib** [rstudio/flexdashboard#260]
I added social icons to navbar for a flexdashboard, but there's no way to add an featured image once it is shared.

In the R Markdown file:

output: 
 ```
 flexdashboard::flex_dashboard:
    orientation: rows
    social: ["facebook", "twitter", "linkedin"]
    # source_code: embed
    vertical_layout: fill
```
How can i set an featured image for social media share for a page on flexdashboard?

Please see [my stackoverflow question](https://stackoverflow.com/questions/61083046/how-to-define-featured-image-for-social-network-share-on-flexdashboard). There is no answer at all.
Thanks

**Comment by d-qn** [comment]
Did you try with [metathis](https://github.com/gadenbuie/metathis)? It worked for me using `meta_social()` for my flexdashboard

**Comment by gadenbuie** [comment]
Thanks for the question @ozturkib and the answer @d-qn. I'm slightly biased but I do think that [metathis](https://cran.r-project.org/package=metathis) provides a good solution for this problem. If rmarkdown revisits it's approach to metadata and opengraph tags, we'll also take a look at updating flexdashboard's approach.
