### ISSUE TITLE
navigating via location hash does not work with multiple pages

### ISSUE THREAD

**Issue by rtaseen** [rstudio/flexdashboard#262]
[test.Rmd.txt](https://github.com/rstudio/flexdashboard/files/4533597/test.Rmd.txt)

Reprex attached

If you navigate to page 2, then click on the link to chart c, you are redirected back to page 1 instead of going down to chart c. When there is a single page, anchor links work.

The source seems to be the popstate event listener on line 1210 of flexdashboard.js
```
    // navigate to a tab when the history changes
    window.addEventListener("popstate", function(e) {
      var hash = window.location.hash;
      var activeTab = $('ul.nav a[href="' + hash + '"]');
      if (activeTab.length) {
        activeTab.tab('show');
      } else {
        $('ul.nav a:first').tab('show');
      }
      FlexDashboardUtils.manageActiveNavbarMenu();
    });
```
Removing this listener fixes the issue in firefox/chrome and there is no issue in IE11, which does not support popstate events.

Removing the else branch (`$('ul.nav a:first').tab('show');`) also fixes the issue.

I am not sure why the default behavior in the else branch is to go back to the first page, but if it is necessary for some other condition, maybe there should be a check to see if the anchor link is valid before?

**Comment by s-etty** [comment]
:+1: I am also running into this issue

**Comment by gadenbuie** [comment]
Thank you for the issue report. Fundamentally, the goal is to be able to deep-link to elements within a page, which was previously reported in https://github.com/rstudio/flexdashboard/issues/190 (where we'll track progress on that front). I don't believe flexdashboard will redirect you to the first page anymore if you click an internal link that doesn't correspond to a page.
