### ISSUE TITLE
Theme sandstone defaults to green sub-theme

### ISSUE THREAD

**Issue by libjohn** [rstudio/flexdashboard#263]
The [sandstone theme](https://bootswatch.com/sandstone/) is predominantly a grey/black/slate color palette.   However, when applying the sandstone theme in flexdashboards, the color palette is derived from the sandstone-success sub-color palette -- which is a rather over-hot green/chartreuse.  

I spent some time trying to override this with style sheets but failed.  While I had some success with a very basic single page dashboard, my more developed dashboards (multi-page) simply did not benefit from the simple CSS alterations.  Can the sandstone theme in flexdashboards be aligned with the bootswatch color palette for primary and secondary colors ranges?

If there's a way for me to help with this, I'm willing.  Might need a mentor to guide me as I fix it.

**Comment by cpsievert** [comment]
You can now do this with the development version (you may also want to wait for #308 to be merged)

````
---
output: 
  flexdashboard::flex_dashboard:
    theme: 
      bootswatch: sandstone
      primary: orange
---
````
