### ISSUE TITLE
Change second tabset on click

### ISSUE THREAD

**Issue by mfherman** [rstudio/flexdashboard#264]
I'm working on a self-contained flexdashboard project and I'm wondering if it's possible when a user clicks to a new tab in one tabset, it changes to a new tab on a second tabset as well. 

So for example, when you click on "Chart B1" below, I would also like to change view to "Chart B2" in the second column. And clicking on "Chart A2" would change back to "Chart A1", etc. etc.

![Screen Shot 2020-04-25 at 07 32 59](https://user-images.githubusercontent.com/24945757/80482206-ca595680-8921-11ea-9282-5d6a6670e5e2.png)

````
---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```

Column {.tabset}
-----------------------------------------------------------------------

### Chart A1

### Chart B1

Column {.tabset}
-----------------------------------------------------------------------

### Chart A2

### Chart B2
````

NOTE: I've asked this on [RStudio Community](https://community.rstudio.com/t/change-second-tabset-on-click-in-flexdashboard/63101) and  [StackOverflow](https://stackoverflow.com/questions/61458456/change-second-tabset-on-click-in-flexdashboard) without any answers.

**Comment by bransonf** [comment]
This can be implemented with JavaScript. Full answer on[ StackOverflow](https://stackoverflow.com/a/61585037/12408287)

**Comment by cderv** [comment]
I saw this issue as a nice JS exercie and I came up with this JS chunk using JQuery and bootstrap tabset helper

```md
```{js}
document.addEventListener("DOMContentLoaded", function(){
    $('a[data-toggle="tab"]').on('click', function(e){
      child = e.target.parentNode;
      column = $(e.target).closest("div[id]");
      columnid = column.attr("id");
      tabnum = Array.from(child.parentNode.children).indexOf(child);
      if (columnid == "column") {
        columnto = "column-1";
      } else {
        columnto = "column";
      }
      $("div[id="+columnto+"] li:eq("+tabnum+") a").tab('show');
    })
});
```
```

It can work with any number of tabs in your two colomn format. 

It is just another way to do what was answer on SO. Hope it helps

**Comment by mfherman** [comment]
Thanks to both of these great solutions!

**Comment by Gerardo-P-Garcia** [comment]
When I attempt this, switching to another page within the document and back resets the first column to 1 while leaving the 2nd wherever it was last on. Any means of fixing this?

**Comment by cderv** [comment]
> Any means of fixing this ? 

Do you talk about a fix in the JS snipper above or with some issue in the package ? 

For the former asking on Stackoverflow or RStudio community would be a better place to get help modifying the Javascript code so that it suits your need. The first answer https://github.com/rstudio/flexdashboard/issues/264#issuecomment-623249543 comes from there

**Comment by npiepgrass** [comment]
Thank you for this wonderful solution, this is very useful. I wasn't able to get the intended functionality when I knit the minimal example in rmarkdown. I checked my indents and spacing the rmarkdown document, and I inspected the html output and found the js script. Is there anywhere I should look to figure out what the problem might be?

**Comment by McQdev** [comment]
Same issue. The minimal example no longer works.

**Comment by McQdev** [comment]
@cderv any thoughts on what might have changed between when this jQuery solution was authored and now such that it's no longer functioning?

**Comment by cderv** [comment]
I don't know specifically. One would need to debug the JS code and adapt it to the newer version of **rmarkdown** output. 

Recent **rmarkdown** will use JQuery 3 by default for example. Also, this could not work if you are using a format that would use Bootstrap 4 or higher by default. 

Did one of you tried looking into what is breaking ?

**Comment by McQdev** [comment]
Not sure what's breaking; there are no console errors or obvious issues in the timeline that I can tell. I'm not familiar with debugging JS within an rmarkdown so I'm not entirely sure how to proceed.

**Comment by McQdev** [comment]
Not sure if it's helpful, but I've been unable to get _any_ JS event listeners working in rmarkdown... Again, no console messages or indications of what's broken, they just have stopped listening!

**Comment by McQdev** [comment]
`Failed to execute 'querySelectorAll' on 'Element'` is what I'm getting in browser debugger, seems.

**Comment by slytilex** [comment]
I'm a bit late, but i'm having the same issue. Do you guys have any solutions ?

**Comment by slytilex** [comment]
i guess no
