### ISSUE TITLE
Multiple Plots on One Tabset Tab

### ISSUE THREAD

**Issue by elbamos** [rstudio/flexdashboard#265]
A couple of people have asked about this on stackoverflow without a useful answer. (E.g., https://stackoverflow.com/questions/43306672/how-to-display-multiple-plots-on-an-r-flexdashboard-page-if-using-storyboard-lay   https://stackoverflow.com/questions/51127918/r-flexdashboard-multiple-plots-on-single-tab).

What I would like to do is have a page of my `flexdashboard` (row-oriented) with two rows.  The top row is a constant visualization. I would like the bottom row to be a `tabset` where each tab contains multiple plots. 

If I attempt to do it like this:

```
Page
=====

Row
------

### Vis 1

[some stuff]

Row {.tabset}
------

## Tab Heading

### Plot 1

[stuff]

### Plot 2

[stuff]
```

Then, depending on whether the Tab Heading is a second or third or whatever level header,  each plot either becomes its own tab, or they all overlap, or some other not-what-was-desired. 

Is there a way to accomplish my goal? Alternatively, please consider this a feature request.

**Comment by cderv** [comment]
With flexdashboard, title levels have different meaning, and the first 3 each serves a purpose. 

* Level 1 are for pages (see about [multiple pages](https://rmarkdown.rstudio.com/flexdashboard/using.html#multiple_pages)
* Level 2 are for definining the layout, Row or Column. See about [orientation](https://rmarkdown.rstudio.com/flexdashboard/using.html#orientation)
* Level 3 are for defining the component, and define the title of each boxes. See about [title](https://rmarkdown.rstudio.com/flexdashboard/using.html#components). They are also uses to defines tabset name (See about [tab row](https://rmarkdown.rstudio.com/flexdashboard/layouts.html#tabset_row)

Let's remind that in markdown 
* level 1 is `#` before the text or `=========` under the text
* level 2 is `##` before the text or `--------------` under the text. 

If you use `##` it is a level two. So i think this kind of markdown code won't work and will not play nice with flexdashboard default layout.

```md
Row {.tabset}
------

## Tab Heading

### Plot 1
```

If you want tabset, you need to follow the doc and use level 3 title directly under the tabsetted level 2 header.

This works to put two plots, in the same tabset.
````md
---
title: test
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
---

Page
=====

Row
------

### Vis 1

```{r}
knitr::kable(mtcars)
```


Row {.tabset}
------

### Plot 1

#### Plot1

```{r}
plot(iris)
```

#### Plot2

```{r}
plot(mtcars)
```

### Tab 2

```{r}
plot(iris)
```
```` 

For the sizing, you need to create some plots that fits correctly on the flexdashboard layout you choose. 

Hope it helps.

**Comment by elbamos** [comment]
@cderv Thank you for clarifying some things about markdown headers and flexdashboard behavior I had not previously understood. 

The code you provided seems to get part of the way there, but not quite to the end. 

The result is that only the first plot on the tab shows up.  Actually, during loading, I see the headers for the two plots one on top of the other.  When the first plot on the tab loads, however, it either pushes the second plot out of view, or appears directly on top of it.  This is true even with the width fixed in the call to create the output (e.g., `highchartOutput(name, width="300px")`).  

Perhaps the tab is trying to arrange itself as a column rather than as a row? 

Do you have any other suggestions? 

Thanks!

**Comment by cderv** [comment]
> The result is that only the first plot on the tab shows up. 

When I run the example I made, I get the two plots on the first tab, with a vertical scroll on the right. 
In you real example it could be different, depending on what you include. 

Flexdashboard is using a specific layout that you need to deal with regarding he components you include. Having several widgets in the same "box" or "tab" may require some adjustement. 
See https://rmarkdown.rstudio.com/flexdashboard/using.html#sizing

Specifically the [flexbox layout}(https://rmarkdown.rstudio.com/flexdashboard/using.html#flexbox_layout) may cause diffculties. 

Do not hesitate to ask for help and ideas on RStudio Community too. There is a broad community with experience. 

If you think there is an issue with one of the widgets you use, please provide a working reproducible example to help me investigate. Thank you !

**Comment by elbamos** [comment]
> When I run the example I made, I get the two plots on the first tab, with a vertical scroll on the right.

Right. The issue is that even though this dashboard is set with `orientation: rows`, `flexdashboard` is trying to orient the `tabset` as a single column, arranging the charts vertically rather than horizontally. 

That's the problem I'm trying to solve.

**Comment by cderv** [comment]
Ok I understand now. Thanks ! 

I don't think that flexdashboard tabsets allow for a grid layout with row or column inside each tab. Only for the main page layout. Inside each tab, it is the same as Rmarkdown I think - linear. 
You may achieve a different layout using CSS maybe.... 
Anyway this is a feature request: hability to create rows inside column, or columns inside row.

Sometimes it can help:  for plots, you can organise them as you like using tools like `cowplot`, `patchwork`, or any other. It will help create one figure with plots organize in row and/or column. 

Also, this layout feature request is related to #37, #79

**Comment by aescherling** [comment]
I was struggling with this for a while, but managed to pull together the following workaround using a flexbox. In particular, to put two figures side by side in a tabset row:

```
Row {.tabset}
-----------------------------------------------------------------------

### Tab1

<div style='display:flex; flex-direction:row; justify-content:space-evenly; align-items:center;'>

<div>
[insert R code block for figure here]
</div>

<div>
[insert R code block for figure here]
</div>

</div>
```

For a helpful guide to flexboxes see https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Basic_Concepts_of_Flexbox

**Comment by cpsievert** [comment]
For posterity the comment above is a great option if you're wanting to put multiple htmlwidgets in a single tab, but if you're hoping to do something similar for static R plots, consider using something like https://patchwork.data-imaginist.com/

**Comment by gadenbuie** [comment]
Thanks everyone for replying with these suggestions. It seems like the original question has been answered, so I'm going to close this issue. If you find yourself with a similar question, please open a new issue!

**Comment by eliseburriss** [comment]
> I was struggling with this for a while, but managed to pull together the following workaround using a flexbox. In particular, to put two figures side by side in a tabset row:
> 
> ```
> Row {.tabset}
> -----------------------------------------------------------------------
> 
> ### Tab1
> 
> <div style='display:flex; flex-direction:row; justify-content:space-evenly; align-items:center;'>
> 
> <div>
> [insert R code chunk for figure here]
> </div>
> 
> <div>
> [insert R code chunk for figure here]
> </div>
> 
> </div>
> ```
> 
> For a helpful guide to flexboxes see https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Basic_Concepts_of_Flexbox

Thank you! 
Am editing someone elses flexdashboard, and I dont really use flexdashboard, so this helped save a lot of time!
