### ISSUE TITLE
Problems with tables from `gt` package

### ISSUE THREAD

**Issue by awgymer** [rstudio/flexdashboard#267]
It seems that `flexdashboard` doesn't recognise tables generated with the `gt` package as tables, I believe because they are wrapped in `div` and the `table` element isn't at the top level of the content. This leads to them being put inside `chart-shim` wrappers which cause long tables to be cut off. 

I think this is a more general problem with the way `flexdashboard` decides what sort of container to put content in, because I've noticed the same thing happen when I generate custom HTML content for a section with `htmltools`. 

An example is when I tried to put an image and a guage in the same section:

    div(
    div(class = "rage-guage-wrapper",
       div(class = "rage-guage-logo-wrap", img(class = "rage-guage-logo",  src=get_team_logo(TEAM_0, logos_pth))),
       div(class = "rage-guage-guage",
         gauge(
           ref_rating[allegiance==TEAM_0, rating], min = -1, max = 1, 
           gaugeSectors(success = c(0.25, 1), warning = c(-0.25, 0.25), danger = c(-0.25, -1))
       )
    )
    ))

It would be useful if there was some way to force a row/column section to behave in a fixed manner rather than relying on its guesswork. Perhaps something like being able to do:

`### Custom Table Section {tabular}`

or 

`### Custom HTML section {noshim}`

**Comment by jthomasmock** [comment]
Just a heads up, you can get scrolling for `gt` or other arbitrary output by wrapping `gt` in a `div()`:

```
div(style='height:600px; overflow-y: scroll', gt(mtcars))
```



<details><summary>Full Example of an R Markdown doc</summary>

````
---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(gt)
library(kableExtra)
library(htmltools)
```

Column {data-width=650;}
-----------------------------------------------------------------------

### Chart A

```{r}
div(style = 'overflow: scroll', gt(mtcars))
```

Column {data-width=350;}
-----------------------------------------------------------------------

### Chart B

```{r}
div(style='height:600px; overflow-y: scroll', gt(mtcars))
```

### Chart C

```{r}
div(style='height:600px; overflow-y: scroll', gt(mtcars))
```



````

</details>

**Comment by awgymer** [comment]
This was a while back now, but the issue was I think I explicitly *didn't* want scrolling. Like with a `kable` table it just expands the divs to the size of the largest table. I ended up adding some custom JS to create an extra component finder:

```javascript
// gt tables
window.FlexDashboardComponents.push({
  find: function(container) {
    return container.find('.gt-no-scroll');
  },
  flex: function(fillPage) {
    return fillPage;
  }
});
```

Then wrapping my `gt` tables in a div with that class (I think that maybe now `gt` supports adding classes to top-level divs itself?). 

You can see an example of it in practice [here](https://awgymer.github.io/rugby-stats/wc-final-eng-sa-dash.html)

**Comment by Nilafhiosagam** [comment]
I'm facing the same issue 

Using jthomasmock's approach with div() inserts a scroll bar but it doesn't scroll. My html knowledge is zero

I have the output as: 
orientation: rows
vertical_layout: scroll

![image](https://user-images.githubusercontent.com/45123924/95212943-2a63fb00-07e6-11eb-907e-ef5ad55855f4.png)

**Comment by lstarkey** [comment]
> This was a while back now, but the issue was I think I explicitly _didn't_ want scrolling. Like with a `kable` table it just expands the divs to the size of the largest table. I ended up adding some custom JS to create an extra component finder:
> 
> ```js
> // gt tables
> window.FlexDashboardComponents.push({
>   find: function(container) {
>     return container.find('.gt-no-scroll');
>   },
>   flex: function(fillPage) {
>     return fillPage;
>   }
> });
> ```
> 
> Then wrapping my `gt` tables in a div with that class (I think that maybe now `gt` supports adding classes to top-level divs itself?).
> 
> You can see an example of it in practice [here](https://awgymer.github.io/rugby-stats/wc-final-eng-sa-dash.html)

This is so so close to helping me address my problem, except the "fillpage" fix doesn't allow the content to scroll. Any ideas?

**Comment by awgymer** [comment]
@lstarkey yes, per above I didn't want it to scroll so that doesn't surprise me. 

Not sure exactly what you are trying to achieve but I have a scrollable table on the page I linked at the end of my previous comment (Where in the world? Section) that might be what you are after so you could look at what I did there (this was ages ago so off the top of my head I can't tell you)

**Comment by awgymer** [comment]
Hmm I seem to remember when I was trying to make this work I spent a lot of time working in chrome devtools to adjust the css until I had the layout I wanted and then worked out how to make flexdashboard generate that. 

Do you know what actual settings you need the table/div to have yet?

**Comment by lstarkey** [comment]
nope, not sure. Thanks anyway!

**Comment by gadenbuie** [comment]
It seems this has been resolved for everyone! If you're facing a similar challenge, definitely check out [Tom's comment here](https://github.com/rstudio/flexdashboard/issues/267#issuecomment-702940982). If you happen to have a similar problem, please open a new issue with a [reprex](https://reprex.tidyverse.org) and we'll be happy to look into it.
