### ISSUE TITLE
Storyboard commentary divs have fixed height on mobile view 

### ISSUE THREAD

**Issue by francisbarton** [rstudio/flexdashboard#272]
When my site is in mobile, single-column mode, the commentary `div` heights are all set to the height of the first commentary. If subsequent commentaries are longer, their text gets truncated.

Here's what I'm seeing in the relevant HTML + CSS:

```
<div class="section level3 chart-wrapper chart-wrapper-flex" style="height: 472px; flex: 472 472 472px;">
[commentary content...]
</div>
```

The 472px sizing obviously comes from the height of the first commentary div, as the text of this fits perfectly.
But this same sizing is then applied to all the other commentary divs in my storyboard, so that any longer commentary texts are cut off.

(Setting `flex-grow` and `flex-shrink` to 472 instead of just 1 seems a bit weird, too.)
But it's the `flex-basis` being a fixed height that is the problem.
If only `flex-basis: content;` was a thing!

There's no suitable parent div that I could set the height of in my own CSS file, and then set `flex-basis: auto !important;` on the class `.chart-wrapper-flex`.

I can try to make a reprex if necessary.

**Comment by cpsievert** [comment]
> I can try to make a reprex if necessary.

That would be great, thanks!

**Comment by gadenbuie** [comment]
Hi @francisbarton! It's been a couple of years and I'm hoping your issues were resolved in the mean time. If not, feel free to comment with a [reprex](https://reprex.tidyverse.org) and we'll be happy to take a look.
