### ISSUE TITLE
Shiny modules example does not reflect moduleServer best practices

### ISSUE THREAD

**Issue by emilyriederer** [rstudio/flexdashboard#275]
The [example](https://rmarkdown.rstudio.com/flexdashboard/shiny.html#shiny_modules) of using Shiny modules with `flexdashboard` relies on the old `callModule()` paradigm. However, I understand that as of Shiny 1.5 [it's recommended](https://shiny.rstudio.com/articles/modules.html#migrating-from-callmodule-to-moduleserver) to use the `moduleServer()` paradigm instead.

The server function definition should be changed to:

```
worldPhones <- function(id) {
  moduleServer(id, function(input, output, session) {
    output$phonePlot <- renderPlot({
      barplot(WorldPhones[, input$region] * 1000,
              ylab = "Number of Telephones", xlab = "Year")
    })
  })
}
```

and the example code of calling this in a dashboard should be changed to:

```
worldPhonesUI("a")
worldPhones("a")
```

Sorry for not sending a PR for the change itself, but somehow I wasn't spotting the website in the repo.

**Comment by cpsievert** [comment]
Hi @emilyriederer! Once #313 is merged (hopefully soon), you'll be able to find the examples under `vignettes/` (a PR would be very welcome :) )
