### ISSUE TITLE
Example on flex_dashboard help page does not work

### ISSUE THREAD

**Issue by tyner** [rstudio/flexdashboard#276]
When I try to run the example on the flex_dashboard help page, 
```r
library(rmarkdown)
library(flexdashboard)
   
# simple invocation
render("dashboard.Rmd", flex_dashboard())
```

it says:

> Error in abs_path(input) : The file 'dashboard.Rmd' does not exist.
> In addition: Warning message:
> In normalizePath(path, winslash = winslash, mustWork = mustWork) :
>  path[1]="dashboard.Rmd": No such file or directory

Here is my sessionInfo():

> R version 4.0.2 (2020-06-22)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Ubuntu 18.04.4 LTS
> 
> Matrix products: default
> BLAS:   /home/btyner/R402/lib/R/lib/libRblas.so
> LAPACK: /home/btyner/R402/lib/R/lib/libRlapack.so
>
> locale:
> [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
> [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
> [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
> [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
> [9] LC_ADDRESS=C               LC_TELEPHONE=C            
>[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
>
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] rmarkdown_2.3       flexdashboard_0.5.2 DT_0.15            
> [4] crosstalk_1.1.0.1  
> 
> loaded via a namespace (and not attached):
>  [1] digest_0.6.25     R6_2.4.1          jsonlite_1.7.0    magrittr_1.5     
>  [5] evaluate_0.14     rlang_0.4.7       tools_4.0.2       htmlwidgets_1.5.1
>  [9] xfun_0.16         yaml_2.2.1        compiler_4.0.2    tcltk_4.0.2      
> [13] htmltools_0.5.0   knitr_1.29

**Comment by cderv** [comment]
It is because the file does not exist if you haven't created it. You need to create a Rmd file using flexdashboard before running this commands. They are examples of how you could render programmatically a Rmd file using flexdashboard. The second call of the example is with another _hypothetical_ file called `pres.Rmd` to show how to modify the theme. 

If you want to get started, it is best to go to https://rmarkdown.rstudio.com/flexdashboard/

**Comment by tyner** [comment]
Then perhaps the example could be enhanced to point to a pre-existing file e.g.

```r
render(file.path(find.package("rmarkdown"), "doc/rmarkdown.Rmd"), flex_dashboard())
```

**Comment by cderv** [comment]
It would be best with a flexdashboard Rmd, and not in another directory than where package files are (otherwise it would render there). Maybe by first using `rmarkdown::draft` to copy the flexdashboard template then rendering. You could send a PR if you want.
