### ISSUE TITLE
Values in valuebox not showing up after running the app for the second time

### ISSUE THREAD

**Issue by kianweelee** [rstudio/flexdashboard#279]
There seems to be an issue with rendering the valuebox if the user decides to restart the application and run it again for the second time. 

If we run it for the first time we will see the following:

![Capture9](https://user-images.githubusercontent.com/46987985/91630265-7612d000-ea02-11ea-9d01-60108e76e3c3.PNG)

If we change the values in the csv file, the number in the valuebox will automatically change. 

However if we run it the second time, we see the following:

![Capture10](https://user-images.githubusercontent.com/46987985/91630285-9a6eac80-ea02-11ea-86ef-02acc88dd579.PNG)

I was wondering if anyone face similar issue and how did you go about resolving it?

I have attached an example file in my repo [here](https://github.com/kianweelee/flexdashboard_test). 

Thanks in advance!

**Comment by cpsievert** [comment]
I think oyur problems derive from the fact that `runtime: shiny` needs to be specified at the top-level. If I change your example's yaml to:

````
---
title: "Test"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
---
````

Then it works for me
