### ISSUE TITLE
corrupting DT:renderDataTable functions

### ISSUE THREAD

**Issue by missymorrow** [rstudio/flexdashboard#28]
Before installing the `flexdashboard `package I was able to execuate this example from the DT library documentation just fine without any issues,

```
library(shiny)
shinyApp(
  ui = fluidPage(DT::dataTableOutput('tbl')),
  server = function(input, output) {
    output$tbl = DT::renderDataTable(
      iris, options = list(lengthChange = FALSE)
    )
  }
)
```

After installing the `flexdashboard `package when i run the same code above the output from the renderDataTable function is corrupted. The datatable does not render accurately and all I see is one line with column names as shown below and I am unable to see the actual contents of the datatable.

![test1](https://cloud.githubusercontent.com/assets/19525272/15460674/2c38f650-2079-11e6-9453-a7991f4b7009.png)

Also renderDataTable does not work while producing Flexdashboard apps using RMarkdown.

**Comment by harryprince** [comment]
you need to use ```as.html``` function to convert dataTable results into html

**Comment by missymorrow** [comment]
I am confused with this answer because I did not use `formattable::as.htmlwidget()` in shiny and the documentation on DT does not recommend using `formattable::as.htmlwidget()`

**Comment by jjallaire** [comment]
We set a couple of DT options to make it behave properly within
flexdashboard and these need to be unset after using flexdashboard (we'll
take care of the unset in a future version of flexdashboard but don't yet
have the hooks to do this cleanly from rmarkdown). Try executing this code
at the top of your Shiny server.R:

options(DT.fillContainer = FALSE)
options(DT.autoHideNavigation = FALSE)

**Comment by missymorrow** [comment]
@jjallaire after adding those two lines everything is working fine another issue is that `renderdatatable `does not render the datatable while I am trying some flexdashboard type apps using Rmarkdown.

**Comment by jjallaire** [comment]
fixsed via https://github.com/rstudio/flexdashboard/commit/854a2ceb867522fa892d66417a43733e476c92ec
