### ISSUE TITLE
New pkgdown documentation site - new build plan?

### ISSUE THREAD

**Issue by apreshill** [rstudio/flexdashboard#280]
Hi @rich-iannone  @schloerke and @jjallaire -

As discussed, we'll convert this R Markdown documentation website into a pkgdown site. I see that the current site is in the `gh-pages` branch, so I wanted to check in before throwing a new documentation site in the mix. Many of our teams prefer not to have the pkgdown `docs` living in the `master` branch, but I don't see any Travis or GitHub Actions for the package build in this repo.

What we did for the [R Markdown documentation site](https://rmarkdown.rstudio.com/docs/) was use Travis to build the site and deploy to Netlify. See code here:

https://github.com/rstudio/rmarkdown/blob/284b685c2feb68083b3434c6ca38717cd61cbeea/.travis.yml#L29-L37

I believe we can do the same combo of Travis + Netlify, or Travis + GH pages if you prefer.

Another option, adopted by the tidyverse team, is using GitHub Actions to deploy to the `gh-pages` branch (then use either GH pages or Netlify to publish), following [`usethis::use_tidy_github_actions`](https://usethis.r-lib.org/reference/tidyverse.html). For example:
+ https://github.com/allisonhorst/palmerpenguins/blob/master/.github/workflows/pkgdown.yaml
+ https://github.com/rstudio/gt/blob/master/.github/workflows/pkgdown.yaml

Do any of these solutions sound preferable to you all?

**Comment by apreshill** [comment]
Ah I just figured out the `gh-pages` branch here is all redirects! As a breadcrumb for myself, the current doc site lives here:

https://github.com/rstudio/rmarkdown/tree/gh-pages/flexdashboard

**Comment by apreshill** [comment]
I have this workflow now operational:

+ in a `pkgdown` branch, 
+ using GH actions to push to `gh-pages` branch,
+ deploying to GitHub Pages

https://github.com/apreshill/flexdashboard/tree/pkgdown

https://apreshill.github.io/flexdashboard/index.html

I did need to clear out the `gh-pages` branch content for this to work (the GH action would not overwrite it since the content was not written by pkgdown originally).

**Comment by schloerke** [comment]
@apreshill I am all for using GHA and the `gh-pages` branch. 

I didn't know the website was hosted under rmarkdown's website. That's odd.

Thank you for the work on this. Please let me know how I can help.

**Comment by cpsievert** [comment]
I think this can be closed now (once the pkgdown workflow is working fully), but let me know if there's anything let to do in the flexdashboard repo, thanks Alison!
