### ISSUE TITLE
add CI to this package and some more tests

### ISSUE THREAD

**Issue by cderv** [rstudio/flexdashboard#284]
There is recently an issue with flexdashboard containing htmlwidgets not working (see #282  and related issues). 
This was due to a change in knitr that had an impact on **flexdashboard**.

As this package does not have much tests, it has not be seen before **knitr** CRAN release. 

What do you think about adding some more tests with content (only the empty template is tested currently), or using GHA or travis / appveyor to render some some flexdahsboard examples to see if that still work ?

**Comment by cderv** [comment]
Sorry I looked to quickly.

**Comment by cpsievert** [comment]
Unit tests are now running via GHA. We also are monitoring a few app examples inside https://github.com/rstudio/shinycoreci-apps

**Comment by cderv** [comment]
Great ! This should be enough to find possible issues with knitr and rmarkdown changes ! 👍
