### ISSUE TITLE
Make dashboard output optional when creating a shiny app

### ISSUE THREAD

**Issue by PhilippPro** [rstudio/flexdashboard#288]
I am creating a flexdashboard from a shiny app using a report.Rmd and `rmarkdown::render`. Is there an easy way to make tabs optional, that means make them dependent on a checkbox in the shiny app? (e.g. checkbox == TRUE -> show tab, checkbox == FALSE -> do not show tab)

**Comment by cpsievert** [comment]
Your best option is probably to do something like `shinyjs::toggle()` everytime the checkbox is pressed:

```r
observeEvent(input$checkbox_id, {
   shinyjs::toggle("tabset_id")
})
```

Closing since this is more of a question about using shiny than it is a request of flexdashboard (next time use https://community.rstudio.com/ to ask this sort of question)
