### ISSUE TITLE
DT tables clipped when text is added to flexdashboard body

### ISSUE THREAD

**Issue by jhuntergit** [rstudio/flexdashboard#290]
**Actual Behavior - Clipping**

When I add text to the body of a DT table, the bottom of the dashboard is clipped (to varying extents). See below. I presume this is a flexdashboard bug, if not please move to the DT issue tracker.

````R
---
title: "With text in the body the bottom is clipped"
output: flexdashboard::flex_dashboard
---

Notice at the bottom that "Showing X entries" and "Previous/Next" are both clipped

```{r}
library(DT)
datatable(mtcars)
```
````

[![bottom of dashboard clipped][2]][2]

**Expected Behavior - No Clipping**

If I remove the text from the body of my table everything behaves as expected. Notice there's no clipping at "Showing X entries" and "Previous/Next".

````R
---
title: "Without text in the body nothing is clipped"
output: flexdashboard::flex_dashboard
---

```{r}
library(DT)
datatable(mtcars)
```
````

[![not clipped dashboard][1]][1]

_Version Info:_

````R
other attached packages:
[1] DT_0.16             flexdashboard_0.5.2
````

  [1]: https://i.stack.imgur.com/m78bt.png
  [2]: https://i.stack.imgur.com/TdFFx.png

**Comment by cpsievert** [comment]
Please read this section on what you can and cannot do with text annotations https://flexdashboard-pkg.netlify.app/articles/using.html#text-annotations-1
