### ISSUE TITLE
Why is standalone not entirely standalone? some "*.js.map" are missing

### ISSUE THREAD

**Issue by rdatasculptor** [rstudio/flexdashboard#299]
I am a huge fan of flexdashboard! I use the package to make nice looking, standalone dashboards. So far so good.

Today a dashboard I am working on does not exactly what I intended it should do. Some htmlwidgets look not entirely properly rendered, or not entirely embedded included in the final html document. Inspecting the console of the page give this information:

```
DevTools failed to load SourceMap: Could not load content for https://myurl/mydir/tippy.all.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://myurl/mydir/shim.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://myurl/mydir/reactable.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://myurl/mydir/react-tools.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

I tried to render the flexdashboard again with explicitly setting the parameter `self_contained = TRUE`. The same error appears after rendering. How is it possible it still tries to load sourcemaps whilst it should be entirely standalone? Does anyone have an idea about how to make it really standalone?

I hope someone has an idea without a reproducable example. But if needed, I will try to make one. 

Many thanks in advance!

**Comment by cpsievert** [comment]
Pretty sure those 404s are result of some other package(s) you're using inside of `{flexdashboard}` (perhaps `{reactable}`?) Please make a reproducible example and file in the appropriate repo.
