### ISSUE TITLE
Show nothing for chartJSRadar function

### ISSUE THREAD

**Issue by unityculture** [rstudio/flexdashboard#30]
Hi 
Thanks for your amazing pacakge, I'm glad to use it!
but when I used `chartJSRadar` to generate [Radar Chart](https://cran.r-project.org/web/packages/radarchart/radarchart.pdf) in flexdashboard 
I got nothing in storyboard page. (It can show up in markdown)

Thanks !

**Comment by jjallaire** [comment]
Radar Chart doesn't appear to implement a resize method at all:

https://github.com/MangoTheCat/radarchart/blob/master/inst/htmlwidgets/chartJSRadar.js

I think that's the problem.

**Comment by voxnonecho** [comment]
Related to [this issue](https://github.com/rstudio/flexdashboard/issues/68)
