### ISSUE TITLE
Non-responsive sizing with highcharts and different browsers

### ISSUE THREAD

**Issue by Eflores89** [rstudio/flexdashboard#31]
I create a dashboard with two highcharts in columns and tabsets. When knitting and looking thru the Rstudio visualizer the charts look okay. 

But when taking the html file and opening in a browser (chrome and explorer) the highcharts are not responsive to the new size. The tabs are unresponsive in both Rstudio and chrome.

Here are some pictures to ilustrate (the second tab chart does not recognize size limits).

![original r](https://cloud.githubusercontent.com/assets/5789139/15512866/9dff9a08-21a7-11e6-93ab-76c1692eefeb.PNG)
 ![new r](https://cloud.githubusercontent.com/assets/5789139/15512867/9e00b7ee-21a7-11e6-9384-1a9b73d08f37.PNG)
Is this something that should be added to the highcharts code? Is it a bug or is there a work-around?

**Comment by timelyportfolio** [comment]
@Eflores89, I have run into this a couple of times also.  `htmlwidgets` in these [lines](https://github.com/ramnathv/htmlwidgets/blob/master/R/sizing.R#L195-L201) sets `defaultSizing` differently for the viewer than the browser.  `fill=TRUE` by default for viewer, so the containing div gets `100%` for `width` and `height`.  When in the browser, the default `fill=FALSE` causes an explicit `width` and `height` to be set on the container for the `htmlwidget`.  The `resizeHandler` will be called [in these lines](https://github.com/ramnathv/htmlwidgets/blob/master/inst/www/htmlwidgets.js#L569-L580), but the explicit `width` and `height` do not adjust so resize is called with the same `height` and `width`.  One potential solution is to set `height="100%", width="100%"` on the R side in your htmlwidget, but this can cause occasionally cause other problems in certain contexts.

What I don't understand though is `highcharter` overrides the default `sizingPolicy` [here](https://github.com/jbkunst/highcharter/blob/806aa94d91339cad4866f5684656cec9c0afc422/R/highcharter.R#L58), so I would expect `resizeHandler` to work correctly.  Do you have the newest version of `highcharter` installed?

**Comment by Eflores89** [comment]
@timelyportfolio Thanks. I tried that but was running into more issues. Basically I updated the `htmlwidgets` to newest version (0.6) and it now seems to work fine. 

Not sure if I should close the issue just now as it should probably be placed as a dependency...

**Comment by jjallaire** [comment]
We've got this in our Imports statement in the DESCRIPTION:

htmlwidgets (>= 0.6)

So this should in theory be handled already.
