### ISSUE TITLE
navbar-right flex css

### ISSUE THREAD

**Issue by meztez** [rstudio/flexdashboard#316]
Using the latest bslib with flexdashboard, I believe the bootstrap css flex property for navbar messes with the navbar layout as it forces all flex elements to have the same width.

Reprex:
```Rmd
---
title: "Break Line"
author: "meztez"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    theme:
      version: 4
      bootswatch: cosmo
      primary: "#003366"
runtime: shiny_prerendered
---

Mercury
=====================================  

Venus
=====================================  

Earth
=====================================  

Mars
=====================================  

Jupiter
=====================================  

Uranus
=====================================  

Neptune
=====================================  

Pluto
=====================================  
```

![image](https://user-images.githubusercontent.com/31039074/111170569-7592ee80-857a-11eb-8a77-4c98fad59c3e.png)

![image](https://user-images.githubusercontent.com/31039074/111170679-93605380-857a-11eb-8bdc-0fbc266d3580.png)

Switching theme to cosmo still works fine

```Rmd
theme: cosmo
```

**Comment by cpsievert** [comment]
Thanks @meztez. Try installing https://github.com/rstudio/bslib/pull/286 for a tentative fix.

**Comment by meztez** [comment]
Tested it, looks fine.
