### ISSUE TITLE
navbar toggle is left aligned with Bootstrap 4+

### ISSUE THREAD

**Issue by meztez** [rstudio/flexdashboard#317]
Reusing the same example as last time

Mobile navbar-toggle is inconsistent when using bslib. I believe bslib is using the correct css, but the template put navbar-toggle first while bootstrap theme version 4 assume it comes before brand.

https://github.com/rstudio/flexdashboard/blob/9e810ba1b9e3c0dcaafd44003a6f6f7ca2bb7b21/inst/rmarkdown/templates/flex_dashboard/resources/default.html#L59

```html
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
```

Reprex
```r
---
title: "Break Line"
author: "meztez"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    theme:
      version: 4
      bootswatch: cosmo
runtime: shiny
---

Mercury
=====================================  

Venus
=====================================  

Earth
=====================================  

Mars
=====================================  

Jupiter
=====================================  

Uranus
=====================================  

Neptune
=====================================  

Pluto
=====================================  
```

![image](https://user-images.githubusercontent.com/31039074/111629932-2fcb6580-87c8-11eb-94ab-0cd3cc12f176.png)

![image](https://user-images.githubusercontent.com/31039074/111629319-8be1ba00-87c7-11eb-9979-34a729f228cd.png)

**Comment by cpsievert** [comment]
Are you asking for the BS4 navbar toggle to be on the right-hand side because that's how BS3 did it?

**Comment by cpsievert** [comment]
This is probably something that should be addressed more generally in bslib, so closing in favor of https://github.com/rstudio/bslib/issues/289
