### ISSUE TITLE
issues with calling another markdown from within flexdashboard

### ISSUE THREAD

**Issue by komalsrathi** [rstudio/flexdashboard#319]
I have a markdown file with flexdashboard output format and I need to call another markdown file from within, for example:

first.Rmd

    ---
    title: First
    output: 
      flexdashboard::flex_dashboard:
        orientation: rows
    ---
    
    ```{r load_libraries}
    library(rmarkdown)
    ```
    
    ```{r call_second_rmd}
    rmarkdown::render(input = 'second.Rmd', output_dir = "second_output", intermediates_dir = 'second_output')
    ```

second.Rmd (this is called from within first.Rmd):

    ---
    title: Second
    ---
    
    ## Plot
    ```{r test_plot}
    library(ggplot2)
    ggplot(data = mtcars, aes(mpg, cyl)) + geom_point()
    ```

I call the first markdown like this and expect **first.html** to be created under `first_output` and **second.html** under `second_output`:

    rmarkdown::render(input = "first.Rmd", output_dir = "first_output", intermediates_dir = "first_output")

However, the above command is giving me an error, second.html is created but first.html is not:

```
> rmarkdown::render(input = "first.Rmd", output_dir = "first_output", intermediates_dir = "first_output")


processing file: first.Rmd
  |..............................                                                                                          |  25%
  ordinary text without R code

  |............................................................                                                            |  50%
label: load_libraries
  |..........................................................................................                              |  75%
  ordinary text without R code

  |........................................................................................................................| 100%
label: call_second_rmd


processing file: second.Rmd
output file: /Users/rathik/Desktop/Tests/markdown/second_output/second.knit.md


Output created: second_output/second.html

output file: /Users/rathik/Desktop/Tests/markdown/first_output/first.knit.md

/usr/local/bin/pandoc +RTS -K512m -RTS /Users/rathik/Desktop/Tests/markdown/first_output/first.utf8.md --to html4 --from markdown+autolink_bare_uris+tex_math_single_backslash --output /Users/rathik/Desktop/Tests/markdown/first_output/first.html --lua-filter /Users/rathik/Library/R/4.0/library/rmarkdown/rmarkdown/lua/pagebreak.lua --lua-filter /Users/rathik/Library/R/4.0/library/rmarkdown/rmarkdown/lua/latex-div.lua --self-contained --variable bs3=TRUE --standalone --section-divs --template /Users/rathik/Library/R/4.0/library/flexdashboard/rmarkdown/templates/flex_dashboard/resources/default.html --variable theme=cosmo --include-in-header /var/folders/hs/dhj65y752djbrytfxzz6t13h35p24r/T//RtmpML2wn8/rmarkdown-str3af1c5dd15b.html --mathjax --variable 'mathjax-url:https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' --include-in-header /var/folders/hs/dhj65y752djbrytfxzz6t13h35p24r/T//RtmpML2wn8/file3af1635bb3b4html --include-before-body /var/folders/hs/dhj65y752djbrytfxzz6t13h35p24r/T//RtmpML2wn8/file3af116379da2.html --highlight-style pygments --include-before-body /var/folders/hs/dhj65y752djbrytfxzz6t13h35p24r/T//RtmpML2wn8/file3af119732162.html --include-after-body /var/folders/hs/dhj65y752djbrytfxzz6t13h35p24r/T//RtmpML2wn8/file3af15594b5fb.html 
pandoc: /Users/rathik/Desktop/Tests/markdown/second_output/second_files/figure-html/test_plot-1.mb.png: openBinaryFile: does not exist (No such file or directory)
Error: pandoc document conversion failed with error 1
```

Directory structure: (note that first_output folder is created but there is no first.html):

```
➜  pwd
/Users/rathik/Desktop/Tests/markdown

➜  tree .
.
├── first.Rmd
├── first_output
├── second.Rmd
└── second_output
    └── second.html

2 directories, 3 files
```

Sessioninfo:

```
> sessionInfo()
R version 4.0.4 (2021-02-15)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_3.3.3 rmarkdown_2.7

loaded via a namespace (and not attached):
 [1] highr_0.8           bslib_0.2.4         compiler_4.0.4      pillar_1.5.0        jquerylib_0.1.3     tools_4.0.4        
 [7] digest_0.6.27       jsonlite_1.7.2      evaluate_0.14       lifecycle_1.0.0     tibble_3.1.0        gtable_0.3.0       
[13] debugme_1.1.0       pkgconfig_2.0.3     rlang_0.4.10        DBI_1.1.1           yaml_2.2.1          xfun_0.21          
[19] withr_2.4.1         stringr_1.4.0       dplyr_1.0.4         knitr_1.31          generics_0.1.0      sass_0.3.1         
[25] vctrs_0.3.6         tidyselect_1.1.0    grid_4.0.4          flexdashboard_0.5.2 glue_1.4.2          R6_2.5.0           
[31] fansi_0.4.2         farver_2.0.3        purrr_0.3.4         magrittr_2.0.1      scales_1.1.1        htmltools_0.5.1.1  
[37] ellipsis_0.3.1      assertthat_0.2.1    colorspace_2.0-0    labeling_0.4.2      tinytex_0.29        utf8_1.1.4         
[43] stringi_1.5.3       munsell_0.5.0       crayon_1.4.1       
```

**Comment by cpsievert** [comment]
I think this is the proper way to do this sort of thing? https://bookdown.org/yihui/rmarkdown-cookbook/child-document.html

(Closing since I don't think this is a flexdashboard issue)

**Comment by komalsrathi** [comment]
@cpsievert Thanks for pointing this out. Is there documentation where you can call the child markdown from within an R script sourced from within the parent markdown? I am facing the same pandoc issue as above when I call render `first.Rmd`:

**first.Rmd**

    ---
    title: First
    output: 
      flexdashboard::flex_dashboard:
        orientation: rows
    ---
    
    ```{r load_libraries}
    library(rmarkdown)
    ```
    
    ```{r call_second_r}
    source('second.R')
    ```

**second.R**

```
# R script with markdown call
library(rmarkdown)
render(input = 'second.Rmd', output_dir = "second_output", intermediates_dir = 'second_output')
```

**second.Rmd**

    ---
    title: Second
    ---
    
    ## Plot
    ```{r test_plot}
    library(ggplot2)
    ggplot(data = mtcars, aes(mpg, cyl)) + geom_point()
    ```

**Comment by cderv** [comment]
Hi @komalsrathi, 

What are you trying to do exactly with this second document ? 
Do you want to include the result as part of the flexdashboard content ? 
Is this another document `second.Rmd` with another format ? 

What is the aim exactly ? 

This would help point you in the right direction. 

By the way, for help on broad usage of package, do not hesitate to ask on QA site like https://community.rstudio.com/c/R-Markdown/10
The community has a wide range of users ready to help, and some of them may have faced the same challenge as you. Or they could have new ideas to achieve your purpose.

**Comment by komalsrathi** [comment]
Hi @cderv 

I have a flexdashboard document (parent markdown), which creates a patient report by sourcing multiple R scripts and using the output tables/plots in the html report. One of those R scripts leverages an R package CEMitool that calls its own render function to generate a markdown and create a report (lets call it the child markdown). When I render the parent document, the child document's html is generated but the parent html fails to be generated because of the above pandoc error. The above is exactly a reproducible example of what I am trying to achieve.

I was trying to fix this issue since past many days, but yesterday found a workaround by using the callr::r function by running the CEMitool function that renders the child markdown in the background, something like this.  

```
r(function(x, y) { CEMiTool::generate_report(cem = x, directory = y, force = T) }, args = list(cem, cemitools_dir))
```

Thanks,
Komal

**Comment by cderv** [comment]
> I was trying to fix this issue since past many days, but yesterday found a workaround by using the callr::r function by running the CEMitool function that renders the child markdown in the background, something like this.

This is exactly what I would have advised now I understand that you are not trying to use what we are calling child document. By child document, we mean documents that are used to create content inside a main one. As explained in https://bookdown.org/yihui/rmarkdown-cookbook/child-document.html

you just want to call (indirectly) `rmarkdown::render()` within another `rmarkdown::render()` - using an another session in that case is the safest.
