### ISSUE TITLE
Mobile menu is incompatible with the Highcharter library

### ISSUE THREAD

**Issue by StefanMusch** [rstudio/flexdashboard#328]
**This is related to the [issue in the highcharter package](https://github.com/jbkunst/highcharter/issues/678).**

Hello,

I just ran into issues when I tried to use [highcharter ](https://github.com/jbkunst/highcharter) together with flexdashboard. More specifically, the burger icon in the navigation bar is not working in mobile mode.

![image](https://user-images.githubusercontent.com/24733935/115247083-c02dfa80-a126-11eb-9c33-581be51e515b.png)

The problem is that the jQuery version used in highcharter is not compatible with bootstrap - a css library used by flexdashboard. See the following links for more technical details

1. https://www.questionary.wiki/en/questions/software/bootstrap-cannot-convert-object-to-primitive-value
1. https://stackoverflow.com/questions/61176484/cannot-convert-object-to-primitive-value-error-in-react-application

Is there any way to downgrade or upgrade the jQuery version used by Flexdashboard, or any other method to make them compatible?

Repex:

```
---
output: flexdashboard::flex_dashboard
---

Info
=====================================     

```{r}
library(highcharter)
highchart(type = "stock") %>% 
  hc_add_series(AirPassengers)
``` 
```

**Comment by StefanMusch** [comment]
That's fantastic @cpsievert. Thank you for taking the time to take a look.

**Comment by srgmld** [comment]
> If you install the dev verison of flexdashboard, you can use Bootstrap 4, which seems to solve the issue:
> 
> ```
> ---
> output: 
>   flexdashboard::flex_dashboard:
>     theme:
>       version: 4
> ---
> ```
> 
> You can also read more about the new `theme` capabilities here https://flexdashboard-pkg.netlify.app/articles/theme.html

It sounds this is a solution when working with flexdashboard. However, do you have any suggestions when working with an rmarkdown site? The same problem occurs, the burger icon in the navigation bar is not working in mobile mode.

Thanks,

**Comment by StefanMusch** [comment]
Hi @srgmld the Version: 4 comes from the `bslib` package, which is also supported by R Markdown according to the Readme. So I think installing that and using it in your markdown documents can fix it: https://rstudio.github.io/bslib/

Let me know if that works.

**Comment by srgmld** [comment]
Thanks @StefanMusch, actually it did work. However, many elements of the document, including the navigation bar are deconfigured i.e. width. I think it will be just add some  css and html configurations.

**Comment by StefanMusch** [comment]
This could be because of the upgrade to version 4, however, even including `version: 3` fixed my issue, but didn't change the bootstrap content. You can try that too.

**Comment by srgmld** [comment]
My problem now is that, when including `version: 4` or `version: 3` the external css `css: style.css` is not being recognized. Even though the advanced theming section of `bslib` recomends to use the `css` parameter for aditional css rules.

Thanks for the suggestions.

**Comment by fyii200** [comment]
Hi @StefanMusch,
I am running into a similar issue (i.e., burger icon not working in mobile mode) so I tried to resolve the issue by installing the 'bslib' package and including Bookstrap 4 in my yaml code bit (see attached). However, I kept getting this error message: 

"Error in match.arg(theme, themes()) : 
  'arg' must be NULL or a character vector
Calls: <Anonymous> ... withCallingHandlers -> <Anonymous> -> <Anonymous> -> base -> match.arg
Execution halted"

Could you please help? Many thanks!
![Screenshot 2021-05-23 at 19 37 42](https://user-images.githubusercontent.com/72454128/119259017-ca985400-bbfe-11eb-92d1-6a18056e2cc3.png)

**Comment by fyii200** [comment]
> Hi @StefanMusch,
> I am running into a similar issue (i.e., burger icon not working in mobile mode) so I tried to resolve the issue by installing the 'bslib' package and including Bookstrap 4 in my yaml code bit (see attached). However, I kept getting this error message:
> 
> "Error in match.arg(theme, themes()) :
> 'arg' must be NULL or a character vector
> Calls: ... withCallingHandlers -> -> -> base -> match.arg
> Execution halted"
> 
> Could you please help? Many thanks!
> ![Screenshot 2021-05-23 at 19 37 42](https://user-images.githubusercontent.com/72454128/119259017-ca985400-bbfe-11eb-92d1-6a18056e2cc3.png)

Just resolved the issue after installing the development version of Flexdashboard!
