### ISSUE TITLE
A great resource

### ISSUE THREAD

**Issue by RenatoPdosSantos** [rstudio/flexdashboard#33]
Thank you very much for this wonderful package.

My Rmd code generates two tables which are a little too long for one slide.

I searched in vain for a solution to have the tables properly shown in Slidify without success.

When I brought the code into flexdashboard, the problem was instantly solved as it provides a convenient scrolling layout.

Besides, having the tables available through a set of two tabs is also an elegant solution.

Great work!

**Comment by jjallaire** [comment]
Thanks!
