### ISSUE TITLE
layouts page not found

### ISSUE THREAD

**Issue by cmatKhan** [rstudio/flexdashboard#339]
It looks like the site is undergoing some development, so I'm sure this will be resolved in its own time. But, I rely heavily on the layout examples and look forward to this page working again:

https://pkgs.rstudio.com/flexdashboard/articles/articles/layouts.html

Currently, it leads to a 'page not found' 404 error

**Comment by cderv** [comment]
Thanks for the report. 

The working link is https://pkgs.rstudio.com/flexdashboard/articles/layouts.html that you can access in the navbar under Articles. 

Where did you get this 404 link ? It was the old one when the site was being under work. If you found this link on the web, we're interested by changing it. Thanks !

**Comment by cmatKhan** [comment]
It is in the section "learning more" at the bottom of this page:

https://pkgs.rstudio.com/flexdashboard/articles/flexdashboard.html

Thank you for pointing me towards the working link -- much appreciated
