### ISSUE TITLE
flexdashboard not rendering reactive data object via DT::renderDataTable

### ISSUE THREAD

**Issue by missymorrow** [rstudio/flexdashboard#34]
This problem is specific to flexdashboard. 

I have developed some shiny UI in which a reactive data object is used as the data argument inside of `renderDataTable` function.  This works fine in a Shiny environment, however if I try this UI within Flexdashboard, I cannot see the contents of my data object. If I switch from `DT::renderDataTable` to just `DT::DataTable` everything works fine. So this is making me think that there is some issue with Flexdashboard trying to render reactive data objects. Here's a minimal reproducible example

               ```
                ---
               title: "Flex Dashboard"
               output: 
               flexdashboard::flex_dashboard:
               orientation: columns
              vertical_layout: fill
              runtime: shiny
             ---

            ```{r setup, include=FALSE}
               library(rmarkdown); library(knitr); library(DT)
            ```
 
          ```{r}
                  DT::renderDataTable({iris},
                  options = list(
                  pageLength = 5,
                  initComplete = I("function(settings, json) {alert('Done.');}")
                )
           )
          ```
```

**Output : Empty**,  now replacing `DT::renderDataTable` with `DT::DataTable` 


      ```
      ---
      title: "Flex Dashboard"
      output: 
      flexdashboard::flex_dashboard:
      orientation: columns
      vertical_layout: fill
      runtime: shiny
      ---

      ```{r setup, include=FALSE}
        library(rmarkdown); library(knitr); library(DT)
      ```
  
      ```{r}
                 DT::datatable(iris,
                 options = list(
                  pageLength = 5,
                  initComplete = I("function(settings, json) {alert('Done.');}")
                )
             )
     ```
```



![test1](https://cloud.githubusercontent.com/assets/19525272/15525120/bd2f3b50-21ec-11e6-9621-a253abe70140.png)

**Comment by jjallaire** [comment]
I fixed the issue here: https://github.com/rstudio/DT/commit/766922829b7618f8bd3a2d0acbd85a0be2d00cf9

**Comment by missymorrow** [comment]
JJ I am not sure why I am seeing this in my output and not the actual
contents of the datatable

function (shinysession, name, ...)

{

    currentSession <<- shinysession

    currentOutputName <<- name

    on.exit({

        currentSession <<- NULL

        currentOutputName <<- NULL

    }, add = TRUE)

    renderFunc()

}

<environment: 0x0000000008500f80>

attr(,"class")

[1] "shiny.render.function" "function"

attr(,"outputFunc")

function (outputId, width = "100%", height = "auto")

{

    htmlwidgets::shinyWidgetOutput(outputId, "datatables", width,

        height, package = "DT")

}

<environment: namespace:DT>


Here's the code I am using to test renderDataTable in Flexdashboard

---

title: "Untitled"

output:

  flexdashboard::flex_dashboard:

    orientation: columns

    vertical_layout: fill

    runtime: shiny

---


```{r setup, include=FALSE}

library(flexdashboard)

library(DT)


```



```{r, echo=FALSE}


DT::renderDataTable({

      mtcars

    })


```

**Comment by jjallaire** [comment]
I can't repro this problem. Maybe try updating all the versions of your
packages (shiny, htmlwidgets, etc.)

**Comment by missymorrow** [comment]
Thanks JJ, I think this is an issue with my code. You are absolutely right.
Thanks as always :)

**Comment by jjallaire** [comment]
No problem!

**Comment by missymorrow** [comment]
JJ,

When I select a specific row from the Datatable the contents of that row
are not automatically populated in the input elements for editing or delete
operation.

I have posted this problem in two different places.

http://stackoverflow.com/questions/37495114/observeevent-for-row-selection-in-flexdashboard

https://github.com/rstudio/DT/issues/300


I dont know if this is an issue with javascript underneath the datatable or
flexboard issue or simply due to my incorrect code.

Could you please take a look at this at your earliest convenience and give
me some feedback.

Thanks as always JJ.

~Missy May

**Comment by missymorrow** [comment]
JJ,

Another issue while recreating a shiny app in Flexdashboard. I have posted
this problem is multiple places

https://github.com/rstudio/DT/issues/300

https://github.com/rstudio/DT/issues/300

I dont know if this is due to Flexdashboard because in shiny this works
fine, or due to the underlying javascript in Datatable not working in
Flexdashboard or simply an error in my code.  Your feedback is much
appreciated.
