### ISSUE TITLE
DT::datatable() issue with container

### ISSUE THREAD

**Issue by stvrd** [rstudio/flexdashboard#341]
Not sure if issue #321  is resolved. With DT-0.18, the following simple flexdashboard shows a box too small to properly show the datatable.

With DT-0.13, the box adapts and shows a nice datatable. Any ideas how to solve this?

```
---
title: "mytitle"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
---
  
```{r}
DT::datatable(mtcars)
```'
```

**Comment by cpsievert** [comment]
You probably need the development version of flexdashboard (`remotes::install_github("rstudio/flexdashboard")`)?

**Comment by stvrd** [comment]
Of course! Thank you :)
