### ISSUE TITLE
Can !important be removed from htmlwidget CSS?

### ISSUE THREAD

**Issue by MilesMcBain** [rstudio/flexdashboard#351]
This kind of practice makes downstream styling customisations hard:

https://github.com/rstudio/flexdashboard/blob/8417d674f97574d1198f17a39bbae971ad727356/inst/www/flex_dashboard/flexdashboard.scss#L310-L313

In my case, I have a htmlwidget that is actually a set of controls for another widget, it has an appropriate default height that gets trumped by this, and I can't override this behaviour with a custom CSS file supplied to {flexdashboard}.

I am going to try to update my widget to include some inline CSS but it's a bit of a yak shave.

**Comment by cpsievert** [comment]
I agree that in theory the `!important` shouldn't be there, but it's been there for many years and changing it now seems like more risk than reward.

> I can't override this behaviour with a custom CSS file supplied to {flexdashboard}.

Are you sure you can't override it? At least with statically rendered Rmd I've confirmed that this works:

```css
.chart-stage .html-widget {
  width: 100% !important;
  height: 300px !important;
}
```

````yaml
---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    css: styles.css
---

```{r setup, include=FALSE}
library(flexdashboard)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
library(plotly)
plot_ly()
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
plot_ly()
```

### Chart C

```{r}
plot_ly()
```
````

If you're trying to do this with a `shiny` or `shiny_prerendered` runtime, you'll probably want the dev version of `{flexdashboard}`

**Comment by MilesMcBain** [comment]
I have two different widgets. For one the 100% default was fine, the other it was too large. If I use that CSS it will set the size for both right?

Both the widgets have different classes. So when I tried to use their htwmlwidget class to set the height like this:

```
.rdeckControls {
	height: 2em !important;
}
```

It was trumped by the !important rules already defined for  `.chart-stage ` and `.html-widget`.

I guess like anything that is being held back by being legacy it would make sense to use a deprecation message and allow an option to change the behaviour to something better that would become the default in the future.

I suspect it might not be a huge problem with these dashboards, because if people expect these to stand the test of time, they will of will have been forced to control their package environment with `{renv}` or similar by other upstream changes.

**Comment by gadenbuie** [comment]
My guess is that `!important` might be used in cases where the htmlwidget author could have set the element height using the htmlwidget's ID, in which case `!important` would be required to override the specificity of an ID selector. I think this is a reasonable approach: most people in most cases in flexdashboard will want the htmlwidget to fill the  vertical space in a box. If `height` is set to an absolute value, the htmlwidget will overflow the box when its shorter than that value, and the the overflow will be clipped. That's probably not what most people want.

There are a few other ways to resolve this using CSS and taking advantage of specificity rules or other properties. My first recommendation would be to set the `max-height` property for the htmlwidgets you're using. This is most likely to apply globally and work well within flexdashboard.

```css
.rdeckControls {
  max-height: 2em;
}
```

Note that you don't need `!important` on this rule. A slightly unintuitive thing about the `height: 100% !important` property value is that `!important` isn't **forcing** the height to be `100%`, it's forcing the `height: 100%` property to be applied in situations where the CSS specificity wouldn't allow it to be applied. When `height: 100%` is combined with a `max-height` property, e.g.

```css
#my-widget {
  height: 100%;
  max-height: 300px;
}
```

they work together to keep `#my-widget` at 100% height _until_ it hits 300px tall.

This points out another reason why `!important` might be the right call on this property. While `!important` pushes the property to apply in places where the rule's CSS specificity wouldn't allow it to be used, `.chart-stage .html-widget` has reasonably low specificity, so it's possible to override it easily with a more specific rule (that also has to use `!important`). 

Using Carson's example, you can give the Chart B plot a different height using this rule:

```css
#chart-b .html-widget {
  height: 300px !important;
}
```

This works great, as long as the containing box is 300px tall or more

![Untitled](https://user-images.githubusercontent.com/5420529/222171125-2e780584-6dfe-4f08-a26b-b76f56112101.png)

but when the box is 300px or smaller, the contained widget will clip.

![Untitled](https://user-images.githubusercontent.com/5420529/222171431-eb030aa7-29fb-4847-accc-925759def79e.png)

Finally, if you're having to do this in many places but want to be more careful about which widgets you're modifying, you can give the box or column or row a CSS class

````markdown

### Chart C {.constrained-height}

```{r}
plot_ly()
```
````

and then use that class in your CSS rules

```css
.constrained-height .chart-stage .html-widget {
  height: 300px !important;
}
```
