### ISSUE TITLE
[Feature Request] Is there a way to have one of the tabs a regular Rmarkdown document?

### ISSUE THREAD

**Issue by RayLarone** [rstudio/flexdashboard#353]
Flexdashboard is an amazing R package. It enables you to create awesome dashboards very quickly. I use it all the time. One thing I always seem to want is a tab (e.g. an "about" tab) which includes a report explaining the dashboard with the format of a regular Rmarkdown document.

Is there a way for one of the tabs in flexdashboard to act as a regular Rmarkdown document, rather than a dashboard formatted one?

Many thanks, and keep up the good work :)

![image](https://user-images.githubusercontent.com/87857081/126769960-fe6c2199-dcdf-4500-8826-9ac43956c044.png)

**Comment by cpsievert** [comment]
(Feel free to reopen the issue if this approach doesn't end up working for you)
