### ISSUE TITLE
Embedding tweets in Flexdashboard storyboard

### ISSUE THREAD

**Issue by ayushnoori** [rstudio/flexdashboard#354]
Hi there,

I am using Flexdashboard to create a [web dashboard](https://www.ayushnoori.com/covid19-nlp/#topics) for my project at https://github.com/ayushnoori/covid19-nlp. In each storyboard frame under the Topics page, I would like to embed certain tweets as described at https://help.twitter.com/en/using-twitter/how-to-embed-a-tweet. I am using `htmltools::includeHTML()` to do so. For example, if I wanted to embed [this tweet](https://twitter.com/Twitter/status/1407421738305077253), I write:

```{r}
htmltools::includeHTML("topics/topic-3.html")
```
Where `topics/topic-3.html` is:
```{html}
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">pls stop posting screenshots of Tweets on IG Stories. you can now share Tweets directly on iOS. <br><br>-management <a href="https://t.co/wpjnElsRTK">pic.twitter.com/wpjnElsRTK</a></p>&mdash; Twitter (@Twitter) <a href="https://twitter.com/Twitter/status/1407421738305077253?ref_src=twsrc%5Etfw">June 22, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<br>
```
However, the resulting tweet is not styled and the media items (e.g., photos, videos, conversations) are not visible. I must add my own custom CSS to approximate the Twitter styling.

I have noticed that removing the `script` at the end (`<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>`) does not change the styling, hence I suspect this is the culprit? I would be grateful for any guidance on how to successfully source the Twitter embed widget. Thanks.

P.S. [Here](https://github.com/ayushnoori/covid19-nlp/blob/main/docs/COVID%20NLP%20Dashboard.Rmd) is my full-length Markdown file in case that may be helpful.

**Comment by ayushnoori** [comment]
Thanks, @cpsievert. Is there any good documentation for `htmltools::tags$iframe()`? A 1:1 replacement with `includeHTML()` produces the following rather than the expected tweets:

![image](https://user-images.githubusercontent.com/43010710/134100739-91d04e95-c779-4b4a-bd24-abe49c0082fb.png)

I can't seem to find much information on `tags:iframe()` other than [this SO post](https://stackoverflow.com/questions/63406208/displaying-html-file-using-htmltoolstagsiframe-in-shiny-is-not-working-with-r), and not in the `htmltools` documentation [here](https://www.rdocumentation.org/packages/htmltools/versions/0.5.2). Please let me know if you have any tips. My usage is as follows:

```
Topics {.storyboard data-icon="fa-file-alt"}
=====================================

### Topic 3: mask, wear, still, social, distanc, peopl, keep {data-commentary-width=400}

/```{r}
htmltools::tags$iframe("topics/topic-3.html")
/```
```
where previously, I had `includeHTML()` instead of `tags$iframe`.

**Comment by deadfate-sky** [comment]
same question here
