### ISSUE TITLE
NO full height when using ggplotly

### ISSUE THREAD

**Issue by MAGALLANESJoseManuel** [rstudio/flexdashboard#355]
I do not why my ggplotly output does not occupy the whole plot area!
![image](https://user-images.githubusercontent.com/7110381/129606582-7ca26db5-141d-49ba-9d2d-84ee1826a890.png)

**Comment by lz100** [comment]
```r
plotlyOutput(
  outputId,
  width = "100%",
  height = "400px",
  inline = FALSE,
  reportTheme = TRUE
)
```
plotlyOutput by default has a fixed height of 400px, of course it will not take the whole height. Change it to `100%` may help (never tested it).

**Comment by cpsievert** [comment]
Closing due to lack of a reproducible example.
