### ISSUE TITLE
valueBox href not working with costum hex-color

### ISSUE THREAD

**Issue by alf-ken** [rstudio/flexdashboard#356]
Hi,

I ran into an odd bug. Using valueBox with a costum color results in breaking href option. I'm using flexdashboard version 0.5.2.9000.

![2021-08-20 12_55_43-H__R_flex_href html](https://user-images.githubusercontent.com/72913399/130223284-efee7927-ac97-4c2c-9e59-ce0482345e82.png)

---
title: "Themed dashboard"
output: 
  flexdashboard::flex_dashboard
---

```{r setup, include=FALSE}
library(flexdashboard)
# Install thematic and un-comment for themed static plots (i.e., ggplot2)
# thematic::thematic_rmd()
```

Page 1
===================================== 

### Box1
```{r, fig.width=2.5}
valueBox("Click", caption = "Click to Page 2", href = "#page-2", color = "primary")
```

### Box 2
```{r, fig.width=2.5}
valueBox("Click", caption = "Click to Page 2", href = "#page-2", color = "#F39200")
```

Page 2
===================================== 

Column {data-width=650 .tabset}
-----------------------------------------------------------------------

### Chart A

```{r}

```

### Chart B

```{r}

```

**Comment by cpsievert** [comment]
Thanks for the report, should be fixed now!

**Comment by alf-ken** [comment]
THX!
