### ISSUE TITLE
Possible bug:  flexdashbord::gauge's label in shiny application with reactive data

### ISSUE THREAD

**Issue by gioneves** [rstudio/flexdashboard#357]
I would like the gauge label to change when the value changes.

I created the `f_3` function to try to adjust this, but not succeed.

 `rmarkdown` code:

    ---
    title: "Label of gauge"
    runtime: shiny
    output: 
      flexdashboard::flex_dashboard:
        orientation: rows
        vertical_layout: fill
        theme: yeti
    ---

    side{.sidebar}
    -------------------------------------------

    ```{r}
    library(tibble)
    library(shiny)
    library(shinyWidgets)
    library(flexdashboard)
    ```

    **Analysis**

    ```{r}
    autonumericInput(
        inputId = "a", 
        value = 10, 
        label = "Value 1", 
        align = "center", 
        currencySymbol = "$", 
        currencySymbolPlacement = "p",
        digitGroupSeparator = ".",
        decimalCharacter = ",", 
        decimalPlaces = 0, 
        minimumValue = 0, 
        maximumValue = 100
    )

    autonumericInput(
        inputId = "b", 
        value = 10, 
        label = "Value 2", 
        align = "center", 
        currencySymbol = "R$", 
        currencySymbolPlacement = "p", 
        digitGroupSeparator = ".",
        decimalCharacter = ",", 
        decimalPlaces = 0, 
        minimumValue = 0, 
        maximumValue = 100
        )
    ```

    ```{r}
    f_1 <- function(a, b) {
      a + b
    }

    reac <- reactive({
      tibble(
        a = input$a, 
        b = input$b
      )
    })

    pred <- reactive({
      temp <- reac()
      f_1(
        a = input$a, 
        b = input$b
      )
    })
    ```

    abc{}
    --------------------------------------

    ###
    ```{r}
    f_3 <- function(x) {
      if (x <= 40) {
        "Danger"
      } else if (x <= 80) {
        "Warning"
      } else ("Success")
    }

    renderGauge({
      gauge(
        value = round(x = pred(), digits = 0), min = 0, max = 100, symbol = "%", 
        label = f_3(x = pred())
        )
    })
    ```
The label's value always appears as `Danger`, even when the value changes. 

This question was answered [here](https://stackoverflow.com/questions/69013336/how-change-flexdashbordgauges-label-in-shiny-application-with-reactive-data/69021155#69021155), I just wanted to know why this happened? Was it a bug?

**Comment by cpsievert** [comment]
I think the development version has a fix for this `remotes::install_github("rstudio/flexdashboard")`? Let me know if it's still broken after updating
