### ISSUE TITLE
Narrowing flexdashboard window causes one graph to overwrite all others

### ISSUE THREAD

**Issue by Henry-E** [rstudio/flexdashboard#36]
If you knit this script and narrow the window horizontally enough, it will cause the final graph to appear over all the others.

```
---
title: "Testing flexdashboard issues"
output:
 flexdashboard::flex_dashboard
---

```{r, results="asis"}
library(ggplot2)
level1MarkdownHeader <- "\n==================\n"

for(i in 1:3){
  cat("\n\nHeading")
  cat(level1MarkdownHeader)
  for(j in 1:2){
    x <- qplot(y = 1:10, x = rnorm(10), colour = I(colours()[sample(1:655, 1)]))
    print(x)
  }
}

```

**Comment by jjallaire** [comment]
The problem here is that we are doing special per-chunk processing to create mobile versions of figures. I think for this code you should just disable this feature via `fig_mobile: false`

**Comment by Henry-E** [comment]
Perfect, thanks.

A secondary issue I've noticed which is probably more of a javascript formatting problem. When narrowing the window, if there's a lot of different page titles and also headings for each graph, the page titles will drop down to a new line, covering up part of the top graph. At least until the window gets too narrow and they end up in the burger menu thing. 

```
---
title: "Testing flexdashboard issues"
output:
 flexdashboard::flex_dashboard
---

```{r, results="asis"}
library(ggplot2)
level1MarkdownHeader <- "\n==================\n"
newLine <- "\n"
headerThree <- "### "

for(i in 1:7){
  cat("\n\nHeading")
  cat(level1MarkdownHeader)
  for(j in 1:2){
    cat(
      newLine,
      newLine, headerThree, "figureName ",
      newLine,
      newLine, sep=""
    )
    x <- qplot(y = 1:10, x = rnorm(10), colour = I(colours()[sample(1:655, 1)]))
    print(x)
    cat("\n")
  }
}
```

**Comment by jjallaire** [comment]
Yes, that's a known issue with the page titles (it effectively caps the number pages you can have in the navigation bar). Note you can also use menus to organize lots of pages: http://rmarkdown.rstudio.com/flexdashboard/using.html#page_navigation
