### ISSUE TITLE
No reference to spaces as special characters in page attributes

### ISSUE THREAD

**Issue by erm-eanway** [rstudio/flexdashboard#372]
Spaces in page attributes (a.k.a. class attributes) fail silently while knitting. I can't find any references that mention that spaces are special characters in page attributes or that spaces should not be included before or after the equal sign in page attributes. I think this issue is specific to flexdashboard rather than e.g. RMarkdown or knitr because it's related to flexdashboard documentation. Does this documentation exist and, if so, could it be more apparent?

Other related questions include: 
- [Flexdashboard multiple attributes page](https://stackoverflow.com/questions/47712019/flexdashboard-multiple-attributes-page); multiple attributes are needed but there's no reference stating how the attributes should be delimited.

Related references include:
- [RMarkdown - Attributes on Sections](https://bookdown.org/yihui/rmarkdown/layout.html#attributes-on-sections)
- [Flexdashboard - Page Navigation](https://rstudio.github.io/flexdashboard/articles/using.html#page-navigation-1)

# MWE
```
---
title: "Page Navigation Menus"
output: flexdashboard::flex_dashboard
---

Page 1 {data-navmenu="Menu A"}
=====================================


Page 2 {data-navmenu= "Menu A"} <!-- page attribute contains a space and fails silently -->
=====================================  


Page 3 {data-navmenu="Menu B"}
=====================================


Page 4 {data-navmenu="Menu B"}
===================================== 
 ```

**Comment by gadenbuie** [comment]
Thanks for the question! These attributes are actually part of pandoc's [header attribute syntax](https://pandoc.org/MANUAL.html#extension-header_attributes). I agree that they could be called out more clearly in our documentation. After a quick scan I think the best place might be in the [Using flexdashboard article](https://rstudio.github.io/flexdashboard/articles/using.html#tabsets-1) at the end of the Tabset section, which is the first place where header attributes are used – and they actually show multiple attributes in use at the same time with `{.tabset .tabset-fade}`.
