### ISSUE TITLE
Way to tell init javascript to ignore contents of div?

### ISSUE THREAD

**Issue by richarddmorey** [rstudio/flexdashboard#373]
I have an app that writes rendered rmarkdown (as HTML) into a shiny uiOutput. This HTML contains tags that the flexdashboard init javascript uses to structure the page (e.g. divs of class "section level2") just because of how it is rendered. Normally, this is not a problem, because the content is filled by shiny AFTER the init script is run, which means it renders as intended.

I'm now trying to build a "static" (non-shiny) version of the same page. Consider the following script:

````
---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```

Column {.sidebar}
-----------------------------------------------------------------------

### Sidebar

sidebar

Column 
-----------------------------------------------------------------------

### Chart B

Top

### Chart C

```{r}

h = '<div class = "section level1">text0</div>text1<div class = "section level2">text2</div><div class = "section level3">text3</div>text4'

htmltools::tags$div(htmltools::HTML(h))
```
````

When this is compiled, the flexdashboard init script screws up the page format (I think) because it sees the `level1`, `level2`, etc divs in `h` as things to be moved around. I do not want flexdashboard to mess with that html. Is there a way to achieve this?

Things I've tried:

* iframe: doesn't work because I want the HTML to be styled using the parent page's css
* javascript: I've tried passing the html as a base64 encoded string, which is then decoded and put into the appropriate div. I know this works if I can delay this until AFTER the flexdashboard init runs. However, I don't have an elegant way of doing this. If I inlcude the decoding script in a script tag to run on document ready, it gets run before the init by default (I guess it is queued up first?). I can use setTimeout() to delay the content replacement until after the flexdashboard init, but this is very inelegant (and potentially error-prone).

Is there a class I can set on the containing div can set to make flexdashboard init ignore the contents? Or a way to queue up my decoding script to run immediately after flexdashboard init?

Thanks!

**Comment by gadenbuie** [comment]
Unfortunately, those classes are quite important for flexdashboard's layout algorithm, so they can't be present in the DOM until after flexdashboard has initialized its layout. Fortunately, there's a jQuery event that indicates when this has happened called `flexdashboard:layoutcomplete`. You can include some JavaScript that listens for this event and executes after it has occurred using code like this:

```js
$(document).on('flexdashboard:layoutcomplete', function() {
  // add elements after the re-layout has finished
})
```

Putting this together with your example, you can add a placeholder `<div>` in your dashboard's source and then use the snippet above to add the contents _after_ relayout has happened.

````markdown
h = '<div class = "section level1">text0</div>text1<div class = "section level2">text2</div><div class = "section level3">text3</div>text4'

htmltools::tagList(
  htmltools::tags$div(id = "replace-me"),
  htmltools::tags$script(htmltools::HTML(
    sprintf("
$(document).on('flexdashboard:layoutcomplete', function() {
  $('#replace-me').html('%s')
})",
      h
    )
  ))
)
````

(Just be careful that you might need to worry about escaping `'` string delimiters.)
