### ISSUE TITLE
Redirect gh-pages to pkgs.rstudio.com/flexdashboard

### ISSUE THREAD

**Issue by IndrajeetPatil** [rstudio/flexdashboard#377]
https://rstudio.github.io/flexdashboard/

![image](https://user-images.githubusercontent.com/11330453/143688533-3f1b90ff-d8f6-492f-938c-96be73fab8a9.png)

**Comment by cderv** [comment]
Thanks for the report. I was puzzled by this but now I understand. 

The new site is now located at https://pkgs.rstudio.com/flexdashboard/ where you'll see that it works correctly. 

Previously the known url was https://rmarkdown.rstudio.com/flexdashboard which still works and redirect to the new site on netlify.

Where did you found this URL ? We should change it if it still lives somewhere. 
We may also need to remove / redirect the github pages. @cpsievert what do you think ? 

FWIW I think there was an action work in May that auto-build the new site according to the commit history: https://github.com/rstudio/flexdashboard/commits/gh-pages and it was probably not expected.

**Comment by IndrajeetPatil** [comment]
> Where did you found this URL ? We should change it if it still lives somewhere.

I was redirected to that website from here: https://rmarkdown.rstudio.com/gallery.html

![image](https://user-images.githubusercontent.com/11330453/143876529-60f45b9a-cad7-45b1-8c98-df85d10a0d9f.png)

**Comment by cderv** [comment]
Thanks a lot!  I'll modify the link there. 

So hard to keep track of all the links when we do such changes!

**Comment by gadenbuie** [comment]
We still need to add a redirect in the `gh-pages` branch of this repo that redirects users to https://pkgs.rstudio.com/flexdashboard.

**Comment by gadenbuie** [comment]
Fixed in #427
