### ISSUE TITLE
Icon in data-navmenu

### ISSUE THREAD

**Issue by ambarja** [rstudio/flexdashboard#383]
Hello everyone, Is possible add a new icon in data-navmenu? Personally, I put the next code :point_down: 
```
Exposición {data-navmenu='<img src="data/covid.png" width="18px">Riesgo por COVID-19' data-icon='fa-list'}
```
but it return error, however when I create a new page section and I put this html code `<img src=""> TITLE` , si display it the image.
Here I added some images
![icon](https://user-images.githubusercontent.com/23284899/149872565-d4a96343-8f81-4a00-b339-21e58bade6bb.png)
![icon2](https://user-images.githubusercontent.com/23284899/149872579-305271dc-ec18-4f97-8910-a334761cca0e.png)

**Comment by DavidRoncal** [comment]
Hi Antony, you just have to put the path of your icon before the title in this way: 
![image](https://user-images.githubusercontent.com/71480596/153784053-37d9bae2-f2a0-4852-b330-1a6c665a3e09.png)
Greetings

**Comment by DavidRoncal** [comment]
![image](https://user-images.githubusercontent.com/71480596/153784173-07f725b9-c788-4971-8631-165f67a17e68.png)

**Comment by vkatti** [comment]
I think we do it as below:

````
---
title: "MyDashboardTitle"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    logo: "path/to/logo.png"
    theme: cosmo
    navbar:
      - {title: "Last Updated at 19-04-2022", align:right}
---
```{r setup, include=FALSE}
library(flexdashboard)
```

# Home {data-icon="fa-home"}

This is Home

# Stats {data-icon="fa-chart-pie"}

This is Stats
````

**Comment by whv20** [comment]
I think @ambarja is referring to adding an icon to a heading on the navigation bar that when clicked brings up a drop down menu.

When you want a page to appear directly on the navigation bar, @vkatti 's solution works perfectly :) 

```
# Section 1 {data-icon="fa-home"}

Some content

# Stats {data-icon="fa-chart-pie"}

Some more stuff
```

![image](https://user-images.githubusercontent.com/118453625/211604974-96bb59c5-f2cf-48c8-acd5-fdd5a9b3cf7b.png)


But if you want to nest several pages in a sub-menu (using data-navmenu="Submenu name"), it doesn't seem to be possible to give the submenu's title an image:

```
# Section 1  {data-icon="fa-home"}

Section 1 is accessed via a button which appears directly on the navigation bar

# Section 2 {data-icon="fa-chart-pie" data-navmenu="Topics"}

Section 2 is accessed via a submenu entitled 'Topics'

# Section 3 {data-icon="fa-info" data-navmenu="Topics"}

Section 3 is also accessed via a submenu entitled 'Topics'
```

![image](https://user-images.githubusercontent.com/118453625/211606608-13c28e93-24a3-44f6-9a13-1243a0d7089d.png)


Together with @ambarja , I would very much like to be able to add an icon to these drop down menu headings (in the example above, I would want 'Topics' to have an icon next to it). Does anyone know if this is possible? If not, please could you consider it for a future update of flexdashboard? Thank you :)

**Comment by whv20** [comment]
Thanks @vkatti , this is a very helpful workaround :) Do you know if it's possible to make the emojis blue and white, like icons would be?

**Comment by vkatti** [comment]
FontAwesome icons conforms to the font color and size as needed. Check out this Stackoverflow link about the same.
https://stackoverflow.com/questions/17254339/font-awesome-unicode
