### ISSUE TITLE
flexdashboard remote installation failed for R V 4.1 on ubuntu 18.04.5

### ISSUE THREAD

**Issue by abiyug** [rstudio/flexdashboard#384]
Attempted to remote install the development version  of flexdashboard on Ubuntu running R v 4.1.x and get an *_error in utils_*. The installation goes without problem on OSx with R v 3.6.x

**OS Version**
`> sessionInfo()
R version 4.1.0 (2021-05-18)  
Platform: x86_64-pc-linux-gnu (64-bit)  
Running under: Ubuntu 18.04.5 LTS  
`

**REPREX**
`> remotes::install_github('rstudio/flexdashboard')

Downloading GitHub repo rstudio/flexdashboard@HEAD  
Error in utils::download.file(url, path, method = method, quiet = quiet,  :   
  download from 'https://api.github.com/repos/rstudio/flexdashboard/tarball/HEAD' failed  
`

**Comment by gadenbuie** [comment]
I'm hoping this was a temporary issue, either with GitHub or your internet connectivity. If you're still running into this issue, please let us know!
