### ISSUE TITLE
Flexdashboard animation controls

### ISSUE THREAD

**Issue by DavisDeRodesLooma** [rstudio/flexdashboard#386]
Hello!

Currently in flexdashboard, I've noticed that the highcharter animation settings are overridden. 

[Here's a .Rmd](https://rstudio.theloomaproject.com/content/803/Untitled.html) with highcharts with different animation settings (one has animations turned off and the other has a very long animation time). 

[Here's a flexdashboard](https://rstudio.theloomaproject.com/content/804/ReprexFlex.html) with the exact same graphs. 

I also noticed that there's still a sort of animation of the graphs expanding to their size with flexdashboard and was wondering if it was controllable. 

Thanks!

**Comment by DavisDeRodesLooma** [comment]
I had an out-of-date version of .Rmarkdown, which was causing the issue with the highcharter animations, but I still would be curious if there was a way to control the flexdashboard animation of graphs expanding into their flexdashboard areas?

Thanks!

**Comment by gadenbuie** [comment]
Hi @DavisDeRodesLooma and thanks for the question – I'm glad your original issue was resolved easily by updating rmarkdown. My guess is that the expansion animation comes from logic in highcharter around resizing the widget elements. Your best bet will be to ask the highcharter developers to find out if you can control that animation.
