### ISSUE TITLE
Gauges labels are cut off if more than one line (development version)

### ISSUE THREAD

**Issue by kate-chalmers** [rstudio/flexdashboard#388]
[](https://i.stack.imgur.com/rRhAy.png)I have built an app that is heavily dependent on gauges to track progress. There was an issue with the label not updating with new input so I have updated my version of flexdashboard to the development version: remotes::install_github("rstudio/flexdashboard").

However, now I have done this the labels of all my gauges are cut off if they are more than one line. See the screenshot below:
<img width="281" alt="gauges" src="https://user-images.githubusercontent.com/74201925/160825879-ddbd4116-2e0f-4012-abcd-eeb45e515b58.png">

I have tried to change the height/width of the column, div and svg using css, but I do not want the gauges larger and that is the only solution that has worked.

I've included below a reprex:

```
library(shiny)
library(flexdashboard)

ui <- fluidPage(
  column(12, gaugeOutput("gauge1")),
  column(12, gaugeOutput("gauge2"))
)

server <- function(input, output) {
  
  output$gauge1 <- renderGauge({
    gauge(15, min=0, max=100, label="Line 1\n Line2")
  })
  
  output$gauge2 <- renderGauge({
    gauge(25, min=0, max=100, label="Line 1\n Line2")
  }) 
}

shinyApp(ui = ui, server = server)

```

**Comment by cpsievert** [comment]
Thanks! This should be fixed now.
