### ISSUE TITLE
Problems visializing sincroniuc multiple maps using tmap in flexdasboard that doesn't happen  when using html

### ISSUE THREAD

**Issue by PauGallesClara** [rstudio/flexdashboard#391]
Hi !
I've created and interactive map with tmap and leaflet and i want to compare different variables. 
When I use Rmarkdown woth the output html I get the sincronyc maps as it is shwon in the screenshot1. Here I I have synchronicity by when I move the mous in one map the red circles in the other two are also moved.

![screenshot1](https://user-images.githubusercontent.com/40725616/166111220-266244e8-40bd-4ff7-b92a-066abc20475c.png)

But when I try to make the same using the output of the flexdasboard It doesn't print anything. Otherwise when I make three individual maps the are correctly represented, but then I loose the synchronicity. Any idea on how to solve that?

**Comment by cpsievert** [comment]
Please provide a reproducible example

**Comment by PauGallesClara** [comment]
Hi ! 
Attached you have the object map_SIR2.rds. And if you copy and paste in a flexdashboard, it doesn't create the leaflet map with synchronicity. But when you run the code in a html layout it works

`map_SIR2 <- tm_shape (barris_SIR2) +
  tm_polygons (c("SIR2", "Y2", "E2"), 
               style=c("cont", "cont", "cont"),
               alpha = 0.5,
               palette=list("-RdBu", "Blues", "Greens"),
               title=c("SIR 2a", "Observats 2a", "Esperats 2a"))

tmap_leaflet(map_SIR2) `

Hope you can help me
[map_SIR2.zip](https://github.com/rstudio/flexdashboard/files/9258189/map_SIR2.zip)

**Comment by PauGallesClara** [comment]
HI @cpsievert could you had the chance to see the example provided?.
Thank you in advance

**Comment by gadenbuie** [comment]
Hi @PauGallesClara! I'm hoping you've been able to resolve this issue, but if not, please provide a complete reproducible example that illustrates the problem. Unfortunately, I'm not very familiar with the packages you're using so I can't diagnose the issue without the complete example. I'm including an `.Rmd` snippet below that might help you create the example.

<details><summary>reprex.Rmd</summary>

````markdown
---
title: "Map Sync Issue"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)

# load additional packages and standalone data sets here
```

Column {data-width=650}
-----------------------------------------------------------------------

### Map One

```{r}
# first map
```

Column {data-width=350}
-----------------------------------------------------------------------

### Map Two

```{r}
# map 2
```

### Map Three

```{r}
# map 3
```
````

</details>
