### ISSUE TITLE
Broken link in 'examples' section

### ISSUE THREAD

**Issue by RPanczak** [rstudio/flexdashboard#397]
Example section of the website

https://pkgs.rstudio.com/flexdashboard/articles/examples.html

Has an example of 'Shiny: Neighborhood diversity' that points to https://walkerke.shinyapps.io/neighborhood_diversity from @walkerke 

Link is however broken.

**Comment by walkerke** [comment]
Yeah, I took the app down as I didn't want to pay the hosting fees given the traffic it was getting.  You can still clone the repo at https://github.com/walkerke/neighborhood_diversity and run locally; however it uses a previous generation of R Spatial so I'm unsure if everything will work perfectly.  

(This issue can be closed)

**Comment by walkerke** [comment]
@RPanczak I actually re-launched it with updated / modern code and new 2020 data, check it out!

**Comment by RPanczak** [comment]
Really cool! =)
