### ISSUE TITLE
Multiple rendering of echars4r drawings on one tab does not work

### ISSUE THREAD

**Issue by avraam-inside** [rstudio/flexdashboard#401]
There is a code for flexdasboard, I need to draw 6 graphs for each column, 2 per line + a scroll is needed, because all the graphs will not fit on the page.

The current problem is that the scroll is not displayed. We need to make it so that it is displayed.

```r
---
title: 'Test'
output:
    flexdashboard::flex_dashboard:
        orientation: rows
---

\```{r Setup, include = FALSE}
suppressPackageStartupMessages({
    library(echarts4r)
    library(data.table)
})
\```

# Test 

Row {.tabset .tabset-fade}
------------------------------------------------------------------------------------------------------------------------

\```{r, results = 'asis'}
# https://stackoverflow.com/questions/71339705/creating-tabs-automatically-in-rmarkdown-and-plotting-with-purrr

# activate autogenerate echarts
# https://stackoverflow.com/questions/63397427/programmatically-create-tab-and-plot-in-markdown
data.table(1) %>% e_charts(height = 0) %>% e_histogram(V1)

# get numeric cols
c('col1', 'col2', 'col3') %>%
# render graph by each col
purrr::iwalk(~{
    # .x <- 'duration'
    
    # create tabset for each group
    cat('###', .x, '\n')
    
    iris %>% setDT() %>%
        e_charts() %>%
        e_histogram(
            Sepal.Width,
            name = "histogram") %>%
        e_tooltip(trigger = "axis") %>%
        htmltools::tagList() %>%
        as.character() %>%
        cat()
    
    iris %>% setDT() %>%
        e_charts() %>%
        e_histogram(
            Sepal.Width,
            name = "histogram") %>%
        e_tooltip(trigger = "axis") %>%
        htmltools::tagList() %>%
        as.character() %>%
        cat()
    
    iris %>% setDT() %>%
        e_charts() %>%
        e_histogram(
            Sepal.Width,
            name = "histogram") %>%
        e_tooltip(trigger = "axis") %>%
        htmltools::tagList() %>%
        as.character() %>%
        cat()
    
    iris %>% setDT() %>%
        e_charts() %>%
        e_histogram(
            Sepal.Width,
            name = "histogram") %>%
        e_tooltip(trigger = "axis") %>%
        htmltools::tagList() %>%
        as.character() %>%
        cat()
})
\```
```

I get this (1 full-page graph instead of 4 fixed-height scroll charts):
![image](https://user-images.githubusercontent.com/52919010/193873978-8aec809d-9fb8-4eff-8767-d6e1305e20df.png)

**Comment by gadenbuie** [comment]
Thanks for the question! flexdashboard very much wants one plot per box area, even within tabs. But you can take matters into your own hands and add a wrapper div around the boxes you want to include. If you use Bootstrap 5 you can get really far with one small tweak.

1. Use Bootstrap 5 in your YAML frontmatter:

   ```yaml
   output:
     flexdashboard::flex_dashboard:
       theme:
         version: 5
   ```

2. Put all the plots in a wrapper container with classes `.d-flex .flex-row`.

   ```r
   cat('###', .x, '\n')

   # open chart container
   cat("\n\n::: {.d-flex .flex-row}\n")

   # ... output charts ...

   # close chart container
   cat("\n\n:::\n\n")
   ```

Out of the box this gives you all the plots in a single row.

![image](https://user-images.githubusercontent.com/5420529/222206465-2d8a7425-a2c4-484a-9cda-661887faf2d4.png)

In practice, you'll likely want to work out a slightly different structure for the plots or to give the plot container its own class that you can control with additional CSS you provide.

Anyway, I hope this gives you enough to get started or to figure out a way around the layout problem you're facing!
