### ISSUE TITLE
Navigation bar obscuring content

### ISSUE THREAD

**Issue by whv20** [rstudio/flexdashboard#412]
When designing a flexdashboard with multiple pages (each with long titles), the navigation bar at the top fills up rapidly. With all but the largest screen sizes, it splits into two or more lines, which then obscure the text beneath.

Several solutions have been discussed on other channels:

- Adding lots of blank lines between the navigation bar and contents is suggested [here](https://stackoverflow.com/questions/42914936/prevent-navigation-bar-from-overlapping-content-in-flexdashboard-r). This isn't ideal – as on a wider screen (when the navbar is still on one line), there's then a very obvious gap between the navbar and the page content. 
- Putting the tabs in drop down menus is also (discussed [there](https://stackoverflow.com/questions/42914936/prevent-navigation-bar-from-overlapping-content-in-flexdashboard-r)), but won't always be appropriate (depending on the structure of the dashboard)
- Using media queries and fiddling around with divs (suggested on stackoverflow [here](https://stackoverflow.com/questions/67941461/navbar-in-r-flexdashboard-cuts-off-main-content?noredirect=1&lq=1) and explained in more detail [here](https://www.w3schools.com/css/tryit.asp?filename=trycss_mediaqueries_hide)) feels like a very long-winded way of going about this… so I feel there must be a better way!
- I also recently posted about this on the [Posit community](https://community.rstudio.com/t/navigation-bar-obscuring-content-in-flexdashboard/156257)

It seems that this would be a very useful addition to the flexdashboard package - detecting when the screen size and navigation bar length are such that the navbar spills onto 2 or more lines, then moving the content down on the page automatically so it isn't overlapped by the navbar.

This could always be added as an optional feature (turned on or off in YAML) for those who for whatever reason don't want it.

Please could you consider adding this feature to your next update? 

Thanks very much in advance for your help - it’s a great package otherwise! :)

**Comment by gadenbuie** [comment]
Hi @whv20, thanks for opening this issue. I can certainly see how long page titles can take up a large amount of space in the navbar and how that can cause the navbar to wrap or overflow.

Here's an example that reproduces the issue

````markdown
---
title: Issue 412
subtitle: https://github.com/rstudio/flexdashboard/issues/412
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

# Section A Proident Proident Enim Veniam Minim Voluptate

Section A content

# Section B Eu Ea Eu Enim Qui Consectetur Ex

Section B content

# Section C Sint Aute Exercitation Exercitation Sint Nulla Dolor Elit Consequat Non Pariatur

Section C content

````

![image](https://user-images.githubusercontent.com/5420529/221034334-339c6da0-4311-4024-8a95-6a0d3816083b.png)

One idea is to use CSS to clip the navbar menu text if it gets too long. You can try adding this to your document.

```html
<style>
.navbar-inverse .navbar-nav>li>a {
  text-overflow: ellipsis;
  max-width: 200px;
  white-space: nowrap;
  overflow: clip;
}
</style>
```

This truncates text that would overflow the `200px` width and adds an ellipsis.

![image](https://user-images.githubusercontent.com/5420529/221034967-b3ab9a1c-8bde-4133-a83b-5a568b72c43b.png)

That said, a much simpler alternative would be to use shorter page titles. I know that probably sounds obvious, so it might be helpful if you could provide an example of a flexdashboard where you needed to use overly long section titles. That would help inform any changes we can make in flexdashboard.
