### ISSUE TITLE
valueBox not appearing

### ISSUE THREAD

**Issue by pssguy** [rstudio/flexdashboard#42]
I'm missing something here

    ```{r }
    renderValueBox({

      records <- data()
      print(records) #31
       valueBox(records, caption = "Records", icon="fa-thumbs-down")
     })
   ```

just renders the number 31 as simple text

**Comment by jjallaire** [comment]
That's because of your print statement (which is preventing the layout
engine from seeing the valueBox)

**Comment by pssguy** [comment]
Tx for swift reply. Removing print statement does not help. I also tried it with valueBoxOutput with no difference. The following code prints  31 twice

```{r vb artist uk}

renderValueBox({
  
  records <-artistUKData()$artistSummary %>% 
    tally() %>% 
    .$n
  
  valueBox(records,"Charted")
  
})

output$testVB <-renderValueBox({
  
  records <-artistUKData()$artistSummary %>% 
    tally() %>% 
    .$n
  
  valueBox(records,"Charted")
  
})

valueBoxOutput("testVB")
          
```

You can see a beta using actual data [here](https://mytinyshinys.shinyapps.io/musicChartsFlexDB/#artist)

**Comment by paulditterline** [comment]
And this:

````{r}
today <- Sys.Date()

renderValueBox({
  valueBox(today, icon = "lock")
})
````

Just creates a big blue box with the number in it.

**Comment by jjallaire** [comment]
I'm not clear on what the defect is here. Could you provide a complete Rmd file that exhibits the problem so I can investigate further? (you can just create a gist and link to it here). For the second example it looks like you are in mobile width (<= 768 pixels wide screen) which is why no icon is displayed.

**Comment by paulditterline** [comment]
I think my issue was mobile width, and leaving the "fa-" off my icon call.

**Comment by jaggaroshu** [comment]
it because of the # library(flexdashboard) , if you are using this library comment it and clear you environment and restart your ide will work fine
