### ISSUE TITLE
Some pages disappear when including images

### ISSUE THREAD

**Issue by MarkEdmondson1234** [rstudio/flexdashboard#44]
I have a strange bug I think that I can't replicate fully, but perhaps its hitting some kind of hard limit of HTML rendering?

I have the below .Rmd that renders ok if I don't include the rest of the R code, but in the full version (of about 400 lines) then including the images I have left in the debug version removes the last two pages in the top menu bar, which is mysterious :)
## Screenshots

Hopefully some explanatory screenshots below - the first shows if I include the images in the full app the top menu pages is only 3 pages

![screen shot 2016-05-31 at 14 25 56](https://cloud.githubusercontent.com/assets/3155884/15674182/bfce2002-273b-11e6-980f-b35f0193ee9d.png)

When I remove the images, I get all the pages back:

![screen shot 2016-05-31 at 14 26 46](https://cloud.githubusercontent.com/assets/3155884/15674181/bfcd6c34-273b-11e6-9d51-0213012a4e63.png)
## Example:

(I can't format the Rmd below as it uses ``` ? but edit this post to view the code as is. )

This example renders fine, which made me think its some kind of limit that is causing the issue.  (I'm sorry I can't include the original)

The R blocks include ggplot and plotly graphs to output - could they be conflicting somehow with the layout?

````
---

title: "Bug content"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
## runtime: shiny

``` r setup, include=FALSE
# Load packages and initialize data here
library(flexdashboard)
library(googleAnalyticsR)
library(shiny)
library(plotly)

```
# Trends {data-icon="fa-line-chart"}
## Column {.sidebar}
### Settings

``` r

## R code

```
## Column {.tabset .tabset-fade}
### Trends

``` r


```

``` r

```
### Animation

``` r, include=FALSE

```

When all the code is in place, including these two lines means the "Funnel" and "Content" pages are removed from top menu.

![](gganimatr2.gif)
![](gganimatr1.gif)
### Something else

Blah
# Campaign Mix {data-icon="fa-line-chart"}
## Column {.sidebar}
### Settings

``` r


```
## Row {data-height=650}
### Multi Channel Mix

``` r

```
## Row {data-height=350}
### Sunburst

``` r


```
### Medium Mix

``` r



```
# Geographic {data-icon="fa-globe"}
## Column {.sidebar}
### Settings

``` r


```
## Column
### Table

``` r


```
## Column
### Globe

Click and Zoom with mouse

``` r


```
### Map

``` r


```
# Funnel {data-icon="fa-filter"}

This page is removed from menu bar when the images above are included(??)
## Column {.sidebar}
### Settings

``` r


```
## Row {.tabset .tabset-fade}
### All Goals

``` r


```
### Goal 1

``` r


```
### Goal 2

``` r


```
### Goal 3

``` r


```
# Content {data-icon="fa-book"}

This page is removed from menu bar when the images above are included(??)
## Column {.sidebar}
### Settings

``` r


```
## Column
### Plot

``` r


```
### Funnel

``` r


```
````

**Comment by jjallaire** [comment]
If you could create a [gist](https://gist.github.com/) that has a reproducible example of the problem I'll investigate further.

**Comment by gadenbuie** [comment]
Thanks for reporting the issue and I'm hoping you haven't run into it again. If you do, please open a new issue and let us know.
