### ISSUE TITLE
R markdown

### ISSUE THREAD

**Issue by envoy-data** [rstudio/flexdashboard#441]
I keep getting this error anytime i click knit to put my document on html from R markdown. please help

processing file: Cyclistic-Bike-Share-Analysis-Case-Sudy-[R].Rmd
  |.............................................       |  86% [unnamed-chunk-2]
Quitting from lines 78-82 [unnamed-chunk-2] (Cyclistic-Bike-Share-Analysis-Case-Sudy-[R].Rmd)
                                                                                                            
Error in `contrib.url()`:
! trying to use CRAN without setting a mirror
Backtrace:
 1. utils::install.packages("tidyverse")
 2. utils::contrib.url(repos, "source")
Execution halted
![Screenshot 2023-09-20 091225](https://github.com/rstudio/flexdashboard/assets/145306505/15a8c90b-51e4-407b-871c-4a0a87c6a2cd)

**Comment by gadenbuie** [comment]
It seems like you might have a line like this somewhere in an R chunk:

```r
install.packages("tidyverse")
```

If you do, you can remove this line. You only need to install the tidyverse once on your machine; after it's installed, you can use `library(tidyverse)` whenever you want to use the tidyverse package.

**Comment by gadenbuie** [comment]
I hope the above helped! I'm going to close this issue for now, but please feel free to comment on this issue if you have more information.
