### ISSUE TITLE
Any way to include a copyright notice in nav bar?

### ISSUE THREAD

**Issue by tbadams45** [rstudio/flexdashboard#45]
Ideally aligned right like the source code icon is here: https://jjallaire.shinyapps.io/shiny-biclust/

**Comment by jjallaire** [comment]
Sure, you can just do this:

    ---
    title: "Copyright"
    output: 
      flexdashboard::flex_dashboard:
        navbar:
          - title: Copyright RStudio, Inc.
    ---

You can also add an "author" field in which case the copyright will be on the left next to the title:

    ---
    title: "Title"
    author: "Copyright RStudio, Inc."
    output: flexdashboard::flex_dashboard
    ---
