### ISSUE TITLE
Create pages hidden from navbar

### ISSUE THREAD

**Issue by eamcvey** [rstudio/flexdashboard#46]
The flexdashboard package is incredibly useful and already many of the features I would have requested have appeared over the last few weeks.  My challenge now is to provide an easy to navigate dashboard that has multiple levels of detail.  One way to do this would be to have multiple tabsets on a page, which only really works for me if I can arrange them in a 2x2 layout or something of the sort (already addressed in another issue).  Another approach would be to have a side navigation bar that provides links to more detailed pages -- but in this case I'd want those pages not to show up in the navbar menus, as they would clutter things too much (unless there's an additional level of hierarchy available in the menu).  If there were a way to create a page that didn't appear in the menu and thus was accessible only by link, that would be helpful.

**Comment by lindzmm** [comment]
Did you find a way to create pages hidden from the navbar? I'm facing the same problem and would like to just link to other pages but can't figure it out.

**Comment by jjallaire** [comment]
Fixed via https://github.com/rstudio/flexdashboard/commit/82278a7963f5c5e217efc8e1e39ca00b62d69393
