### ISSUE TITLE
Title link not displaying correctly

### ISSUE THREAD

**Issue by jrowen** [rstudio/flexdashboard#47]
The link itself is functional, but I'm seeing `Google" />` right below the navbar.

```

---
title: "`r htmltools::tags$a(href = 'www.google.com', style = 'color: inherit; text-decoration: inherit;', 'Google')`"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill

---
```

I'm using v0.2.1.

**Comment by jrowen** [comment]
I think the problem can be traced back to [setting the `og:title` property](https://github.com/rstudio/flexdashboard/blob/master/inst/rmarkdown/templates/flex_dashboard/resources/default.html#L19).

**Comment by jjallaire** [comment]
HTML within the html `<title>` tag is invalid, see https://www.w3.org/TR/html401/struct/global.html#h-7.4.2

**Comment by jrowen** [comment]
Sorry, I didn't clarify the goal of the code above.  I was attempting to add a link to the navbar header (think of it as a home link) and not to the page title `<title>` .  It appears that these two items are currently linked.  Maybe there is a better way to add a link to the link in the navbar header.

**Comment by jjallaire** [comment]
You are right, there's currently no way to do this outside of including custom JavaScript. Marking as an enhancement request.

**Comment by s-etty** [comment]
Is there a way to make the title of a dashboard a hyperlink? What would the custom JavaScript look like to make this happen?

**Comment by gadenbuie** [comment]
Here's a snippet of JavaScript that you can add into your dashboard to update the title to make it a link.

```html
<script>
$('.navbar-brand')
  .replaceWith('<a class="navbar-brand" href="https://duckduckgo.com">Google</a>')
</script>
```

Watch out, though. flexdashboard adds the document author to the `.navbar-brand` element, and the JavaScript above might remove it accidentally.
