### ISSUE TITLE
flexdashaboard fail to load customize js.

### ISSUE THREAD

**Issue by harryprince** [rstudio/flexdashboard#48]
I am trying to load my customize javascript code in 10+ way, but I fail to do that.
Here is what I was trying:
\```{r}
HTML("<script src=\"init.js\"></script>")
source("init.R") # init.R including some script to load js
includeScript('init.js')
\```

or adding dependencies option in yaml,like this:

dependencies:
    script:
        - init.js

or writing HTML("<script src=\"init.js\"></script>") directly out of R block.

above all, I couldn't insert my js, I found the problem is flexdashboard convert all this thing into some secret code when I check out the source file by chrome.

**Comment by jpf5046** [comment]
Rand into a similar issue when trying to deploy google analytics script.

Was trying to run:

`tags$head(includeScript("Data\\google-analytics.js"))`

with 'google-analytics.js' being a file that provides the standard google tracker script given by google analytics. 

Rmarkdown would Knit, but did not show up in the source code in the browser.

**Comment by MarkEdmondson1234** [comment]
I have a similar issue, trying to add custom javascript via a Shiny module: the javascript renders but doesn't seem to fire.  Do I need to change the JS somehow?

Here is the JS in case its needed:

```r
gar_auth_jsUI <- function(id, 
                          login_class = "btn btn-primary",
                          logout_class = "btn btn-danger"){

  ns <- shiny::NS(id)

  shiny::tagList(
    tags$script(src='https://apis.google.com/js/auth.js?onload=init'),
    tags$button(id = ns("login"), onclick="auth();", "Log In", class = login_class),
    tags$button(id = ns("logout"), onclick="out();", "Log Out", class = logout_class),
    tags$script(type="text/javascript", HTML(paste0("
      var authorizeButton = document.getElementById('",ns("login"),"');
      var signoutButton = document.getElementById('",ns("logout"),"');
      signoutButton.style.display = 'none';
      function auth() {
        var config = {
          'client_id': '",getOption("googleAuthR.webapp.client_id"),"',
          'scope': '", paste(getOption("googleAuthR.scopes.selected"), collapse = " "),"',
          'approval_prompt':'force'
        };
        gapi.auth.authorize(config, function() {
          token = gapi.auth.getToken();
          console.log('login complete');
          console.log(token);
          Shiny.onInputChange('",ns("js_auth_access_token"),"', token.access_token);
          Shiny.onInputChange('",ns("js_auth_token_type"),"', token.token_type);
          Shiny.onInputChange('",ns("js_auth_expires_in"),"', token.expires_in);
          authorizeButton.style.display = 'none';
          signoutButton.style.display = 'block';
        });
       }
       function out(){
          gapi.auth.signOut();
          location.reload()
       }
       "
    ) )
    )
  )

}
```

**Comment by digital-dharma** [comment]
We'd also be interested in this.  Without a fix, I understand that inserting usage tracking code such as Google Analytics is not possible.

**Comment by jcheng5** [comment]
Wow, you're all running into completely different problems. I don't think there's an underlying bug here.

@harryprince: `includeScript("init.js")` doesn't have the _side effect_ of including the JS code; instead, it returns the JS code object as a value, suitable for being printed as part of the document. So it wouldn't work inside a `source("init.R")` unless you did `source("init.R")$value` and also called `includeScript("init.js")` as the final expression in init.R.

@jpf5046: `tags$head` doesn't seem to work in Rmd, period. I'm not clear on whether this was a regression we picked up at some point, or whether it never worked. In either case, I'd just drop it and call `includeScript` directly. If you really feel strongly about having it in the `<head>`, you can accomplish that by declaring an `htmlDependency` object and having knitr print it:

```r
```{r}
library(htmltools)
attachDependencies(tagList(),
  htmlDependency("google-analytics", version = "1.1.1", "Data", script = "google-analytics.js", all_files = FALSE)
)
```

but I wouldn't bother.

@MarkEdmondson1234: You have `https://apis.google.com/js/auth.js?onload=init`, but where is the `init` function defined? Are you getting an error in your JS console?

@digital-dharma: What have you tried so far?

We can continue the discussion in this thread but I'll mark it as closed unless/until a concrete code issue or feature request is identified.

**Comment by jcheng5** [comment]
Actually wait a sec--are you all using `runtime: shiny`? After turning that on, I get problems with `tags$script` and `includeScript` not running.

**Comment by MarkEdmondson1234** [comment]
Hi, yes I still get the problem, with `runtime: shiny`.  

I took out the init function ( as it shouldnøt have been there, yes) but its still as if the passed in JS never fires.  I can see it rendered in the source but nothing runs.  

Screenshot of the JS console:
<img width="893" alt="screen shot 2016-07-21 at 20 47 24" src="https://cloud.githubusercontent.com/assets/3155884/17034880/dd4e5bf8-4f84-11e6-8a97-f48073c7fe75.png">

and I published the Flexdashboard here: https://mark.shinyapps.io/authDemoFlex/ (the log out button should be hidden if the JS fires correctly)

A very similar Rmarkdown document that the same functions work is here: https://mark.shinyapps.io/googleAuthRMarkdown/

**Comment by jcheng5** [comment]
OK, in that case, this is the same issue as #29. We should have a fix soon. Thanks!

**Comment by digital-dharma** [comment]
@jcheng5 - Joe, you're spot on, we're using: `runtime:shiny`

We'll track the issue and conversation in #29.

Thanks again,
- Jeff

**Comment by tarunparmar** [comment]
@jcheng5 - Hi Joe, I am using flexdashboard 0.5 from cran and was able to get the GA work with first app having `runtime: shiny` in it and by having `includeScript("www/js/google-analytics.js")`. The GA id was like GA-XXXXXXXX-2. 
I had another app for which I created second property in GA and used the GA-XXXXXXXX-3 but this app does not show any data on Google. Any idea what could be wrong ? Thx.
