### ISSUE TITLE
DT has fidgety behaviour while adding rows

### ISSUE THREAD

**Issue by MySchizoBuddy** [rstudio/flexdashboard#49]
When you add rows to a reactive dataframe and have DT display the dataframe. You will notice that the bottom navigation moves up and down every time you add a row to the dataframe
Here is[ working code ](https://gist.githubusercontent.com/MySchizoBuddy/ad1a1fc057be9d9e65c4d997204debb7/raw/cd0b8bfb1b89e0746f191af78ccdb78426268972/tableTest.Rmd)that shows this behavior.

**Comment by jjallaire** [comment]
That's unfortunately a DT issue that I don't think we can address in the short term (it has to do with how DataTables redraws itself when new data is received).
