### ISSUE TITLE
cannot disable Mathjax

### ISSUE THREAD

**Issue by MySchizoBuddy** [rstudio/flexdashboard#50]
using `mathjax :NULL` in yaml doesn't disable mathjax when using shiny runtime.
Also `author: Name` shows the name next to the title. Is this by design

**Comment by jjallaire** [comment]
Yes, showing the name next to the title is indeed by design.

I'm unable to repro `mathjax: null` failing to disable mathjax when in shiny. Could you provide a reproducible example of this please?
