### ISSUE TITLE
resizing the window relauches the application

### ISSUE THREAD

**Issue by MySchizoBuddy** [rstudio/flexdashboard#51]
Flexdashboard with shiny runtime
When you make the window smaller it relaunches the app. All state is then lost.

**Comment by jjallaire** [comment]
This is currently by design (we need to reload the app to switch between
mobile and non-mobile layouts). One possible workaround is if we can make
the threshold where we do this configurable. See
https://github.com/rstudio/flexdashboard/issues/43

**Comment by pssguy** [comment]
Not sure if this is related but I have also noticed that when i use an actionButton it shows up in full screen but not when reduced in size even when I set a small width eg 100px

Full Screen
![before](https://cloud.githubusercontent.com/assets/2775918/15866488/ad65284a-2c93-11e6-85e2-1dede0cc2e05.png)

Reduced Size
![after](https://cloud.githubusercontent.com/assets/2775918/15866493/b3ded748-2c93-11e6-891e-dc4e1c33139a.png)

**Comment by jjallaire** [comment]
Could you file a separate bug about the actionButton issue?

**Comment by yogat3ch** [comment]
> This is currently by design (we need to reload the app to switch between
> mobile and non-mobile layouts). One possible workaround is if we can make
> the threshold where we do this configurable. See
> #43
> 
> On Sun, Jun 5, 2016 at 7:51 AM, MySchizoBuddy [notifications@github.com](mailto:notifications@github.com)
> wrote:
> 
> > Flexdashboard with shiny runtime
> > When you make the window smaller it relaunches the app. All state is then
> > lost.
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub
> > #51, or mute the thread
> > https://github.com/notifications/unsubscribe/AAGXxycgqvdvgehWC6hBaeiz2cgBkm3kks5qIrhKgaJpZM4IuVqV
> > .

@jjallaire An option to disable this reloading behavior would truly be wonderful for debugging purposes. In building a large shiny app where hundreds to thousands of debugging sessions have to be run the number of accidental reloads becomes significant and time consuming. It also seems to occur for no reason on occasion - like when a date slider is adjusted. 

I think an argument to just turn off automatic reloading of the app under any circumstances, except from user input (hitting stop on the RMarkdown tab, or closing the window), will resolve this.

**Comment by jjallaire** [comment]
Seems like a valuable addition to provide this option. @schloerke Could we take a shot at this? (references to the relevant bits of code below).

Here's where we trigger the reload:

https://github.com/rstudio/flexdashboard/blob/master/inst/rmarkdown/templates/flex_dashboard/resources/flexdashboard.js#L144-L147

Here's where options come in to JavaScript from R:

https://github.com/rstudio/flexdashboard/blob/master/inst/rmarkdown/templates/flex_dashboard/resources/flexdashboard.js#L11-L23

Finally, here's where we pass options from R to JavaScript:

https://github.com/rstudio/flexdashboard/blob/ccb5f1ad057f42da24818d6ff3acb0f4e6b944cb/R/flex_dashboard.R#L344-L358

**Comment by yogat3ch** [comment]
@jjallaire, @schloerke ,
Thanks for elevating this to an action item! I wanted to offer a contribution to get it started since I imagine ya'll have a lot of other things underway.
