### ISSUE TITLE
Printing dashboard

### ISSUE THREAD

**Issue by Clementine** [rstudio/flexdashboard#52]
Hi, 

Is it possible to print a dashboard?

When I use cmd-p to print this dashboard https://beta.rstudioconnect.com/jjallaire/htmlwidgets-ggplotly-geoms/, there's aren't any graphs and all the text is garbled. 

I'm not sure whether this is a bug or if there is a technical reason why it can't be done, but it would be really useful to be able to print out the dashboard. 

thanks,

**Comment by jjallaire** [comment]
No, dashboards aren't really intended to be printed.

**Comment by Clementine** [comment]
Thanks for the quick reply. I work for an NGO operating mainly in sub-Saharan Africa and flexdashboard seems exactly what we need to share analytical results. However, we also need to be able to print the dashboards (and also save as pdfs) as we can't assume that people will always have internet access. 

Being able to print flexdashboards would change the way we are able to work. Consequently, I'd be really grateful if you could please look into the issue. Any help you could give would be amazing. 

thanks

**Comment by jjallaire** [comment]
I'd suggest you just add another format (e.g. pdf_document) alongside the
flexdashboard::flex_dashboard format and render to PDF for offline access.

This won't work if you are including htmlwidgets because JavaScript
visualizations don't play nicely with print formats like PDF.

**Comment by Clementine** [comment]
Thank you so much for your help. I've been trying to get your suggestion to work but I'm struggling a bit. Could you please illustrate how I could change the below code to also get a pdf output?

---
title: "My dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```

**Comment by jjallaire** [comment]
Just add pdf_document as an additional format:

    ---
    title: "My dashboard"
    output: 
      pdf_document: default
      flexdashboard::flex_dashboard:
        orientation: columns
        vertical_layout: fill
---

When you hit the Knit button in RStudio or call the `rmarkdown::render` function you'll get the first format listed. You can render an individual format as follows:

```r
rmarkdown::render("mydoc.Rmd", output_format = "pdf_document")
```

You can also render all formats with:

```r
rmarkdown::render("mydoc.Rmd", output_format = "all")
```


If you get the [Preview Release](https://www.rstudio.com/products/rstudio/download/preview/) of RStudio then the Knit button will also include a menu that allows you to switch between the various formats within the UI.
