### ISSUE TITLE
Action Button disappears on downsizing window

### ISSUE THREAD

**Issue by pssguy** [rstudio/flexdashboard#53]
when i use an actionButton it shows up in full screen but not when reduced in size even when I set a small width eg 100px

Full Screen
![before](https://cloud.githubusercontent.com/assets/2775918/15866488/ad65284a-2c93-11e6-85e2-1dede0cc2e05.png)

Reduced Size
![after](https://cloud.githubusercontent.com/assets/2775918/15866493/b3ded748-2c93-11e6-891e-dc4e1c33139a.png)

**Comment by pssguy** [comment]
Just checking in as this kinda goes against pushing FDB as a mobile experience. Am I missing something?

**Comment by jjallaire** [comment]
I'm currently not able to reproduce this. Could you provide a minimal reproducible example so we can investigate further?

**Comment by gadenbuie** [comment]
Thanks for reporting! I also cannot reproduce this (many years later), so I'm going to close this issue. If you run into something similar, please open a new issue.
