### ISSUE TITLE
Fully dynamic control the number of pages, charts

### ISSUE THREAD

**Issue by ThoDuyNguyen** [rstudio/flexdashboard#55]
Currently, we define pages and charts beforehand. 

But sometime, we need the number pages/charts dynamically, for example when a report for products when each product will be presented in a page and the product list could be changed all the time. 

My thought is that i write an  script to output a Rmd file and then render that file. Could we do it directly just by using only Rmd file without writing additional script? 

Kind regards.

**Comment by Agpa88** [comment]
I am topping up this request. It would be highly appreciated functionality to dynamically determine number of pages/columns/boxes.

**Comment by gadenbuie** [comment]
Unfortunately this is not a use-case that flexdashboard is designed to cover well. I would recommend you instead look into building your dashboard with [Shiny](https://shiny.rmarkdown.com).
