### ISSUE TITLE
Flexdashboard on shiny - not running

### ISSUE THREAD

**Issue by nite** [rstudio/flexdashboard#57]
Hi, 

I have a flexdashboard that works via rmarkdown::run() but not shiny on the same server - the loading spinner shows but times out. After ages it shows 'Error: subscript out of bounds' on the browser doc. 
No logs appear in /var/logs/shiny-server or errors to the js console. Nothing else in the directory, and I've tried with an empty newly generated flexdashboard. 

Any ideas?

**Comment by jjallaire** [comment]
We've got log
