### ISSUE TITLE
Bug: Duplicate pages due to a full stop

### ISSUE THREAD

**Issue by csgillespie** [rstudio/flexdashboard#60]
If I build the [following](https://gist.github.com/csgillespie/0f30ec3cd6e219048649944897b8082a) flex dashboard file, the scatter plot isn't displayed. Instead, when I click on the `Scatter` page the histogram is still shown. 

Removing the `.` from the page title solves the issue.

**Comment by jjallaire** [comment]
Fixed via https://github.com/rstudio/flexdashboard/commit/8c4553836ec7c21f1c301c4b5b26cefbd51e394f
