### ISSUE TITLE
unicode character in tabset results in blank page

### ISSUE THREAD

**Issue by shrektan** [rstudio/flexdashboard#65]
Hi, I like this package very much. The design is awesome and it's very useful for me.

However, I met an issue related to unicode character here, not sure it's a problem of `rmarkdown` or `flexdashboard`.

Here's my code, you will find the whole page is blank, unless you replace the unicode character （风险状况 & 收益情况) with ascii characters. 

```rmarkdown
---
title: "中文-beta"
output: 
  flexdashboard::flex_dashboard:
    theme: yeti
---

概览
=========================================

test2 {.tabset .tabset-fade}
-----------------------------------------

### 风险状况

test

### 收益情况

test

```

**Comment by jjallaire** [comment]
This is a limitation of pandoc (it can't support chinese characters within header ids): https://github.com/revolunet/sublimetext-markdown-preview/issues/129

Happily, there is a workaround -- You can explicitly create an ID in the header attributes like this:

    ### 风险状况 {#id1}

    test
 
    ### 收益情况 {#id2}

    test

Maybe I can automate this so you don't need to do this explicitly (I'll leave this case open pending that investigation).

**Comment by jjallaire** [comment]
Fixed via https://github.com/rstudio/flexdashboard/commit/bba4e61e0f7aa22d9d551cb2a247f013e6d2a3fb

**Comment by shrektan** [comment]
great, thanks!
