### ISSUE TITLE
Error: package or namespace load failed for 'highcharter'

### ISSUE THREAD

**Issue by ptoche** [rstudio/flexdashboard#67]
Playing around with the examples, successfully built several flexdashboards: Brilliant Stuff!!

Had problems with the following. Any ideas?

title: "Sales Report with Highcharter"
author: "Joshua Kunst"

render("htmlwidgets-highcharter.Rmd", flex_dashboard())

processing file: htmlwidgets-highcharter.Rmd
  |......                                                           |  10%
  ordinary text without R code

  |.............                                                    |  20%
label: setup (with options) 
List of 1
 $ include: logi FALSE

Error : object 'layout_nicely' is not exported by 'namespace:igraph'
Quitting from lines 12-31 (htmlwidgets-highcharter.Rmd) 
Error: package or namespace load failed for 'highcharter'

**Comment by jbkunst** [comment]
Hi @ptoche 

It's seems a more about the highcharter installation than a flexdashboard issue. Have you tried install the lastest version of highcharter?

If you still have issues let's discuss in the highcharter issues section.

Best,

**Comment by ptoche** [comment]
@jbkunst, you must be right. I was just fooling around, not a big problem, thanks.

**Comment by Elaine-AL** [comment]
hi @jbkunst am also getting this error while loading the highcharter package. At first i thought it was a problem in my code while running a flexdashboard, but when i removed, re-installed and loaded the package again i got the same error. This one below.

Quitting from lines 658-713 (Probability-of-churn.Rmd) 

Warning: Error in : package or namespace load failed for 'highcharter':
 object 'all_of' is not exported by 'namespace:dplyr'

**Comment by jbkunst** [comment]
Hi @Elaine-AL 

Try to update `dplyr` and `tidyselect` package. 

Tell me if this works for you.

**Comment by bynans** [comment]
I had the exact same error as @Elaine-AL this morning, and updating `dplyr `and `tidyselect `solved the issue.
Thanks!!

**Comment by Elaine-AL** [comment]
Thanks @jbkunst  your solution worked!! It was because i had updated all the packages in my Rstudio.

Hi @bynans good for you too!!

**Comment by jbkunst** [comment]
Thanks @bynans  and @Elaine-AL  for the confirmation! We'll keep closed this issue 😅
