### ISSUE TITLE
Commentary in storyboard repeated on mobile

### ISSUE THREAD

**Issue by AdeelK93** [rstudio/flexdashboard#69]
The storyboard shows the commentary for every section all together for each frame when on mobile. This seems to happen with each storyboard I try to view on mobile, even the example one: https://beta.rstudioconnect.com/jjallaire/htmlwidgets-showcase-storyboard/

I'm using an iPhone 5S if it helps any. Anyone else seeing this?

**Comment by jjallaire** [comment]
Fixed via: https://github.com/rstudio/flexdashboard/commit/c7ee9d7fdb07726b6d6684d368f9f00a0281a9f6
