### ISSUE TITLE
Adding notes to multiple elements within a column does not size/display properly

### ISSUE THREAD

**Issue by eamcvey** [rstudio/flexdashboard#71]
If I add notes with the > method to two elements in the same column on a page, typically one will display correctly and the other will get squished to almost non-visible state.  Also this seems to cause a page not to fit in the browser window by the height of the note box.  This is the type of setup where I consistently find this not working.  This is a great feature for adding short captions, and I look forward to it working completely : )

```
Column 1 {data-width=200}
-------------------------------------

### First box

> Some text

### Second box

> Some text
```

**Comment by Henry-E** [comment]
Rather than making an new issue I thought I'd also mention that new line and carriage return characters, \n and \r, don't work inside of annotations. Not sure if this is by design.

**Comment by jjallaire** [comment]
Okay, that's good to know.

I realize that I've been unresponsive to issues on this repo for the last
few weeks -- was very busy with preparing for useR. I'll be turning to
flexdashboard work and will deal with all the issues later this month.

**Comment by eamcvey** [comment]
Related to this, the behavior I'd like when adding text (just regular markdown, not annotation specifically) in the same element as a graph is for them collectively to take up the same space as the graph on its own would have.  i.e. I want the graph to resize to make space for the text rather than it resulting in a page that requires scrolling to see the bottom of.  I'm not sure if this is the intended behavior and it's a bug, or if it wasn't intended to behave this way.  Particularly because so many of the web-friendly graphics packages I've tried place the y-axis label on top of or ugly-close to the tick mark values, it's nice to use text to describe the graph in lieu of labels (though hopefully someday either way will be viable).

**Comment by jjallaire** [comment]
I'm not reproducing the issue with footnotes that you are seeing. Here's the full code of my test Rmd:

    ---
    title: "Test"
    output: 
      flexdashboard::flex_dashboard:
        orientation: columns
        vertical_layout: fill
    ---

    Column
    -----------------------------------------------------------------------

    ### Chart A

    ```{r}

    ```

    Column
    -----------------------------------------------------------------------

    ### First box

    > Some text

    ### Second box

    > Some text

**Comment by jjallaire** [comment]
You can actually get newlines into chart notes by using the markdown syntax for newlines (two spaces at the end of the line prior to the \n)

**Comment by jjallaire** [comment]
The interleaving of arbitrary text with figures inside dashboard panels is definitely something I'd like us to be able to do but it's pretty tricky/expensive so not something we're pursuing in the short term.

**Comment by eamcvey** [comment]
I discovered that the issue I was having with footnotes was user error -- in some cases I did not have an empty line between the end of the R chunk for the plot and the > text line

**Comment by jjallaire** [comment]
Okay, great. Glad you sorted out what was going on.
