### ISSUE TITLE
Row layout cannot be set on a page by page basis

### ISSUE THREAD

**Issue by eamcvey** [rstudio/flexdashboard#73]
Although I can get other layouts set by page (ex. storyboard), I have not been able to get some pages to have a row layout and others to have a column layout.  When I add ```{.rows}``` to the page header, I still get columns.  Not sure if this is a bug or a feature request ...

**Comment by jjallaire** [comment]
You should be able to use the `data-orientation` attribute to set a distinct orientation for a page. See http://rmarkdown.rstudio.com/flexdashboard/using.html#page-orientation

**Comment by eamcvey** [comment]
Thank you - this worked : )  Not sure why I couldn't get it to work when I tried what I thought was the same thing originally.

**Comment by pulleyps** [comment]
I normally like to put spaces before and after '=' equal signs, but it appears that in setting this data-orientation flag, it doesn't work unless I remove these spaces.
