### ISSUE TITLE
invalid multibyte character Error

### ISSUE THREAD

**Issue by statkclee** [rstudio/flexdashboard#74]
Whenerver I compile, I've got the following errors where Korean characters appear.

rd <- read_excel("01.data/게임(종합).xlsx", sheet="게임별 데이터", skip=2)

Quitting from lines 21-23 (dashboard-proto.Rmd) 
Error in source("02.code/hsh.R") : 
  invalid multibyte character in parser at line 36
Calls: <Anonymous> ... eval -> source -> withVisible -> eval -> eval -> source
Execution halted

**Comment by jjallaire** [comment]
Please post a complete minimum reproducible example so we can debug this problem firsthand.
