### ISSUE TITLE
Flexdashboard potential bug in CentOS?

### ISSUE THREAD

**Issue by carloserrangeli** [rstudio/flexdashboard#75]
Hi 
I am trying to generate a html file from Rmd document using flexdahsboard output. In WinOS works grat, but for some reason I believe that some of the functions are not behaving properly in CentOS.
html output works fine in both systems
Attach is Rmd file andd the 2 outputs generated
[test.zip](https://github.com/rstudio/flexdashboard/files/366743/test.zip)
If I replace following function in resulting html file, than I am able to open CentOS html file
  function addNavbarItems
  
  function componentsInit(dashboardContainer) {
 function componentsFind(container) {
  function componentsCustom(components) {
  function componentsFlex(components) {
  function componentsLayout(components, title, container) {
  function extractTitle(container) {
  function extractChartNotes(chartContent, chartNotes) {
  function findShinyOutput(chartContent) {
  function isMobilePhone() {
  function isFillPage() {
  function isPortrait() {
  function isTablet() {
  function isShinyDoc() {
  function handleLocationHash() {

**Comment by jjallaire** [comment]
I have no trouble running the flexdashboard examples on CentOS and also have no trouble with the test files you sent. It's possible that if you are using the Firefox version built into CentOS that it isn't updated enough to render flexbox layout correctly. In that case you could try updating to a more recent version of Firefox or using Chrome.

In any case, if you are still seeing problems feel free to post a new issue that includes a minimum reproducible example. Also please let me know if you see any errors printed in the JavaScript console.

**Comment by carloserrangeli** [comment]
Can you give me list of packages and version that you have on your CentOs?

**Comment by jjallaire** [comment]
See below. I've also confirmed that the version of Firefox that ships with CentOS definitely cannot render flexdashboard correctly.

```
R version 3.1.1 (2014-07-10)
Platform: x86_64-redhat-linux-gnu (64-bit)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] flexdashboard_0.2.1

loaded via a namespace (and not attached):
 [1] digest_0.6.4    evaluate_0.9    htmltools_0.3.5 jsonlite_0.9.17
 [5] knitr_1.13      magrittr_1.5    Rcpp_0.11.5     rmarkdown_1.0  
 [9] stringi_1.1.1   stringr_1.0.0   tools_3.1.1     yaml_2.1.13    
```

**Comment by carloserrangeli** [comment]
Hi this is what I am getting from java console on my browser.
I just want to let you know that the problem is in the produced html file in my case not in browser
![flexsdashboardconsole](https://cloud.githubusercontent.com/assets/16352955/17027137/b461b7f2-4f30-11e6-83a2-48fe36527423.png)

**Comment by jjallaire** [comment]
I have no idea what the underlying problem is. You have to give me an example that I can reproduce locally.

**Comment by carloserrangeli** [comment]
If you are available next week I would like to share my screen with you so you can see what I am facing.

**Comment by carloserrangeli** [comment]
I apologize jj.
I believe that I erroneously gave you the wrong fileattached are teh 2 html file generated that actually are differrent. One generated from serverthe other locally


[flex_index_error_CEntOs.zip](https://github.com/rstudio/flexdashboard/files/377996/flex_index_error_CEntOs.zip)

**Comment by jjallaire** [comment]
I need to be able to reproduce the problem to fix it. This means I need you
to send the source code of the Rmd that is generating the html with errors.
Just sending me an html file that's broken doesn't help because I have no
idea how it got broken without the source code.

**Comment by carloserrangeli** [comment]
yes
the Rmd example was in the test.zip file in my previous post.
I am trying to replicate the error via R console, error miught be related to pandoc version? I think the version I got is old and rmarkdown looks for a n ewer version .. I will let you know what I find out

**Comment by carloserrangeli** [comment]
jjallaire
I solved the issue
that was with pandoc version
I had to uninstall what is coming with CentOS (1.9) and create a link to point to version that is coming with RStudio as suggested on your site

sudo ln -s /usr/lib/rstudio-server/bin/pandoc/pandoc /usr/local/bin

This solved my issue
thanks again
Carlo

**Comment by jjallaire** [comment]
Great, glad you figured this out!
