### ISSUE TITLE
Anyway to control sidebar (toggle | slide off) ?

### ISSUE THREAD

**Issue by gponce-ars** [rstudio/flexdashboard#76]
Hi,

Is there anyway to control a sidebar within flexdashboard? 
E.g. Let's say that I want to show a side bar only when someone click at a specific menu option, otherwise the side bar should be slide off...

**Comment by jjallaire** [comment]
No, there isn't currently a way to do this.

**Comment by gadenbuie** [comment]
This was also requested in #210 where more people have commented and upvoted the issue.
