### ISSUE TITLE
Sharing large datasets over multiple sessions?

### ISSUE THREAD

**Issue by raubreywhite** [rstudio/flexdashboard#85]
I have a large data.table that is the underlying dataset for my flexdashboard. Using the old shiny server.R file, I could specify the loading of this file outside of the session call, meaning that the data was only loaded once (being both fast and saving lots of memory). I can't seem to find how to do this with flexdashboards? Is it even possible?

**Comment by jjallaire** [comment]
@jcheng5 and  @jmcphers, is there a way to get code to execute once at startup for `runtime: shiny` analogous to the way that you can do this for normal Shiny applications?

**Comment by jjallaire** [comment]
If there isn't a way to do this now, perhaps we could by convention treat a chunk with a special label (e.g. `global`) as something that's only executed once per process.

**Comment by jmcphers** [comment]
I can't think of one. The Shiny "server function" for `runtime: shiny` is embedded in the rmarkdown package (cf. https://github.com/rstudio/rmarkdown/blob/a40b2f57e7b461297603ee72453028b5ba4a02fc/R/shiny.R#L166); it has no hooks for doing this kind of thing now but it'd be relatively straightforward to prime the session.

**Comment by jjallaire** [comment]
It looks to me like it sources global.R if it exists,
wouldn't that do the trick?

**Comment by jcheng5** [comment]
Seems like global.R should work, yeah.

**Comment by jmcphers** [comment]
I was trying to discover the mechanism by which this happens and found this: https://github.com/rstudio/rmarkdown/commit/dd9bbba1d166fc43eca3533922d6c103ad3a5988

That's what I get for commenting on github before I've had coffee! Thanks guys. :-)

**Comment by jjallaire** [comment]
@raubreywhite It looks like if you create a file named global.R alongside your flexdashboard that code will run once per app (at startup) rather then once per user connection.

I still think it would be nice if we could include this code in a special chunk named e.g. `global`.  I'll take a look at doing this soon.
