### ISSUE TITLE
Icons in the menus (not individual pages)

### ISSUE THREAD

**Issue by Eflores89** [rstudio/flexdashboard#88]
Is it possible, or maybe an enhancement in future versions, to add icons to the menu headers (as opposed) to the individual pages? 

For example, to have the "fa-medkit" icon in the OTC menu (like the Farma) in the following example, and not in the "Total" tag: 
![icons](https://cloud.githubusercontent.com/assets/5789139/18357949/7e4676ae-75b8-11e6-9a66-09af1a4cd9f8.PNG)

**Comment by mgarbuzov** [comment]
Why closed, is there a solution?
