### ISSUE TITLE
Updating of elements of input (updateSelectInput) is possible?

### ISSUE THREAD

**Issue by AITikhonov** [rstudio/flexdashboard#90]
Hello.
In my Shiny application, I choose parameter in the first SelectInput, the file is downloaded, and on the base of this file the second select input has to be updated throught observe(updateSelectInput(....)). 
But  in transformation of shiny application in flexdashboard I can't update this selectinput.

It in general is impossible in the flexdashboard? Or there are some ways to solve a similar problem.
Thank you.

**Comment by pkopps** [comment]
Hey

It is, after some research and fiddling I got it to work. The key I think is to use observeEvent() (not observe()) and declare what the observeEvent function should depend on (the other input). 

```r

# marketplace selector for filtering
selectizeInput(
  "marketplace_short_names", 
  label = "Marketplace:", 
  choices = marketplace_short_names, 
  selected = marketplace_short_names,
  multiple = FALSE,
  options = list(
    plugins = list('remove_button', 'drag_drop')
  )
)

observeEvent(input$marketplace_short_names, {
  
  marketplace_short_name <- input$marketplace_short_names

  if(marketplace_short_name == 'IT'){
    start_date <- weblab_launch_dates_min %>% filter(marketplace_short_name == marketplace_short_name) %>% select(wk_start_date) %>% pull()
  } else {
    start_date <- Sys.Date() - 30
  }

  updateDateRangeInput(session, "date_range",
      start = start_date
    )

})

  # date selector for filtering
  # min <- min(df_joined$wk_start_date)
  max <- max(df_joined$wk_start_date)
  dateRangeInput('date_range',
        label = 'Date Range:',
        # start = Sys.Date() - (10 * 7),
        end = max,
        # min = min,
        max = max
  )

```

**Comment by gadenbuie** [comment]
Thanks for reporting this and thank you @pkopps for providing a solution.
