### ISSUE TITLE
How to debug flexdashboard?

### ISSUE THREAD

**Issue by zhiboz** [rstudio/flexdashboard#91]
thanks a ton for this great tool! although very much enjoy prototyping with it, I did not figure out a way to debug with RStudio by adding a breakpoint. any pointer would be greatly appreciated!

**Comment by duckontheweb** [comment]
@zhiboz What was the resolution for this issue? I have the same need to add a breakpoint in some R code within a flexdashboard R Markdown file and I am curious what your solution was. Thanks!

**Comment by maxmoro** [comment]
Same here :)

**Comment by mxblsdl** [comment]
`browser()` calls are picked up when you source the flexdashboard with through `rmarkdown::run(path_to_rmd)`.
