### ISSUE TITLE
Unable to get scrollbars with vertical_layout: scroll

### ISSUE THREAD

**Issue by richarddmorey** [rstudio/flexdashboard#92]
I installed the github version of flexdashboard today. I'm trying to build the document `solve.Rmd_` here (I added the underscore to prevent github from rendering the markdown):

https://gist.github.com/richarddmorey/6342de8bee6bae057613e667406a9ff7

which compiles `test.Rmd` to markdown and renders it in a chunk. `test.Rmd` is only the rmarkdown template page in Rstudio. I'd like the second, markdown chunk to either have a scrollbar by itself (so that one can scroll down and see the rest of the document, but leave the rest of the interface in place) or just have the whole page scroll. But `vertical_layout: scroll` doesn't seem to do what I'd expect. Building the file just gives a fixed-height chunk.

Any way to get this working?

**Comment by gadenbuie** [comment]
Thanks for reporting this! I'm not able to completely reproduce the issue you described using your example. I'm hoping by now you've found other ways to achieve this goal. One suggestion for anyone else who finds this issue: you might want to look into using [rmarkdown::html_fragment()](https://pkgs.rstudio.com/rmarkdown/reference/html_fragment.html) for rendering the "child" document.
