### ISSUE TITLE
Is it possible to add target="_blank" to an href link ? 

### ISSUE THREAD

**Issue by pachevalier** [rstudio/flexdashboard#93]
I would like to put a link to the header and add the option target="_blank". I've tried the following syntax : 

    - { title: "Data", icon: "fa-database", href: "http://www.data.gouv.fr/fr/", target: "_blank"}

This doesn't work. Is there any solution ?

**Comment by pachevalier** [comment]
Thanks to your quick answer. I've no idea how to write the jquery script. What would be the keyword to find the solution ?

**Comment by jjallaire** [comment]
Just add this to the bottom of your document:

    ```{js}
    setTimeout(function(){
      $('a[href="http://www.data.gouv.fr/fr/"]').attr('target', '_blank')
    }, 1000)
    ```

**Comment by jjallaire** [comment]
Just added support for the "target" field in navbar links so you won't need to use the jquery solution.

**Comment by pachevalier** [comment]
Thanks 👍 . It's so great to open an issue on Friday and to come back on Monday with a new feature !!!!!!

**Comment by jjallaire** [comment]
No worries, it was a feature that should have been there from day one!
