### ISSUE TITLE
Error publishing shiny powered flexdashboard using development version of a package

### ISSUE THREAD

**Issue by abresler** [rstudio/flexdashboard#96]
I am trying to publish a shiny powered flexdashboard.  I have some development versions of packages not on CRAN and it is causing errors to be thrown.  How do I point the RMD file to install packages from github.  A good example is this error being thrown from having the development  version of stringr

```Error: Unhandled Exception: Child Task 262270799 failed: Error building image: Error fetching stringr (1.1.0.9000) source. Error accessing GitHub repository hadley/stringr. HTTP 301: Moved Permanently```

**Comment by jjallaire** [comment]
A better option would be for packrat to be able to follow redirects when downloading packages (it looks like `devtools::install_github` already does). @kevinushey how hard would this be?

@trestletech @aronatkins  FYI this may cause a bunch of deployments to break unless/until packrat can deal with the redirect.

**Comment by kevinushey** [comment]
I think we need more information -- I just tested this, and everything works fine for me on both OS X and Windows with the latest Packrat. The following script works fine for me:

```
url <- "https://api.github.com/repos/hadley/stringr/tarball/master"
packrat:::githubDownload(url, destfile = tempfile())
packrat:::download(url = url, destfile = tempfile())

if (nzchar(Sys.which("curl")))
  download.file(url, destfile = tempfile(), method = "curl", extra = "-L -f")

if (nzchar(Sys.which("wget")))
  download.file(url, destfile = tempfile(), method = "wget", extra = "")
```

These are the code paths that Packrat would potentially be using for download here. @abresler, what is the output of `sessionInfo()`?
