### ISSUE TITLE
Allow for specific column widths within orientation: row

### ISSUE THREAD

**Issue by DataStrategist** [rstudio/flexdashboard#97]
I would like to be able to specify the widths of columns within an `orientation: row` setting, in order to implement something like this:

![image](https://cloud.githubusercontent.com/assets/8094091/19447336/6a4d6f70-9473-11e6-8941-f54ec47958f7.png)

As is, there is no good way to show a very tall but skinny table without wasting massive screen real-estate in a row oriented dashboard.

**Comment by statquant** [comment]
Being able to create a custom layout is indeed the most missing feature

**Comment by gadenbuie** [comment]
flexdashboard's design makes it easy to use R Markdown syntax to create a dashboard, but a trade-off in that approach is that custom layouts become more difficult. For a layout like the one described here, I'd recommend using [gridlayout](https://github.com/rstudio/gridlayout) or [Shiny](https://shiny.rmarkdown.com).

**Comment by kendavidn** [comment]
I think this is now possible with data-width?
