### ISSUE TITLE
Function for converting name to href?

### ISSUE THREAD

**Issue by dnegrey** [rstudio/flexdashboard#99]
What function (or logic) is used to convert the name of a page to the href text in the anchor tag of the resulting HTML? Here is a more aggregious example:

    3Miles_ per Gallon.1
    ====================

The name is correctly used in the HTML navigation, but the actual href text in the link is:

`#miles_-per-gallon1`

I'm assuming (and hoping) there's an existing function that is used to clean up the name for use in the href, something like: `f("3Miles_ per Gallon.1") == "miles_-per-gallon1"`

**Comment by jjallaire** [comment]
That's actually handled automatically by pandoc (so the function you are seeking is somewhere in the pandoc source oode). You can however override the automatically generated ID via:

```
3Miles_ per Gallon.1 {#3-miles-per-gallon}
====================
```
